<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of logs'); ?></h3>
    <?php if (!empty($list)) { ?>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Name'); ?></th>
            <th><?php _e('Identity'); ?></th>
            <th><?php _e('Email'); ?></th>
            <th><?php _e('Amount'); ?></th>
            <th><?php _e('Time Update'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $credit) { ?>
        <tr>
            <td><?php echo $this->escape($credit['id']); ?></td>
            <td><?php echo $this->escape($credit['user']['name']); ?></td>
            <td><?php echo $this->escape($credit['user']['identity']); ?></td>
            <td><?php echo $this->escape($credit['user']['email']); ?></td>
            <td><?php echo $this->escape($credit['amount_view']); ?></td>
            <td><?php echo $this->escape($credit['time_update_view']); ?></td>
            <td>
                <a class="btn btn-primary btn-xs" title="<?php _e('Update credit'); ?>" href="<?php echo $this->url('admin', array(
                    'controller' => 'credit',
                    'action' => 'update',
                    'uid' => $credit['uid'],
                )); ?>"><?php _e('Update credit'); ?></a>
                <a class="btn btn-success btn-xs" title="<?php _e('History'); ?>" href="<?php echo $this->url('admin', array(
                    'controller' => 'credit',
                    'action' => 'history',
                    'uid' => $credit['uid'],
                )); ?>"><?php _e('History'); ?></a>
                <a class="btn btn-success btn-xs" title="<?php _e('User information'); ?>" href="<?php echo $this->url('admin', array(
                    'module' => 'user',
                    'controller' => 'edit',
                    'action' => 'index',
                    'uid' => $credit['uid'],
                )); ?>" target="_blank"><?php _e('User information'); ?></a>
            </td>
        </tr>
        <?php } ?>
    </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert"><?php _e('No credit information used yet'); ?></div>
    <?php } ?>
</div>