<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingForm">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseForm" aria-expanded="false" aria-controls="collapseForm">
                        <i class="fas fa-plus"></i> <?php _e('Filter users'); ?>
                    </a>
                </h4>
            </div>
            <div id="collapseForm" class="panel-collapse collapse" role="tabpanel">
                <div class="panel-body">
                    <?php echo $this->form($form); ?>
                </div>
            </div>
        </div>
    </div>
    <h3><?php _e('List of users'); ?></h3>
    <?php if (!empty($list)) { ?>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('Name'); ?></th>
            <th><?php _e('Amount'); ?></th>
            <th><?php _e('Time Update'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $credit) { ?>
        <tr>
            <td>
                <?php if (!empty($credit['user']['first_name']) && !empty($credit['user']['last_name'])) { ?>
                    <span><?php echo $this->escape($credit['user']['first_name']); ?> <?php echo $this->escape($credit['user']['last_name']); ?></span>
                <?php } else { ?>
                    <span><?php echo $this->escape($credit['user']['name']); ?></span>
                <?php } ?>
                <small>(<?php _e('ID'); ?> : <?php echo $this->escape($credit['user']['id']); ?>)</small>
            </td>
            <td>
                <?php echo $this->escape($credit['amount_view']); ?>
                <button type="button" class="btn btn-link btn-xs text-right" data-toggle="modal" data-target="#creditModal<?php echo $this->escape($credit['id']); ?>">
                    <i class="fas fa-info-circle" aria-hidden="true"></i>
                </button>
                <div class="modal fade" id="creditModal<?php echo $this->escape($credit['id']); ?>" tabindex="-1" role="dialog" aria-labelledby="creditModalLabel<?php echo $this->escape($credit['id']); ?>">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="creditModalLabel<?php echo $this->escape($credit['id']); ?>"><?php _e('Amount details'); ?></h4>
                            </div>
                            <div class="modal-body">
                                <?php foreach ($credit['amount_detail_view'] as $amountDetail) { ?>
                                    <p><?php echo $amountDetail['module_title']; ?> : <strong><?php echo $amountDetail['amount_view']; ?></strong></p>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td><?php echo $this->escape($credit['time_update_view']); ?></td>
            <td>
                <a class="btn btn-primary btn-xs" title="<?php _e('Update credit'); ?>" href="<?php echo $this->url('admin', array(
                    'controller' => 'credit',
                    'action' => 'update',
                    'uid' => $credit['uid'],
                )); ?>"><?php _e('Update credit'); ?></a>
                <a class="btn btn-success btn-xs" title="<?php _e('History'); ?>" href="<?php echo $this->url('admin', array(
                    'controller' => 'credit',
                    'action' => 'history',
                    'uid' => $credit['uid'],
                )); ?>"><?php _e('History'); ?></a>
                <a class="btn btn-success btn-xs" title="<?php _e('User information'); ?>" href="<?php echo $this->url('admin', array(
                    'module' => 'user',
                    'controller' => 'edit',
                    'action' => 'index',
                    'uid' => $credit['uid'],
                )); ?>" target="_blank"><?php _e('User information'); ?></a>
            </td>
        </tr>
        <?php } ?>
    </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert"><?php _e('No credit information used yet'); ?></div>
    <?php } ?>
</div>