<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of Delivery methods'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $delivery) { ?>
                <?php
                if ($delivery['status'] == 1) {
                    $labelIdClass = 'label-success';
                } else {
                    $labelIdClass = 'label-warning';
                }
                ?>
                <tr>
                    <td><span
                            class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($delivery['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($delivery['title']); ?></td>
                    <td>
                        <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', array('action' => 'update', 'id' => $delivery['id'])); ?>"><i
                                class="fas fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert"><?php _e('No delivery methods is not created yet'); ?></div>
        <div class="alert alert-info" role="alert">
            <h4><?php _e('Todo list for fist time'); ?></h4>
            <ol>
                <li><?php _e('Setup payment gateway from gateway tap'); ?></li>
                <li><?php _e('Setup delivery method from delivery tap'); ?></li>
                <li><?php _e('Setup location from location tap'); ?></li>
            </ol>
        </div>
    <?php } ?>
</div>