<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h1 class="mb-3"><?php _e('List of all available gateways'); ?></h1>
    <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
        <tr>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Status'); ?></th>
            <th><?php _e('Gateway detail'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $item) { ?>
            <tr>
                <td><?php echo $item['title']; ?></td>
                <td>
                    <?php if (isset($item['status']) && $item['status'] == 1) { ?>
                        <span class="badge badge-success"><?php _e('Active'); ?></span>
                    <?php } elseif (isset($item['status']) && $item['status'] == 0) { ?>
                        <span class="badge badge-warning"><?php _e('Inactive'); ?></span>
                    <?php } else { ?>
                        <span class="badge badge-danger"><?php _e('Not installed'); ?></span>
                    <?php } ?>
                </td>
                <td>
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#<?php echo $item['path']; ?>Modal">
                        <?php _e('Gateway detail'); ?>
                    </button>
                    <div class="modal fade" id="<?php echo $item['path']; ?>Modal" tabindex="-1" role="dialog"
                         aria-labelledby="<?php echo $item['path']; ?>ModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="<?php echo $item['path']; ?>ModalLabel"><?php echo $item['title']; ?>
                                        (<?php echo $item['path']; ?>)</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>"><span
                                                aria-hidden="true">&times;</span></button>
                                </div>
                                <div class="modal-body">
                                    <div class="clearfix">
                                        <div class="col-lg-6 col-md-6">
                                            <ul class="list-unstyled">
                                                <li><strong><?php _e('Description'); ?></strong> : <?php echo $item['description']; ?></li>
                                                <li><strong><?php _e('Version'); ?></strong> : <?php echo $item['version']; ?></li>
                                                <li><strong><?php _e('Author'); ?></strong> : <?php echo $item['author']; ?></li>
                                                <li><strong><?php _e('Credits'); ?></strong> : <?php echo $item['credits']; ?></li>
                                                <li><strong><?php _e('Release Date'); ?></strong> : <?php echo _date($item['releaseDate']); ?></li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-6 col-md-6">
                                            <?php if (isset($item['option']) && !empty($item['option'])) { ?>
                                                <ul class="list-unstyled">
                                                    <?php foreach ($item['option'] as $key => $value) { ?>
                                                        <li><strong><?php _e($key); ?></strong> : <?php echo $value; ?></li>
                                                    <?php } ?>
                                                </ul>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td>
                    <?php if (isset($item['status']) && $item['status'] == 1) { ?>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['controller' => 'gateway', 'action' => 'update', 'path' => $item['path']]); ?>"><?php _e(
                                'Edit'
                            ); ?></a>
                        <a class="btn btn-warning btn-sm" title="<?php _e('Inactive'); ?>"
                           href="<?php echo $this->url('', ['controller' => 'gateway', 'action' => 'status', 'path' => $item['path']]); ?>"><?php _e(
                                'Inactive'
                            ); ?></a>
                    <?php } elseif (isset($item['status']) && $item['status'] == 0) { ?>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['controller' => 'gateway', 'action' => 'update', 'path' => $item['path']]); ?>"><?php _e(
                                'Edit'
                            ); ?></a>
                        <a class="btn btn-success btn-sm" title="<?php _e('Active'); ?>"
                           href="<?php echo $this->url('', ['controller' => 'gateway', 'action' => 'status', 'path' => $item['path']]); ?>"><?php _e(
                                'Active'
                            ); ?></a>
                    <?php } else { ?>
                        <a class="btn btn-success btn-sm" title="<?php _e('Install'); ?>"
                           href="<?php echo $this->url('', ['controller' => 'gateway', 'action' => 'update', 'path' => $item['path']]); ?>"><?php _e(
                                'Install'
                            ); ?></a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>
