<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingForm">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseForm" aria-expanded="false" aria-controls="collapseForm">
                        <i class="fas fa-plus"></i> <?php _e('Filter invoices'); ?>
                    </a>
                </h4>
            </div>
            <div id="collapseForm" class="panel-collapse collapse" role="tabpanel">
                <div class="panel-body">
                    <?php echo $this->form($form); ?>
                </div>
            </div>
        </div>
    </div>
    <h3><?php _e('List of invoices'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th class="col-md-1"><?php _e('Invoice ID'); ?></th>
                <th class="col-md-1"><?php _e('Status'); ?></th>
                <th class="col-md-1"><?php _e('Type'); ?></th>
                <th class="col-md-1"><?php _e('Type payment'); ?></th>
                <th class="col-md-1"><?php _e('Time Create'); ?></th>
                <th class="col-md-1"><?php _e('Total price'); ?></th>
                <th class="col-md-1"><?php _e('Information'); ?></th>
                <th class="col-md-7"><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $invoice) { ?>
                <?php
                    $labelIdClass = '';
                    if ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_VALIDATED) {
                        $labelIdClass = 'label-success';
                    } elseif ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_DRAFT) {
                        $labelIdClass = 'label-warning';
                    } elseif ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_CANCELLED) {
                        $labelIdClass = 'label-danger';
                    }
                    $class = '';
                    if ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_VALIDATED) {
                        if ($invoice['status_payment'] == \Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_UNPAID) {
                            $class = 'danger';
                        } else if ($invoice['status_payment'] == \Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID) {
                           $class = 'success';
                        }  
                    } 
                ?>
                
                <tr class="<?php echo $class ?>">
                    <td><?php echo $this->escape($invoice['code']); ?></td>
                    <td><span class="label <?php echo $labelIdClass; ?>"><?php echo \Module\Order\Model\Invoice::getStatusList()[$invoice['status']]; ?></span></td>
                    <td><?php echo $this->escape($invoice['type']); ?></td>
                    <td><?php echo $this->escape($invoice['type_payment']); ?></td>
                    <td><?php echo $this->escape($invoice['time_create_view']); ?></td>
                    <td><?php echo $this->escape($invoice['total_price_view']); ?></td>
                    <td>
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <?php echo $this->escape($invoice['first_name']); ?>
                                <?php echo $this->escape($invoice['last_name']); ?>
                            </li>
                        </ul>
                    </td>
                    
                    <td class="text-right">
                        <a class="btn btn-primary btn-xs" title="<?php _e('Download'); ?>"
                           href="<?php echo $this->url('', array('action' => 'print-pdf', 'id' => $invoice['id'])); ?>"
                           target="_blank"><i class="fas fa-download"></i> <?php _e('Download'); ?></a>
                        <a class="btn btn-primary btn-xs" title="<?php _e('Order'); ?>"
                           href="<?php echo $this->url('', array('controller' => 'order', 'action' => 'view', 'id' => $invoice['order'])); ?>"
                           target="_blank"><i class="far fa-eye"></i> <?php _e('Order'); ?></a>
                        <a class="btn btn-primary btn-xs" title="<?php _e('View'); ?>"
                           href="<?php echo $this->url('', array('action' => 'view', 'id' => $invoice['id'])); ?>"><i
                                class="far fa-eye" target="_blank"></i> <?php _e('View'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
        <p>
            <span class="label label-success"><?php _e('Paid'); ?></span>
            <span class="label label-warning"><?php _e('Unpaid'); ?></span>
            <span class="label label-danger"><?php _e('Canceled'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert"><?php _e('No invoice is created yet'); ?></div>
        <div class="alert alert-info" role="alert">
            <h4><?php _e('Todo list for fist time'); ?></h4>
            <ol>
                <li><?php _e('Setup payment gateway from gateway tap'); ?></li>
                <li><?php _e('Setup delivery method from delivery tap'); ?></li>
                <li><?php _e('Setup location from location tap'); ?></li>
            </ol>
        </div>
    <?php } ?>
</div>
