<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php echo sprintf($invoice['type'] == 'CREDIT' ? __('Credit Note %s') : __('Invoice %s'), $this->escape($invoice['code'])); ?></h3>

    <div class="card">
        <div class="card-header clearfix row">
            <div class="col-md-4">
                <p><strong><?php _e('Invoicing address') ?></strong></p>
                <hr/>
                <p>
                    <?php if (!empty($addressInvoicing['first_name']) && !empty($addressInvoicing['last_name'])) { ?>
                        <?php echo $this->escape($addressInvoicing['first_name']); ?> <?php echo $this->escape($addressInvoicing['last_name']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['id_number'])) { ?>
                        <?php echo $this->escape($addressInvoicing['id_number']); ?><br/>
                    <?php } ?>
                </p>
                <p>
                    <?php if (!empty($addressInvoicing['address1'])) { ?>
                        <?php echo $this->escape($addressInvoicing['address1']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['address2'])) { ?>
                        <?php echo $this->escape($addressInvoicing['address2']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['zip_code'])) { ?>
                        <?php echo $this->escape($addressInvoicing['zip_code']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['city'])) { ?>
                        <?php echo $this->escape($addressInvoicing['city']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['state'])) { ?>
                        <?php echo $this->escape($addressInvoicing['state']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['country'])) { ?>
                        <?php echo $this->escape($addressInvoicing['country']); ?><br/>
                    <?php } ?>
                </p>
                <p>
                    <?php if (!empty($addressInvoicing['email'])) { ?>
                        <?php _e('Email'); ?> : <?php echo $this->escape($addressInvoicing['email']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['phone'])) { ?>
                        <?php _e('Phone'); ?> : <?php echo $this->escape($addressInvoicing['phone']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['mobile'])) { ?>
                        <?php _e('Mobile'); ?> : <?php echo $this->escape($addressInvoicing['mobile']); ?><br/>
                    <?php } ?>
                </p>
                <p>
                    <?php if (!empty($addressInvoicing['company'])) { ?>
                        <?php echo $this->escape($addressInvoicing['company']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['company_id'])) { ?>
                        <?php echo $this->escape($addressInvoicing['company_id']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['company_vat'])) { ?>
                        <?php echo $this->escape($addressInvoicing['company_vat']); ?><br/>
                    <?php } ?>
                </p>
            </div>
            <div class="col-md-4">
                <p><strong><?php _e('Delivery address') ?></strong></p>
                <hr/>
                <p>
                    <?php if (!empty($addressDelivery['first_name']) && !empty($addressDelivery['last_name'])) { ?>
                        <?php echo $this->escape($addressDelivery['first_name']); ?> <?php echo $this->escape($addressDelivery['last_name']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['id_number'])) { ?>
                        <?php echo $this->escape($addressDelivery['id_number']); ?><br/>
                    <?php } ?>
                </p>
                <p>
                    <?php if (!empty($addressDelivery['address1'])) { ?>
                        <?php echo $this->escape($addressDelivery['address1']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['address2'])) { ?>
                        <?php echo $this->escape($addressDelivery['address2']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['zip_code'])) { ?>
                        <?php echo $this->escape($addressDelivery['zip_code']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['city'])) { ?>
                        <?php echo $this->escape($addressDelivery['city']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['state'])) { ?>
                        <?php echo $this->escape($addressDelivery['state']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['country'])) { ?>
                        <?php echo $this->escape($addressDelivery['country']); ?><br/>
                    <?php } ?>
                </p>
                <p>
                    <?php if (!empty($addressDelivery['email'])) { ?>
                        <?php _e('Email'); ?> : <?php echo $this->escape($addressDelivery['email']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['phone'])) { ?>
                        <?php _e('Phone'); ?> : <?php echo $this->escape($addressDelivery['phone']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['mobile'])) { ?>
                        <?php _e('Mobile'); ?> : <?php echo $this->escape($addressDelivery['mobile']); ?><br/>
                    <?php } ?>
                </p>
                <p>
                    <?php if (!empty($addressDelivery['company'])) { ?>
                        <?php echo $this->escape($addressDelivery['company']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['company_id'])) { ?>
                        <?php echo $this->escape($addressDelivery['company_id']); ?><br/>
                    <?php } ?>
                    <?php if (!empty($addressDelivery['company_vat'])) { ?>
                        <?php echo $this->escape($addressDelivery['company_vat']); ?><br/>
                    <?php } ?>
                </p>
            </div>
            <div class="col-md-4">
                <p><strong><?php _e('Informations') ?></strong></p>
                <hr/>
                <p><strong><?php _e('Status'); ?></strong> :
                    <?php if ($invoice['status'] == \Module\Order\Model\Invoice::STATUS_INVOICE_VALIDATED) { ?>
                        <span class="badge badge-success"><?php _e('Validated'); ?></span>
                    <?php } elseif ($invoice['status'] == \Module\Order\Model\Invoice::STATUS_INVOICE_DRAFT) { ?>
                        <span class="badge badge-warning"><?php _e('Draft'); ?></span>
                    <?php } else { ?>
                        <span class="badge badge-danger"><?php _e('Canceled'); ?></span>
                    <?php } ?>
                </p>

                <p><strong><?php _e('Order'); ?></strong> : <span><?php echo $this->escape($order['code']); ?></span>
                </p>

                <p><strong><?php _e('Time Create'); ?></strong> :
                    <span><?php echo $this->escape($invoice['time_create_view']) . ' ' . date('H:i', $invoice['time_create']) ; ?> </span></p>
                
                <p><strong><?php _e('Time invoice'); ?></strong> :
                    <span><?php echo $this->escape($invoice['time_invoice_view']) ?> </span>
                </p>
                
                <?php if ($invoice['shipping_price'] > 0) { ?>
                    <p><strong><?php _e('Shipping price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['shipping_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['packing_price'] > 0) { ?>
                    <p><strong><?php _e('Packing price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['packing_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['vat_price'] > 0) { ?>
                    <p><strong><?php _e('Vat price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['vat_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['total_price'] > 0) { ?>
                    <p><strong><?php _e('Total price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['total_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['paid_price'] > 0) { ?>
                    <p><strong><?php _e('Paid price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['paid_price_view']); ?></span></p>
                <?php } ?>
            </div>
            <div class="col-md-12 text-right">
                <a class="btn btn-primary" title="<?php _e('View order'); ?>"
                   href="<?php echo $this->url('', array('controller' => 'order', 'action' => 'view', 'id' => $invoice['order'])); ?>"
                   target="_blank"><i class="far fa-eye"></i> <?php _e('View order'); ?></a>
                <a class="btn btn-primary" title="<?php _e('Print'); ?>"
                   href="<?php echo $this->url('', array('controller' => 'invoice', 'action' => 'print-pdf', 'id' => $invoice['id'])); ?>"
                   target="_blank"><i class="fas fa-print"></i> <?php _e('Print'); ?></a>
            </div>
        </div>
        
    </div>
     <div class="clearfix mt-3">
        <h3><?php _e('Installments'); ?></h3>
        <?php if (count($invoice['installments']) == 0) { ?>
            <?php _e('You did not validate your invoice yet, installment are not generated !') ?>
        <?php } else { ?> 
            <?php foreach ($invoice['installments'] as $installment) { ?>
                <table class="table table-striped table-bordered table-sm">
                    <tr>
                        <th class="table-col-md-2"><?php _e('Installment'); ?></th>
                        <th class="table-col-md-1"><?php _e('Price'); ?></th>
                        <th class="table-col-md-1"><?php _e('Credit price'); ?></th>
                        <th class="table-col-md-2"><?php _e('Due date'); ?></th>
                        <th class="table-col-md-2"><?php _e('Time pay'); ?></th>
                        <th class="table-col-md-2"><?php _e('Gateway'); ?></th>
                        <th class="table-col-md-1"><?php _e('Status'); ?></th>
                        <th class="table-col-md-1 text-right"><?php _e('Action'); ?></th>
                    </tr>
                    <?php
                    $rowClass = '';
                    if ($installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_UNPAID) {
                        $badgeIdClass = 'badge-warning';
                    } elseif ($installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID) {
                        $badgeIdClass = 'badge-success';
                    } 
                    ?>
                    <tr>
                        <td><?php echo $installment['count'] . ' / ' . count($invoice['installments']) ?></td>
                        <td><?php echo $this->escape($installment['due_price_view']); ?></td>
                        <td><?php echo $this->escape($installment['credit_price_view']); ?></td>
                        <td><?php echo $this->escape($installment['time_duedate_view']); ?></td>
                        <td><?php echo $this->escape($installment['time_payment_view']); ?></td>
                        <td><?php echo isset($gateways[$installment['gateway']]) ? $gateways[$installment['gateway']] : ''; ?></td >
                        <td><span class="badge <?php echo $badgeIdClass; ?>"><?php echo $installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID ? __('Paid') : __('Unpaid') ?></span></td>
                        <td class="text-right">
                            <?php 
                            $type = '';
                            if (isset($gatewaysInfo[$installment['gateway']])) {
                                $type = $gatewaysInfo[$installment['gateway']]['type'];
                            }
                            $readonly = $installment['status_payment'] == \Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID && $type == 'online';
                            if ($invoice['status'] != \Module\Order\Model\Invoice::STATUS_INVOICE_CANCELLED && !$readonly) { ?> 
                                <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'installment', 'action' => 'edit', 'id' => $installment['id'])); ?>">
                                    <i class="fas fa-pencil-alt"></i> <?php _e('Edit'); ?></a>
                            <?php } ?>
                        </td>
                    </tr>
                </table>
            <?php } ?>
        <?php } ?>
    </div>
    <?php if (!empty($invoice['log'])) { ?>
        <div class="clearfix">
            <h3><?php _e('Logs'); ?></h3>

                    <?php foreach ($invoice['log'] as $log) { ?>
            <div class="card">
                <div class="card-header clearfix row">
                        <div class="well">
                            <p><strong><?php _e('Id'); ?></strong> : <?php echo $this->escape($log['id']); ?></p>

                            <p><strong><?php _e('Invoice'); ?></strong> : <?php echo $this->escape($log['invoice']); ?></p>

                            <p><strong><?php _e('Gateway'); ?></strong> : <?php echo $this->escape($log['gateway']); ?></p>

                            <p><strong><?php _e('Create'); ?></strong> : <?php echo $this->escape($log['time_create_view']); ?>
                            </p>

                            <p><strong><?php _e('User'); ?></strong> : <?php echo $this->escape($log['uid']); ?></p>

                            <p><strong><?php _e('Amount'); ?></strong> : <?php echo $this->escape($log['amount_view']); ?></p>

                            <p><strong><?php _e('Authority'); ?></strong> : <?php echo $this->escape($log['authority']); ?></p>

                            <p><strong><?php _e('Status'); ?></strong> : <?php echo $this->escape($log['status']); ?></p>

                            <p><strong><?php _e('Ip'); ?></strong> : <?php echo $this->escape($log['ip']); ?></p>

                            <p><strong><?php _e('Message'); ?></strong> : <?php echo $this->escape($log['message']); ?></p>
                            <pre><code><?php print_r($log['value']); ?></code></pre>
                        </div>
                </div>
            </div>
                        <hr/>
                    <?php } ?>

        </div>
    <?php } ?>
</div>
