<div class="clearfix">
    <h3><?php echo sprintf(__('Update invoice %s'), $this->escape($invoice['code'])); ?></h3>

    <div class="card">
        <div class="clearfix card-body">
            <div class="col-lg-6 col-md-6">
                <p><strong><?php _e('Status'); ?></strong> :
                    <?php
                    if ($invoice['status'] == \Module\Order\Model\Invoice::STATUS_INVOICE_DRAFT) {
                        $class = "warning";
                    } elseif ($invoice['status'] == \Module\Order\Model\Invoice::STATUS_INVOICE_VALIDATED) {
                        $class = "success";
                    } else {
                        $class = "danger";
                    }
                    ?>
                    <span class="badge badge-<?php echo $class ?>"><?php echo \Module\Order\Model\Invoice::getStatusList()[$invoice['status']] ?></span>
                </p>

                <p><strong><?php _e('Order'); ?></strong> : <span><?php echo $this->escape($order['code']); ?></span>
                </p>

                <p><strong><?php _e('Gateway'); ?></strong> :
                    <span><?php echo $this->escape($invoice['gateway']); ?></span></p>

                <p><strong><?php _e('Time create'); ?></strong> :
                    <span><?php echo $this->escape($invoice['time_create_view']); ?> </span></p>

                <p><strong><?php _e('Time invoice'); ?></strong> :
                    <span><?php echo $this->escape($invoice['time_invoice_view']); ?> </span></p>

                <?php if ($invoice['shipping_price'] > 0) { ?>
                    <p><strong><?php _e('Shipping price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['shipping_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['packing_price'] > 0) { ?>
                    <p><strong><?php _e('Packing price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['packing_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['vat_price'] > 0) { ?>
                    <p><strong><?php _e('Vat price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['vat_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['total_price'] > 0) { ?>
                    <p><strong><?php _e('Total price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['total_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['paid_price'] > 0) { ?>
                    <p><strong><?php _e('Paid price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['paid_price_view']); ?></span></p>
                <?php } ?>
            </div>
            <div class="col-lg-6 col-md-6">
                <?php if ($address['account_type'] === 'company') { ?>
                    <?php if (!empty($address['company'])) { ?>
                        <p><strong><?php _e('Name'); ?></strong> :
                            <span><?php echo $this->escape($address['company']); ?></span>
                        </p>
                    <?php } ?>
                    <?php if (!empty($address['id_number'])) { ?>
                        <p><strong><?php _e('ID number'); ?></strong> :
                            <span><?php echo $this->escape($address['id_number']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['company_address1'])) { ?>
                        <p><strong><?php _e('Address'); ?></strong> :
                            <span><?php echo $this->escape($address['company_address1']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['company_address2'])) { ?>
                        <p><strong><?php _e('Address addition'); ?></strong> :
                            <span><?php echo $this->escape($address['company_address2']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['company_city'])) { ?>
                        <p><strong><?php _e('City'); ?></strong> :
                            <span><?php echo $this->escape($address['company_city']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['company_state'])) { ?>
                        <p><strong><?php _e('State'); ?></strong> :
                            <span><?php echo $this->escape($address['company_state']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['company_country'])) { ?>
                        <p><strong><?php _e('Country'); ?></strong> :
                            <span><?php echo $this->escape($address['company_country']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['company_zip_code'])) { ?>
                        <p><strong><?php _e('Zip code'); ?></strong> :
                            <span><?php echo $this->escape($address['company_zip_code']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['company_id'])) { ?>
                        <p><strong><?php _e('Company ID'); ?></strong> :
                            <span><?php echo $this->escape($address['company_id']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['company_vat'])) { ?>
                        <p><strong><?php _e('Company VAT'); ?></strong> :
                            <span><?php echo $this->escape($address['company_vat']); ?></span></p>
                    <?php } ?>
                <?php } else { ?>
                    <?php if (!empty($address['first_name']) && !empty($address['last_name'])) { ?>
                        <p><strong><?php _e('Name'); ?></strong> :
                            <span><?php echo $this->escape($address['first_name']) . ' ' . $this->escape($address['last_name']); ?></span>
                        </p>
                    <?php } ?>
                    <?php if (!empty($address['id_number'])) { ?>
                        <p><strong><?php _e('ID number'); ?></strong> :
                            <span><?php echo $this->escape($address['id_number']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['address1'])) { ?>
                        <p><strong><?php _e('Address'); ?></strong> :
                            <span><?php echo $this->escape($address['address1']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['address2'])) { ?>
                        <p><strong><?php _e('Address addition'); ?></strong> :
                            <span><?php echo $this->escape($address['address2']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['city'])) { ?>
                        <p><strong><?php _e('City'); ?></strong> :
                            <span><?php echo $this->escape($address['city']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['state'])) { ?>
                        <p><strong><?php _e('State'); ?></strong> :
                            <span><?php echo $this->escape($address['state']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['country'])) { ?>
                        <p><strong><?php _e('Country'); ?></strong> :
                            <span><?php echo $this->escape($address['country']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['zip_code'])) { ?>
                        <p><strong><?php _e('Zip code'); ?></strong> :
                            <span><?php echo $this->escape($address['zip_code']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['email'])) { ?>
                        <p><strong><?php _e('Email'); ?></strong> :
                            <span><?php echo $this->escape($address['email']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['phone'])) { ?>
                        <p><strong><?php _e('Phone'); ?></strong> :
                            <span><?php echo $this->escape($address['phone']); ?></span></p>
                    <?php } ?>
                    <?php if (!empty($address['mobile'])) { ?>
                        <p><strong><?php _e('Mobile'); ?></strong> :
                            <span><?php echo $this->escape($address['mobile']); ?></span></p>
                    <?php } ?>
                <?php }  ?>
                <p>
                    <strong><?php _e('Type') ?></strong> :
                    <?php echo $address['account_type'] == 'none' ? __('ND') : __(ucfirst($address['account_type'])); ?>
                </p>
            </div>
            <div class="col-lg-12 col-md-12 text-right">
                <a class="btn btn-primary" title="<?php _e('View order'); ?>"
                   href="<?php echo $this->url('', ['controller' => 'order', 'action' => 'view', 'id' => $invoice['order']]); ?>"
                   target="_blank"><i class="far fa-eye"></i> <?php _e('View order'); ?></a>
                <a class="btn btn-primary" title="<?php _e('Print'); ?>"
                   href="<?php echo $this->url('', ['controller' => 'invoice', 'action' => 'print', 'id' => $invoice['id']]); ?>"
                   target="_blank"><i class="fas fa-print"></i> <?php _e('Print'); ?></a>
            </div>
        </div>
    </div>
    <?php if (!empty($invoice['log'])) { ?>
        <div class="clearfix">
            <h3><?php _e('Logs'); ?></h3>
            <?php foreach ($invoice['log'] as $log) { ?>
                <div class="card">
                    <div class="card-body">
                        <p>
                            <strong><?php _e('ID'); ?></strong> : <?php echo $this->escape($log['id']); ?>
                        </p>
                        <p>
                            <strong><?php _e('Invoice'); ?></strong> : <?php echo $this->escape($log['invoice']); ?>
                        </p>

                        <p>
                            <strong><?php _e('Gateway'); ?></strong> : <?php echo $this->escape($log['gateway']); ?>
                        </p>
                        <p>
                            <strong><?php _e('Create'); ?></strong> : <?php echo $this->escape($log['time_create_view']); ?>
                        </p>
                        <p>
                            <strong><?php _e('User'); ?></strong> : <?php echo $this->escape($log['uid']); ?>
                        </p>
                        <p>
                            <strong><?php _e('Amount'); ?></strong> : <?php echo $this->escape($log['amount_view']); ?>
                        </p>
                        <p>
                            <strong><?php _e('Authority'); ?></strong> : <?php echo $this->escape($log['authority']); ?>
                        </p>
                        <p>
                            <strong><?php _e('Status'); ?></strong> : <?php echo $this->escape($log['status']); ?>
                        </p>
                        <p>
                            <strong><?php _e('Ip'); ?></strong> : <?php echo $this->escape($log['ip']); ?>
                        </p>
                        <p>
                            <strong><?php _e('Message'); ?></strong> : <?php echo $this->escape($log['message']); ?>
                        </p>
                        <pre><?php print_r($log['value']); ?></pre>
                    </div>
                </div>
                <hr/>
            <?php } ?>
        </div>
    <?php } ?>
    <?php echo $this->form($form); ?>
</div>
