<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <br />
    <div class="well">
        <h3><?php _e('Filter invoices'); ?></h3>
        <?php echo $this->form($form); ?>
    </div>
    <h3><?php _e('List of invoices'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Amount'); ?></th>
                <th><?php _e('Time Create'); ?></th>
                <th><?php _e('Due date'); ?></th>
                <th><?php _e('Time pay'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach($list as $invoice) { ?>
                <?php
                // Set lable
                if($invoice['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif($invoice['status'] == 2) {
                    $labelIdClass = 'label-warning';
                } elseif($invoice['status'] == 3) {
                    $labelIdClass = 'label-danger';
                }
                // Set row class
                $rowClass = '';
                if ($invoice['status'] == 1) {
                    $rowClass = ' class="success"';
                } elseif ($invoice['time_duedate'] < strtotime("-1 day")) {
                    $rowClass = ' class="danger"';
                } elseif ($invoice['time_duedate'] < strtotime("+1 day")) {
                    $rowClass = ' class="warning"';
                }
                ?>
                <tr<?php echo $rowClass; ?>>
                    <td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($invoice['code']); ?></span></td>
                    <td><?php echo $this->escape($invoice['total_price_view']); ?></td>
                    <td><?php echo $this->escape($invoice['time_create_view']); ?></td>
                    <td><?php echo $this->escape($invoice['time_duedate_view']); ?></td>
                    <td><?php echo $this->escape($invoice['time_payment_view']); ?></td>
                    <td>
                        <a class="btn btn-primary" title="<?php _e('View'); ?>" href="<?php echo $this->url('', array('action' => 'view', 'id' => $invoice['id'])); ?>"><i class="fa fa-eye" target="_blank"></i> <?php _e('View'); ?></a>
                        <a class="btn btn-primary" title="<?php _e('View order'); ?>" href="<?php echo $this->url('', array('controller' => 'order', 'action' => 'view', 'id' => $invoice['order'])); ?>" target="_blank"><i class="fa fa-eye"></i> <?php _e('View order'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
        <p>
            <span class="label label-success"><?php _e('Paid'); ?></span>
            <span class="label label-warning"><?php _e('Unpaid'); ?></span>
            <span class="label label-danger"><?php _e('Canceled'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert"><?php _e('No invoice is not created yet'); ?></div>
        <div class="alert alert-info" role="alert">
            <h4><?php _e('Todo list for fist time'); ?></h4>
            <ul>
                <li><?php _e('1- Setup payment gateway from gateway tap'); ?></li>
                <li><?php _e('2- Setup delivery method from delivery tap'); ?></li>
                <li><?php _e('3- Setup location from location tap'); ?></li>
            </ul>
        </div>
    <?php } ?>
</div>