<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php echo sprintf(__('Invoice %s'), $this->escape($invoice['code'])); ?></h3>

    <div class="well">
        <div class="clearfix">
            <div class="col-md-4">
                <p><strong><?php _e('Informations') ?></strong></p>
                <hr/>
                <p><strong><?php _e('Status'); ?></strong> :
                    <?php if ($invoice['status'] == \Module\Order\Model\Invoice::STATUS_INVOICE_VALIDATED) { ?>
                        <span class="label label-success"><?php _e('Validated'); ?></span>
                    <?php } elseif ($invoice['status'] == \Module\Order\Model\Invoice::STATUS_INVOICE_DRAFT) { ?>
                        <span class="label label-warning"><?php _e('Draft'); ?></span>
                    <?php } else { ?>
                        <span class="label label-danger"><?php _e('Canceled'); ?></span>
                    <?php } ?>
                </p>

                <p><strong><?php _e('Bank ID'); ?></strong> : <?php echo $this->escape($invoice['random_id']); ?></p>

                <p><strong><?php _e('Order'); ?></strong> : <span><?php echo $this->escape($order['code']); ?></span>
                </p>

                <p><strong><?php _e('Time Create'); ?></strong> :
                    <span><?php echo $this->escape($invoice['time_create_view']) . ' ' . date('H:i', $invoice['time_create']) ; ?> </span></p>
                
                <?php if ($invoice['shipping_price'] > 0) { ?>
                    <p><strong><?php _e('Shipping price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['shipping_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['packing_price'] > 0) { ?>
                    <p><strong><?php _e('Packing price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['packing_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['vat_price'] > 0) { ?>
                    <p><strong><?php _e('Vat price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['vat_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['total_price'] > 0) { ?>
                    <p><strong><?php _e('Total price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['total_price_view']); ?></span></p>
                <?php } ?>
                <?php if ($invoice['paid_price'] > 0) { ?>
                    <p><strong><?php _e('Paid price'); ?></strong> :
                        <span><?php echo $this->escape($invoice['paid_price_view']); ?></span></p>
                <?php } ?>
            </div>
            <div class="col-md-4">
                <p><strong><?php _e('Invoicing address') ?></strong></p>
                <hr/>
                <?php if (!empty($addressInvoicing['first_name']) && !empty($addressInvoicing['last_name'])) { ?>
                    <p><strong><?php _e('Name'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['first_name']); ?> <?php echo $this->escape($addressInvoicing['last_name']); ?></span>
                    </p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['id_number'])) { ?>
                    <p><strong><?php _e('ID number'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['id_number']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['address1'])) { ?>
                    <p><strong><?php _e('Address'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['address1']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['address2'])) { ?>
                    <p><strong><?php _e('Address addition'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['address2']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['city'])) { ?>
                    <p><strong><?php _e('City'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['city']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['state'])) { ?>
                    <p><strong><?php _e('State'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['state']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['country'])) { ?>
                    <p><strong><?php _e('Country'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['country']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['zip_code'])) { ?>
                    <p><strong><?php _e('Zip code'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['zip_code']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['email'])) { ?>
                    <p><strong><?php _e('Email'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['email']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['phone'])) { ?>
                    <p><strong><?php _e('Phone'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['phone']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['mobile'])) { ?>
                    <p><strong><?php _e('Mobile'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['mobile']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['company'])) { ?>
                    <p><strong><?php _e('Company'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['company']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['company_id'])) { ?>
                    <p><strong><?php _e('Company ID'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['company_id']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressInvoicing['company_vat'])) { ?>
                    <p><strong><?php _e('Company VAT'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['company_vat']); ?></span></p>
                <?php } ?>
            </div>
            <div class="col-md-4">
                <p><strong><?php _e('Delivery address') ?></strong></p>
                <hr/>
                <?php if (!empty($addressDelivery['first_name']) && !empty($addressDelivery['last_name'])) { ?>
                    <p><strong><?php _e('Name'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['first_name']); ?> <?php echo $this->escape($addressDelivery['last_name']); ?></span>
                    </p>
                <?php } ?>
                <?php if (!empty($addressDelivery['id_number'])) { ?>
                    <p><strong><?php _e('ID number'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['id_number']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['address1'])) { ?>
                    <p><strong><?php _e('Address'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['address1']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['address2'])) { ?>
                    <p><strong><?php _e('Address addition'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['address2']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['city'])) { ?>
                    <p><strong><?php _e('City'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['city']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['state'])) { ?>
                    <p><strong><?php _e('State'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['state']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['country'])) { ?>
                    <p><strong><?php _e('Country'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['country']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['zip_code'])) { ?>
                    <p><strong><?php _e('Zip code'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['zip_code']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['email'])) { ?>
                    <p><strong><?php _e('Email'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['email']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['phone'])) { ?>
                    <p><strong><?php _e('Phone'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['phone']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['mobile'])) { ?>
                    <p><strong><?php _e('Mobile'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['mobile']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['company'])) { ?>
                    <p><strong><?php _e('Company'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['company']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['company_id'])) { ?>
                    <p><strong><?php _e('Company ID'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['company_id']); ?></span></p>
                <?php } ?>
                <?php if (!empty($addressDelivery['company_vat'])) { ?>
                    <p><strong><?php _e('Company VAT'); ?></strong> :
                        <span><?php echo $this->escape($addressDelivery['company_vat']); ?></span></p>
                <?php } ?>
            </div>
            <div class="col-md-12 text-right">
                <a class="btn btn-primary" title="<?php _e('View order'); ?>"
                   href="<?php echo $this->url('', array('controller' => 'order', 'action' => 'view', 'id' => $invoice['order'])); ?>"
                   target="_blank"><i class="fa fa-eye"></i> <?php _e('View order'); ?></a>
                <a class="btn btn-primary" title="<?php _e('Print'); ?>"
                   href="<?php echo $this->url('', array('controller' => 'invoice', 'action' => 'print-pdf', 'id' => $invoice['id'])); ?>"
                   target="_blank"><i class="fa fa-print"></i> <?php _e('Print'); ?></a>
            </div>
        </div>
    </div>
    <?php if (!empty($invoice['log'])) { ?>
        <div class="clearfix">
            <h3><?php _e('Logs'); ?></h3>
            <?php foreach ($invoice['log'] as $log) { ?>
                <div class="well">
                    <p><strong><?php _e('Id'); ?></strong> : <?php echo $this->escape($log['id']); ?></p>

                    <p><strong><?php _e('Invoice'); ?></strong> : <?php echo $this->escape($log['invoice']); ?></p>

                    <p><strong><?php _e('Gateway'); ?></strong> : <?php echo $this->escape($log['gateway']); ?></p>

                    <p><strong><?php _e('Create'); ?></strong> : <?php echo $this->escape($log['time_create_view']); ?>
                    </p>

                    <p><strong><?php _e('User'); ?></strong> : <?php echo $this->escape($log['uid']); ?></p>

                    <p><strong><?php _e('Amount'); ?></strong> : <?php echo $this->escape($log['amount_view']); ?></p>

                    <p><strong><?php _e('Authority'); ?></strong> : <?php echo $this->escape($log['authority']); ?></p>

                    <p><strong><?php _e('Status'); ?></strong> : <?php echo $this->escape($log['status']); ?></p>

                    <p><strong><?php _e('Ip'); ?></strong> : <?php echo $this->escape($log['ip']); ?></p>

                    <p><strong><?php _e('Message'); ?></strong> : <?php echo $this->escape($log['message']); ?></p>
                    <pre><?php print_r($log['value']); ?></pre>
                </div>
                <hr/>
            <?php } ?>
        </div>
    <?php } ?>
</div>
