<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of logs'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('User'); ?></th>
                <th><?php _e('Invoice'); ?></th>
                <th><?php _e('Adapter'); ?></th>
                <th><?php _e('Amount'); ?></th>
                <th><?php _e('Time Create'); ?></th>
                <th><?php _e('Details'); ?></th>
            </tr>
            <?php foreach ($list as $log) { ?>
                <?php
                if ($log['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($log['status'] == 2) {
                    $labelIdClass = 'label-warning';
                } elseif ($log['status'] == 0) {
                    $labelIdClass = 'label-danger';
                }
                ?>
                <tr>
                    <td>
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($log['id']); ?></span>
                    </td>
                    <td>
                        <a target="_blank" href="<?php echo $this->escape($log['user_url']); ?>">
                            <?php echo $this->escape($log['user']['name']); ?> (<?php echo $this->escape($log['user']['id']); ?>)
                        </a>
                    </td>
                    <td>
                        <a target="_blank" href="<?php echo $this->escape($log['invoice_url']); ?>">
                            <?php echo $this->escape($log['invoice']); ?> (<?php _e('View'); ?>)
                        </a>
                    </td>
                    <td>
                        <?php echo $this->escape($log['gateway']); ?>
                        <?php if ($log['gateway'] == 'Mellat') { ?>
                            <?php if (isset($log['value']['request']['SaleReferenceId'])) { ?>
                                ( <?php echo $log['value']['request']['SaleReferenceId']; ?> )
                            <?php } ?>
                        <?php } ?>
                    </td>
                    <td><?php echo $this->escape($log['amount']); ?></td>
                    <td><?php echo $this->escape($log['time_create_view']); ?></td>
                    <td>
                        <button type="button" class="btn btn-primary btn-xs" data-toggle="modal"
                                data-target="#log-modal-<?php echo $this->escape($log['id']); ?>">
                            <?php _e('Show details'); ?>
                        </button>
                        <div class="modal fade" id="log-modal-<?php echo $this->escape($log['id']); ?>" tabindex="-1"
                             role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title"><?php _e('Log details'); ?></h4>
                                    </div>
                                    <div class="modal-body">
                                        <pre><?php print_r($log); ?></pre>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
        <p>
            <span class="label label-success"><?php _e('Paid'); ?></span>
            <span class="label label-warning"><?php _e('Unpaid'); ?></span>
            <span class="label label-danger"><?php _e('Error'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert"><?php _e('No invoice is not set yet'); ?></div>
        <div class="alert alert-info" role="alert">
            <h4><?php _e('Todo list for fist time'); ?></h4>
            <ol>
                <li><?php _e('Setup payment gateway from gateway tap'); ?></li>
                <li><?php _e('Setup delivery method from delivery tap'); ?></li>
                <li><?php _e('Setup location from location tap'); ?></li>
            </ol>
        </div>
    <?php } ?>
</div>
