<?php
$this->css($this->assetModule('css/admin.css'));
$this->backbone();
?>
<div id="js-order" class="clearfix">
    <div id="accordion" role="tablist" aria-multiselectable="true">
        <div class="card">
            <div class="card-header" role="tab" id="headingForm">
                <h4 class="card-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseForm" aria-expanded="false"
                       aria-controls="collapseForm">
                        <i class="fas fa-plus"></i> <?php _e('Filter orders'); ?>
                    </a>
                </h4>
            </div>
            <div id="collapseForm" class="panel-collapse collapse" role="tabpanel">
                <div class="card-body">
                    <?php echo $this->form($form); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix row order-header mb-3">
        <div class="col-3">
            <h3><?php _e('List of orders'); ?></h3>
        </div>
        <div class="col-6 text-center totalOrder">
            <strong><?php echo __('{Own}') . ' ' . __('Ordered') . ' ' . date('Y') . ' : ' ?></strong> <?php echo _currency($totalOwnOrdered) ?>
            -
            <strong><?php echo __('Invoiced') . ' ' . date('Y') . ' : ' ?></strong> <?php echo _currency($totalOwnBilled) ?>
            ==
            <strong><?php echo __('Non invoiced') . ' ' . date('Y') . ' : ' ?></strong> <?php echo _currency($totalOwnOrdered - $totalOwnBilled) ?>
        </div>
        <div class="col-3 text-right">
            <a class="btn btn-success" title="<?php _e('New order'); ?>" href="<?php echo $this->url('', ['controller' => 'order', 'action' => 'add']); ?>">
                <i class="fas fa-plus"></i> <?php _e('New order'); ?>
            </a>
        </div>
    </div>
    <div class="clearfix row order-header mb-3">
        <div class="col-3">
        </div>
        <div class="col-6 text-center totalOrder">
            <strong><?php echo __('{Third}') . ' ' . __('Ordered') . ' ' . date('Y') . ' : ' ?></strong> <?php echo _currency($totalThirdOrdered) ?>
            -
            <strong><?php echo __('Invoiced') . ' ' . date('Y') . ' : ' ?></strong> <?php echo _currency($totalThirdBilled) ?>
            ==
            <strong><?php echo __('Non invoiced') . ' ' . date('Y') . ' : ' ?></strong> <?php echo _currency($totalThirdOrdered - $totalThirdBilled) ?>
        </div>
    </div>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
            <tr>
                <th class="text-center small"><?php _e('Code'); ?></th>
                <th class="text-center small"><?php _e('Date'); ?></th>
                <th class="text-center small"><?php _e('Total ordered'); ?></th>
                <th class="text-center small"><?php _e('Total invoiced'); ?></th>
                <th class="text-center small"><?php _e('Information'); ?></th>
                <th class="text-center small table-col-3"><?php _e('Products'); ?></th>
                <th class="clearfix table-col-6">
                    <ul class="list-inline">
                        <li class="list-inline-item text-center small table-col-2 "><?php _e('Order status'); ?></li>
                        <li class="list-inline-item text-center small table-col-2 "><?php _e('Can pay'); ?></li>
                        <li class="list-inline-item text-center small table-col-1 "><?php _e('Payment'); ?></li>
                        <li class="list-inline-item text-center small table-col-2 "><?php _e('Delivery'); ?></li>
                        <li class="list-inline-item text-center small table-col-1 "><?php _e('Note'); ?></li>
                        <li class="list-inline-item text-center small table-col-3 "><?php _e('Action'); ?></li>
                    </ul>
                </th>
            </tr>
            <?php foreach ($list as $order) { ?>
                <?php
                $class = '';
                if ($order['status_payment'] == \Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID) {
                    $class = 'success';
                } else {
                    if ($order['status_payment'] != null && $order['status_payment'] != ''
                        && $order['status_payment'] == \Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_UNPAID
                    ) {
                        $class = 'danger';
                    }
                } ?>
                <tr
                        class="table-<?php echo $class; ?>"
                        data-id="<?php echo $this->escape($order['id']); ?>"
                        data-order="<?php echo $this->escape($order['url_update_order']); ?>"
                        data-canPay="<?php echo $this->escape($order['url_update_canPay']); ?>"
                        data-delivery="<?php echo $this->escape($order['url_update_delivery']); ?>"
                        data-listUser="<?php echo $this->escape($order['url_list_user']); ?>"
                >
                    <td class="text-center small"><?php echo $this->escape($order['code']); ?></td>
                    <td class="text-center small"><?php echo _date($order['time_create']) . '<br>' . date('H:i', $order['time_create']); ?></td>
                    <td class="text-center small"><?php echo $this->escape($order['total_ordered_view']); ?></td>
                    <td class="text-center small"><?php echo $this->escape($order['total_own_billed_view']); ?></td>
                    <td class="text-center small">
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <?php echo $this->escape($order['first_name']); ?>
                                <?php echo $this->escape($order['last_name']); ?>
                            </li>
                        </ul>
                    </td>
                    <td class="text-center small">
                        <?php $productsList = [];
                        foreach ($order['products'] as $product) {
                            $productsList[] = $product['details']['title'];
                        }
                        echo implode('<br/>', $productsList); ?>
                    </td>
                    <td class="clearfix">
                        <ul class="list-inline">
                            <li class="list-inline-item table-col-2 text-center">
                                <?php if ($order['status_order'] == \Module\Order\Model\Order::STATUS_ORDER_VALIDATED) { ?>
                                    <span id="update-order-<?php echo $this->escape($order['id']); ?>"
                                          class="update-order btn btn-sm <?php echo $this->escape($order['orderClass']); ?>"><?php echo $this->escape(
                                            $order['orderTitle']
                                        ); ?></span>
                                <?php } else {
                                    if ($order['status_order'] == \Module\Order\Model\Order::STATUS_ORDER_DRAFT || $order['status_order'] == \Module\Order\Model\Order::STATUS_ORDER_PENDING) { ?>
                                        <span class="badge badge-warning"><?php echo $this->escape($order['orderTitle']); ?></span>
                                    <?php } else { ?>
                                        <span class="badge badge-danger"><?php echo $this->escape($order['orderTitle']); ?></span>
                                    <?php }
                                } ?>
                            </li>
                            <li class="list-inline-item table-col-2 text-center">
                                <span id="update-canPay-<?php echo $this->escape($order['id']); ?>"
                                      class="update-canPay btn btn-sm <?php echo $this->escape($order['canPayClass']); ?>"><?php echo $this->escape(
                                        $order['canPayTitle']
                                    ); ?></span>
                            </li>
                            <li class="list-inline-item table-col-1 text-center">
                                <?php if ($class == '') { ?>
                                    <span class="badge badge-warning" data-toggle="tooltip" data-placement="top" title="<?php _e('Pending'); ?>"><?php _e(
                                            'Pending'
                                        ); ?></span>
                                <?php } elseif ($class == 'success') { ?>
                                    <span class="badge badge-success" data-toggle="tooltip" data-placement="top" title="<?php _e('Paid'); ?>"><?php _e(
                                            'Paid'
                                        ); ?></span>
                                <?php } else { ?>
                                    <span class="badge badge-danger" data-toggle="tooltip" data-placement="top" title="<?php _e('Unpaid'); ?>"><?php _e(
                                            'Unpaid'
                                        ); ?></span>
                                <?php } ?>
                            </li>
                            <li class="list-inline-item table-col-2 text-center">
                                <?php if ($order['type_commodity'] == 'product') { ?>
                                    <span id="update-delivery-<?php echo $this->escape($order['id']); ?>"
                                          class="update-delivery btn btn-sm <?php echo $this->escape($order['deliveryClass']); ?>"><?php echo $this->escape(
                                            $order['deliveryTitle']
                                        ); ?></span>
                                <?php } else if ($order['type_commodity'] == 'booking') { ?>
                                    <span class="badge badge-secondary"><?php _e('Its a booking'); ?></span>
                                <?php } else { ?>
                                    <span class="badge badge-secondary"><?php _e('Its service'); ?></span>
                                <?php } ?>
                            </li>
                            <li class="list-inline-item table-col-1 text-center">
                                <?php if ($order['user_note']) { ?>
                                    <span class="far fa-comments"></span>
                                <?php } ?>
                            </li>
                            <li class="list-inline-item table-col-3 text-center">
                                <a class="btn btn-primary btn-sm" title="<?php _e('View'); ?>" href="<?php echo $this->escape($order['url_view']); ?>"
                                   target="_blank"><i class="far fa-eye"></i>
                                    <?php _e('View'); ?>
                                </a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert"><?php _e('No order is not created yet'); ?></div>
        <div class="alert alert-info" role="alert">
            <h4><?php _e('Todo list for fist time'); ?></h4>
            <ol>
                <li><?php _e('Setup payment gateway from gateway tap'); ?></li>
                <li><?php _e('Setup delivery method from delivery tap'); ?></li>
                <li><?php _e('Setup location from location tap'); ?></li>
            </ol>
        </div>
    <?php } ?>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-order'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.badge').hover(this.tooltipAction);
                this.$('.update-order').click(this.orderAction);
                this.$('.update-payment').click(this.paymentAction);
                this.$('.update-delivery').click(this.deliveryAction);
                this.$('.update-canPay').click(this.canPayAction);
                this.$('.show-list-user').click(this.listUserAction);
            },
            tooltipAction: function (e) {
                $('[data-toggle="tooltip"]').tooltip();
            },
            orderAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-order')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-order-' + p.attr('data-id')).attr('class', 'update-order btn btn-sm ' + d.orderClass).html(d.orderTitle);
                    };
                });
            },
            paymentAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-payment')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-payment-' + p.attr('data-id')).attr('class', 'update-payment btn btn-sm ' + d.paymentClass).html(d.paymentTitle);
                    };
                });
            },
            deliveryAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-delivery')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-delivery-' + p.attr('data-id')).attr('class', 'update-delivery btn btn-sm ' + d.deliveryClass).html(d.deliveryTitle);
                    };
                });
            },
            canPayAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-canPay')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-canPay-' + p.attr('data-id')).attr('class', 'update-canPay btn btn-sm ' + d.canPayClass).html(d.canPayTitle);
                    };
                });
            },
            listUserAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-listUser')).done(function (res) {
                    self.modal.html(res).modal('show');
                });
            },
        }
        page.init();
    })(jQuery)
</script>
