<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('New order'); ?></h3>
    <div class="alert alert-info">
        <?php _e('You can add manual order for your customer, this order not join to any service or product. and useful for just make payment by customers'); ?>
    </div>
    <?php echo $this->form($form); ?>
</div>

<script>
    $(function () {
        var changeModule = function() {
            $('.specific:first').closest('fieldset').show();
            var moduleName = $('[name=module_name]').val();
            $('.specific').parent().parent().parent().parent().hide();
            $('.specific.' + moduleName).parent().parent().parent().parent().show();

            if ($('.specific:visible').length == 0) {
                $('.specific:first').closest('fieldset').hide();
            } else {
                $('.specific:first').closest('fieldset').show();
            }
        };
        $('[name=module_name]').change(changeModule);
        changeModule();
    });
</script>