<?php
$this->css(
    [
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->backbone();
?>

<div id="js-order" class="order-view clearfix">
    <div class="order-form" data-id="<?php echo $this->escape($order['id']); ?>"
         data-order="<?php echo $this->escape($order['url_update_order']); ?>"
         data-invoice="<?php echo $this->escape($order['url_update_invoice']); ?>"
         data-delivery="<?php echo $this->escape($order['url_update_delivery']); ?>"
         data-canPay="<?php echo $this->escape($order['url_update_canPay']); ?>"
         data-note="<?php echo $this->escape($order['url_update_note']); ?>">

        <div class="page-header mb-3">
            <ul class="list-inline clearfix">
                <li class="list-inline-item float-left">
                    <h1><?php echo sprintf(__('Order %s details'), $order['code']); ?></h1>
                </li>
                <?php if (!$hasValidInvoice) { ?>
                    <?php if ($order['create_by'] == 'ADMIN' && count($order['invoices']) == 0) { ?>
                        <li class="list-inline-item float-right">
                            <a class="btn btn-danger" title="<?php _e('Delete'); ?>"
                               href="<?php echo $this->url(
                                   '', [
                                       'controller' => 'order',
                                       'action'     => 'delete',
                                       'id'         => $order['id'],
                                   ]
                               ); ?>"><i class="fas fa-times"></i> <?php _e('Delete'); ?>
                            </a>
                        </li>
                    <?php } ?>

                    <li class="list-inline-item float-right">
                        <a class="btn btn-success" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url(
                               '', [
                                   'controller' => 'order',
                                   'action'     => 'edit',
                                   'id'         => $order['id'],
                               ]
                           ); ?>"><i class="fas fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>

        <?php if ($offline) { ?>
            <div class="alert alert-danger">
                <ul class="list-inline">
                    <li class="list-inline-item order-main-icon"><i class="fas fa-exclamation-triangle"
                                                                    aria-hidden="true"></i></li>
                    <li class="list-inline-item"><?php _e('This order have offline payment'); ?></li>
                </ul>
            </div>
        <?php } ?>

        <div class="alert alert-info">
            <ul class="list-inline">
                <li class="list-inline-item order-main-icon">
                    <a class="" title="<?php _e('User information'); ?>" href="<?php echo $this->url(
                        'admin', [
                            'module'     => 'user',
                            'controller' => 'edit',
                            'action'     => 'index',
                            'uid'        => $order['uid'],
                        ]
                    ); ?>" target="_blank"><i class="fas fa-user" aria-hidden="true"></i></a></li>

                <li class="list-inline-item"><strong><?php _e('ID'); ?></strong>
                    : <?php echo $this->escape($order['user']['id']); ?></li>


                <?php if ($addressInvoicing['account_type'] == 'company') { ?>
                    <?php if (!empty($addressInvoicing['company'])) { ?>
                        <li class="list-inline-item"><strong><?php _e('Name'); ?></strong> :
                            <span><?php echo $this->escape($addressInvoicing['company']); ?></span>
                        </li>
                        <?php echo $this->escape($order['user']['name']); ?></li>
                    <?php } ?>
                <?php } else { ?>
                    <?php if (!empty($addressInvoicing['first_name']) && !empty($addressInvoicing['last_name'])) { ?>
                        <li class="list-inline-item"><strong><?php _e('Name'); ?></strong> :
                            <span><?php echo $this->escape($addressInvoicing['first_name']) . ' ' . $this->escape($addressInvoicing['last_name']); ?></span>
                        </li>
                    <?php } else { ?>
                        <li class="list-inline-item"><strong><?php _e('Name'); ?></strong>
                            : <?php echo $this->escape($order['user']['name']); ?></li>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['email'])) { ?>
                        <li class="list-inline-item"><strong><?php _e('Email'); ?></strong> :
                            <span><?php echo $this->escape($addressInvoicing['email']); ?></span></li>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['phone'])) { ?>
                        <li class="list-inline-item"><strong><?php _e('Phone'); ?></strong> :
                            <span><?php echo $this->escape($addressInvoicing['phone']); ?></span></li>
                    <?php } ?>
                    <?php if (!empty($addressInvoicing['mobile'])) { ?>
                        <li class="list-inline-item"><strong><?php _e('Mobile'); ?></strong> :
                            <span><?php echo $this->escape($addressInvoicing['mobile']); ?></span></li>
                    <?php } ?>
                <?php } ?>


                <?php if ($order['total_price'] > 0) { ?>
                    <li class="list-inline-item"><strong><?php _e('Total price'); ?></strong> :
                        <span><?php echo $this->escape($order['total_price_view']); ?></span></li>
                <?php } ?>
            </ul>
        </div>
        <?php if (!empty($order['invoices'])) { ?>
            <?php if ($order['paidInstallments'] == $order['totalInstallments']) {
                $adminCanPay = false;
                $classAlert  = 'alert-success';
            } elseif ($order['unPaidInstallments'] == $order['totalInstallments']) {
                $adminCanPay = true;
                $classAlert  = 'alert-danger';
            } else {
                $adminCanPay = false;
                $classAlert  = 'alert-warning';
            } ?>
            <div class="alert <?php echo $classAlert; ?>">
                <ul class="list-inline clearfix">
                    <li class="list-inline-item order-main-icon"><i class="fas fa-calculator" aria-hidden="true"></i>
                    </li>
                    <li class="list-inline-item"><strong><?php _e('Pay installments status'); ?></strong> :</li>
                    <li class="list-inline-item"><?php echo $this->escape($order['statusInstallments']); ?></li>
                    <?php if ($adminCanPay) { ?>
                        <li class="list-inline-item text-right">
                            <a class="btn btn-danger btn-sm"
                               href="<?php echo $this->url('', ['action' => 'pay', 'id' => $order['id']]); ?>"
                               onclick="return confirm('Are you sure you want to make this order as paid?')">
                                <?php _e('Make as paid') ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        <?php } ?>

        <?php if ($config['score_active']) { ?>
            <?php $score = Pi::api('invoice', 'order')->getInvoiceScore($order['uid']); ?>
            <div class="alert alert-info">
                <ul class="list-inline clearfix">
                    <li class="list-inline-item order-main-icon"><i class="far fa-star" aria-hidden="true"></i></li>
                    <li class="list-inline-item"><strong><?php _e('User score'); ?></strong> :</li>
                    <li class="list-inline-item"><?php echo sprintf(__('Type : %s - Amount : %s'), $score['type_view'], $score['amount_view']); ?></li>
                </ul>
            </div>
        <?php } ?>

        <?php if ($config['credit_active']) { ?>
            <div class="alert alert-info">
                <ul class="list-inline clearfix">
                    <li class="list-inline-item order-main-icon"><i class="fas fa-money-bill-alt"
                                                                    aria-hidden="true"></i></li>
                    <li class="list-inline-item"><strong><?php _e('Credit'); ?></strong> :</li>
                    <li class="list-inline-item"><?php echo $this->escape($order['credit']['amount_view']); ?></li>
                    <li class="list-inline-item">( <?php echo $this->escape($order['credit']['time_update_view']); ?>
                        )
                    </li>
                    <li class="list-inline-item float-right">
                        <a class="btn btn-info btn-sm"
                           href="<?php echo $this->url('', ['controller' => 'credit', 'action' => 'update', 'uid' => $order['uid']]); ?>"
                           title="<?php _e('Update credit'); ?>" target="_blank"><i
                                    class="fas fa-plus"></i> <?php _e('Update credit'); ?></a>
                        <a class="btn btn-info btn-sm"
                           href="<?php echo $this->url('', ['controller' => 'credit', 'action' => 'history', 'uid' => $order['uid']]); ?>"
                           title="<?php _e('History'); ?>" target="_blank"><i
                                    class="fas fa-plus"></i> <?php _e('History'); ?></a>
                    </li>
                </ul>
            </div>
        <?php } ?>

        <div id="accordion">

            <!-- accordion -->
            <div class="card">
                <div class="card-header" role="tab" id="headingInformation">
                    <h4 class="card-title">
                        <?php _e('Main information of order'); ?>
                    </h4>
                </div>
                <div id="collapseInformation" class="collapse show" role="tabpanel">
                    <div class="card-body">
                        <div class="clearfix row">
                            <div class="col-lg-4 col-md-4">
                                <p><strong><?php _e('Invoicing address') ?></strong></p>
                                <hr/>

                                <?php if ($addressInvoicing['account_type'] === 'company') { ?>
                                    <p>
                                        <?php if (!empty($addressInvoicing['company'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['company']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressInvoicing['company_address1'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['company_address1']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['company_address2'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['company_address2']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['company_zip_code'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['company_zip_code']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['company_city'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['company_city']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['company_state'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['company_state']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['company_country'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['company_country']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressInvoicing['company_id'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['company_id']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['company_vat'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['company_vat']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressInvoicing['email'])) { ?>
                                            <?php _e('Email'); ?> : <?php echo $this->escape($addressInvoicing['email']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['phone'])) { ?>
                                            <?php _e('Phone'); ?> : <?php echo $this->escape($addressInvoicing['phone']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['mobile'])) { ?>
                                            <?php _e('Mobile'); ?> : <?php echo $this->escape($addressInvoicing['mobile']); ?>
                                            <br/>
                                        <?php } ?>
                                    </p>

                                <?php } else { ?>
                                    <p>
                                        <?php if (!empty($addressInvoicing['first_name']) && !empty($addressInvoicing['last_name'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['first_name']) . ' ' . $this->escape($addressInvoicing['last_name']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['id_number'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['id_number']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressInvoicing['address1'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['address1']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['address2'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['address2']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['zip_code'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['zip_code']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['city'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['city']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['state'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['state']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['country'])) { ?>
                                            <?php echo $this->escape($addressInvoicing['country']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressInvoicing['email'])) { ?>
                                            <?php _e('Email'); ?> : <?php echo $this->escape($addressInvoicing['email']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['phone'])) { ?>
                                            <?php _e('Phone'); ?> : <?php echo $this->escape($addressInvoicing['phone']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressInvoicing['mobile'])) { ?>
                                            <?php _e('Mobile'); ?> : <?php echo $this->escape($addressInvoicing['mobile']); ?>
                                            <br/>
                                        <?php } ?>
                                    </p>
                                <?php } ?>
                                <p>
                                    <?php _e('Type') ?> :
                                    <?php echo $addressInvoicing['account_type'] == 'none' ? __('ND') : __(ucfirst($addressInvoicing['account_type'])); ?>
                                </p>

                            </div>
                            <div class="col-lg-4 col-md-4">
                                <p><strong><?php _e('Delivery address') ?></strong></p>
                                <hr/>
                                <?php if ($addressDelivery['account_type'] === 'company') { ?>
                                    <p>
                                        <?php if (!empty($addressDelivery['company'])) { ?>
                                            <?php echo $this->escape($addressDelivery['company']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressDelivery['company_address1'])) { ?>
                                            <?php echo $this->escape($addressDelivery['company_address1']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['company_address2'])) { ?>
                                            <?php echo $this->escape($addressDelivery['company_address2']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['company_zip_code'])) { ?>
                                            <?php echo $this->escape($addressDelivery['company_zip_code']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['company_city'])) { ?>
                                            <?php echo $this->escape($addressDelivery['company_city']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['company_state'])) { ?>
                                            <?php echo $this->escape($addressDelivery['company_state']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['company_country'])) { ?>
                                            <?php echo $this->escape($addressDelivery['company_country']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressDelivery['company_id'])) { ?>
                                            <?php echo $this->escape($addressDelivery['company_id']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['company_vat'])) { ?>
                                            <?php echo $this->escape($addressDelivery['company_vat']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressDelivery['email'])) { ?>
                                            <?php _e('Email'); ?> : <?php echo $this->escape($addressDelivery['email']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['phone'])) { ?>
                                            <?php _e('Phone'); ?> : <?php echo $this->escape($addressDelivery['phone']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['mobile'])) { ?>
                                            <?php _e('Mobile'); ?> : <?php echo $this->escape($addressDelivery['mobile']); ?>
                                            <br/>
                                        <?php } ?>
                                    </p>
                                <?php } else { ?>
                                    <p>
                                        <?php if (!empty($addressDelivery['first_name']) && !empty($addressDelivery['last_name'])) { ?>
                                            <?php echo $this->escape($addressDelivery['first_name']) . ' ' . $this->escape($addressDelivery['last_name']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['id_number'])) { ?>
                                            <?php echo $this->escape($addressDelivery['id_number']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressDelivery['address1'])) { ?>
                                            <?php echo $this->escape($addressDelivery['address1']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['address2'])) { ?>
                                            <?php echo $this->escape($addressDelivery['address2']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['zip_code'])) { ?>
                                            <?php echo $this->escape($addressDelivery['zip_code']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['city'])) { ?>
                                            <?php echo $this->escape($addressDelivery['city']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['state'])) { ?>
                                            <?php echo $this->escape($addressDelivery['state']); ?><br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['country'])) { ?>
                                            <?php echo $this->escape($addressDelivery['country']); ?><br/>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if (!empty($addressDelivery['email'])) { ?>
                                            <?php _e('Email'); ?> : <?php echo $this->escape($addressDelivery['email']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['phone'])) { ?>
                                            <?php _e('Phone'); ?> : <?php echo $this->escape($addressDelivery['phone']); ?>
                                            <br/>
                                        <?php } ?>
                                        <?php if (!empty($addressDelivery['mobile'])) { ?>
                                            <?php _e('Mobile'); ?> : <?php echo $this->escape($addressDelivery['mobile']); ?>
                                            <br/>
                                        <?php } ?>
                                    </p>
                                <?php } ?>
                                <p>
                                    <?php _e('Type') ?> :
                                    <?php echo $addressDelivery['account_type'] == 'none' ? __('ND') : __(ucfirst($addressDelivery['account_type'])); ?>
                                </p>

                            </div>
                            <div class="col-lg-4 col-md-4">
                                <p><strong><?php _e('Informations') ?></strong></p>
                                <hr/>
                                <p><strong><?php _e('Time create'); ?></strong> :
                                    <span><?php echo $this->escape($order['time_create_view']); ?> </span>
                                </p>
                                <p><strong><?php _e('Time order'); ?></strong> :
                                    <span><?php echo $this->escape($order['time_order_view']); ?> </span>
                                </p>
                                <?php
                                $orderClass = '';
                                switch ($order['status_order']) {
                                    case Module\Order\Model\Order::STATUS_ORDER_PENDING:
                                    case Module\Order\Model\Order::STATUS_ORDER_DRAFT:
                                        $orderClass = 'btn-warning';
                                        break;
                                    case Module\Order\Model\Order::STATUS_ORDER_VALIDATED:
                                        $orderClass = 'btn-success';
                                        break;
                                    case Module\Order\Model\Order::STATUS_ORDER_CANCELLED:
                                        $orderClass = 'btn-danger';
                                        break;
                                }
                                ?>
                                <p><strong><?php _e('Order status'); ?></strong> : <span
                                            id="update-order-<?php echo $this->escape($order['id']); ?>"
                                            class=" <?php echo ($order['status_order'] != \Module\Order\Model\Order::STATUS_ORDER_VALIDATED
                                                || !$hasValidInvoice) ? 'btn update-order' : '' ?> <?php echo $orderClass; ?> btn-sm">
                                            <?php echo Module\Order\Model\Order::getStatusList()[$order['status_order']]; ?>
                                            </span>
                                </p>
                                <p><strong><?php _e('Invoice paid ?'); ?></strong> :


                                    <?php
                                    $countPaid   = 0;
                                    $countUnpaid = 0;

                                    foreach ($order['invoices'] as $invoice) {
                                        foreach ($invoice['installments'] as $installment) {
                                            if ($installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_UNPAID) {
                                                $countUnpaid++;
                                            } else {
                                                $countPaid++;
                                            }
                                        }
                                    }

                                    if ($countPaid == 0) {
                                        $label = __('No');
                                        $badge = "danger";
                                    } else if ($countUnpaid == 0) {
                                        $label = __('Yes');
                                        $badge = "success";
                                    } else {
                                        $label = __('Partially');
                                        $badge = "warning";
                                    }
                                    ?>
                                    <span id="update-canPay-<?php echo $this->escape($order['id']); ?>"
                                          class="update-canPay btn badge badge-<?php echo $badge ?> btn-sm"><?php echo $label ?></span>

                                </p>
                                <p><strong><?php _e('Delivery status'); ?></strong> :
                                    <?php if (count($order['products'])) { ?>
                                        <?php if ($order['type_commodity'] == 'product') { ?>
                                            <span
                                                    id="update-delivery-<?php echo $this->escape($order['id']); ?>"
                                                    class="update-delivery btn <?php echo $this->escape($order['deliveryClass']); ?> btn-sm">

                                            </span>
                                        <?php } else if ($order['type_commodity'] == 'product') { ?>
                                            <span class="badge badge-secondary"><?php _e('Its a booking'); ?></span>
                                        <?php } else { ?>
                                            <span class="badge badge-secondary"><?php _e('Its service'); ?></span>
                                        <?php } ?>
                                    <?php } else { ?>
                                        <?php _e('NA') ?>
                                    <?php } ?>
                                </p>
                                <p><strong><?php _e('Time delivery'); ?></strong> : <span
                                            id="update-delivery-<?php echo $this->escape($order['id']); ?>-time"><?php echo $this->escape(
                                            $order['time_delivery_view']
                                        ); ?></span>
                                </p>
                                <p>
                                    <strong><?php _e('Default gateway'); ?></strong>
                                    : <?php echo $order['default_gateway'] ?>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- accordion -->
            <div class="card mt-3">
                <h4 class="card-title alert alert-success">
                    <?php _e('List of ordered services/products'); ?>
                </h4>
                <div id="collapseProducts" class="collapse show" role="tabpanel">
                    <div class="card-body">
                        <?php if (count($order['products'])) { ?>
                            <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
                                <tr>
                                    <th><?php _e('Product'); ?></th>
                                    <th><?php _e('Time start'); ?></th>
                                    <th><?php _e('Time end'); ?></th>
                                    <th><?php _e('Number'); ?></th>
                                    <th><?php _e('Price ext VAT'); ?></th>
                                    <th><?php _e('Shipping'); ?></th>
                                    <th><?php _e('Packing'); ?></th>
                                    <th><?php _e('Setup'); ?></th>
                                    <th><?php _e('Discount'); ?></th>
                                    <th><?php _e('Vat'); ?></th>
                                    <th><?php _e('Total all taxes included'); ?></th>
                                    <th><?php _e('Extra'); ?></th>
                                    <th></th>
                                </tr>
                                <?php
                                $totalProductPrice  = 0;
                                $totalShippingPrice = 0;
                                $totalPackingPrice  = 0;
                                $totalSetupPrice    = 0;
                                $totalDiscountPrice = 0;
                                $totalVatPrice      = 0;
                                $totalPrice         = 0;

                                foreach ($order['products'] as $product) {
                                    $product['extra']['unconsumedPrice'] = isset($product['extra']['unconsumedPrice']) ? $product['extra']['unconsumedPrice'] : 0;
                                    $totalProductPrice                   += $product['product_price'] - $product['extra']['unconsumedPrice'];
                                    $totalShippingPrice                  += $product['shipping_price'];
                                    $totalPackingPrice                   += $product['packing_price'];
                                    $totalSetupPrice                     += $product['setup_price'];
                                    $totalDiscountPrice                  += $product['discount_price'] + $product['extra']['unconsumedPrice'];
                                    $totalVatPrice                       += $product['vat_price'];
                                    $totalPrice                          += $product['total_price'] - $product['extra']['unconsumedPrice'];
                                    ?>
                                    <tr>
                                        <td>
                                            <div class="productItem">
                                                <?php if (isset($product['details']['productUrl']) && !empty($product['details']['productUrl'])) { ?>
                                                    <a title="<?php echo $this->escape($product['details']['title']); ?>"
                                                       href="<?php echo $this->escape($product['details']['productUrl']); ?>">
                                                        <?php if (isset($product['details']['thumbUrl']) && !empty($product['details']['thumbUrl'])) { ?>
                                                            <img width="32" height="32"
                                                                 src="<?php echo $this->escape($product['details']['thumbUrl']); ?>"
                                                                 alt="<?php echo $this->escape($product['details']['title']); ?>">
                                                        <?php } ?>
                                                        <?php echo $this->escape($product['details']['title']); ?>
                                                    </a>
                                                <?php } else { ?>
                                                    <?php echo $this->escape($product['details']['title']); ?>
                                                <?php } ?>
                                            </div>

                                        </td>
                                        <td><?php echo $product['time_start'] ? _date($product['time_start']) : ''; ?></td>
                                        <td><?php echo $product['time_end'] ? _date($product['time_end']) : ''; ?></td>
                                        <td><?php echo $product['number'] ?></td>
                                        <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['product_price'] - $product['extra']['unconsumedPrice'])); ?></td>
                                        <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['shipping_price'])); ?></td>
                                        <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['packing_price'])); ?></td>
                                        <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['setup_price'])); ?></td>
                                        <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['discount_price'])); ?></td>
                                        <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['vat_price'])); ?></td>
                                        <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['total_price'] - $product['extra']['unconsumedPrice'])); ?></td>
                                        <br/>
                                        <td rowspan=2>
                                            <?php foreach ($product['extra'] as $key => $value) {
                                                echo $key . ' : ' . ($value ? $value : 0) . '<br>';
                                            } ?>
                                        </td>

                                        <td rowspan=2>
                                            <?php if (!$hasValidInvoice) { ?>
                                                <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                                                   href="<?php echo $this->url(
                                                       '', ['controller' => 'order', 'action' => 'product', 'order' => $order['id'], 'id' => $product['id']]
                                                   ); ?>">
                                                    <i class="fas fa-pencil-alt"></i> <?php _e('Edit'); ?></a>
                                                <a class="btn btn-primary btn-sm" title="<?php _e('Delete'); ?>"
                                                   href="<?php echo $this->url(
                                                       '', ['controller' => 'order', 'action' => 'product-delete', 'id' => $product['id']]
                                                   ); ?>">
                                                    <i class="fas fa-times"></i> <?php _e('Delete'); ?></a>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan=11>
                                            <?php echo nl2br($this->escape($product['admin_note'])) ?>
                                        </td>
                                    </tr>
                                <?php } ?>
                                <tr>
                                    <td colspan=4><strong><?php _e('Total') ?></strong></td>
                                    <td>
                                        <strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalProductPrice)); ?></strong>
                                    </td>
                                    <td>
                                        <strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalShippingPrice)); ?></strong>
                                    </td>
                                    <td>
                                        <strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalPackingPrice)); ?></strong>
                                    </td>
                                    <td>
                                        <strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalSetupPrice)); ?></strong>
                                    </td>
                                    <td>
                                        <strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalDiscountPrice)); ?></strong>
                                    </td>
                                    <td>
                                        <strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalVatPrice)); ?></strong>
                                    </td>
                                    <td>
                                        <strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalPrice)); ?></strong>
                                    </td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            </table>
                        <?php } else { ?>
                            <?php _e('No product'); ?>
                        <?php } ?>

                        <hr/>
                        <?php if (!$hasValidInvoice) { ?>
                            <ul class="list-inline clearfix">
                                <li class="list-inline-item float-left"><?php _e('You can add new product / service to this order'); ?></li>
                                <li class="list-inline-item float-right">
                                    <a class="btn btn-success" title="<?php _e('Add product / service'); ?>"
                                       href="<?php echo $this->url(
                                           '', [
                                               'controller' => 'order',
                                               'action'     => 'product',
                                               'order'      => $order['id'],
                                           ]
                                       ); ?>">
                                        <i class="fas fa-plus"></i> <?php _e('Add product / service'); ?>
                                    </a>
                                </li>
                            </ul>
                        <?php } ?>
                    </div>
                </div>
            </div>

            <!-- accordion -->
            <div class="card mt-3">
                <h4 class="card-title alert alert-success">
                    Liste des factures associées à cette commande
                </h4>
                <div id="collapseInvoice" class="collapse show" role="tabpanel">
                    <div class="card-body">
                        <?php if (!empty($order['invoices'])) { ?>

                            <?php foreach ($order['invoices'] as $invoice) { ?>
                                <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
                                    <tr>
                                        <th class="table-col-md-2"><?php echo $invoice['type'] == 'CREDIT'
                                                ? __('Credit Note number')
                                                : __(
                                                    'Invoice ID'
                                                ); ?></th>
                                        <th class="table-col-md-1"><?php _e('Status'); ?></th>
                                        <th class="table-col-md-1"><?php _e('Type'); ?></th>
                                        <th class="table-col-md-1"><?php _e('Type payment'); ?></th>
                                        <th class="table-col-md-2"><?php _e('Time Create'); ?></th>
                                        <th class="table-col-md-2"><?php echo $invoice['type'] == 'CREDIT'
                                                ? __('Credit Note time')
                                                : __(
                                                    'Time invoice'
                                                ); ?></th>
                                        <th class="table-col-md-6 text-right"><?php _e('Action'); ?></th>
                                    </tr>

                                    <?php
                                    $badgeIdClass = '';
                                    if ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_VALIDATED) {
                                        $badgeIdClass = 'badge-success';
                                    } elseif ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_DRAFT) {
                                        $badgeIdClass = 'badge-warning';
                                    } elseif ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_CANCELLED) {
                                        $badgeIdClass = 'badge-danger';
                                    }
                                    ?>


                                    <tr>
                                        <td><?php echo $this->escape($invoice['code']); ?></td>
                                        <td><span id="update-invoice-<?php echo $invoice['id'] ?>"
                                                  data-invoice="<?php echo $invoice['id'] ?>"
                                                  class="badge <?php echo $invoice['type'] != 'CREDIT'
                                                  && $invoice['status'] != \Module\Order\Model\Invoice::STATUS_INVOICE_CANCELLED ? 'update-invoice btn'
                                                      : '' ?>  <?php echo $badgeIdClass; ?>"><?php echo \Module\Order\Model\Invoice::getStatusList()[$invoice['status']]; ?></span>
                                        </td>
                                        <td><?php echo $this->escape($invoice['type']); ?></td>
                                        <td><?php echo $this->escape($invoice['type_payment']); ?></td>
                                        <td><?php echo $this->escape($invoice['time_create_view']) . ' ' . date('H:i', $invoice['time_create']); ?></td>
                                        <td><?php echo $this->escape($invoice['time_invoice_view']) ?></td>
                                        <td class="text-right">
                                            <a class="btn btn-primary btn-sm" title="<?php _e('View'); ?>"
                                               href="<?php echo $this->url('', ['controller' => 'invoice', 'action' => 'view', 'id' => $invoice['id']]); ?>">
                                                <i class="far fa-eye"></i> <?php _e('View'); ?></a>
                                            <a class="btn btn-primary btn-sm" target="_blank"
                                               title="<?php _e('Print'); ?>"
                                               href="<?php echo $this->url(
                                                   '', ['controller' => 'invoice', 'action' => 'print-pdf', 'id' => $invoice['id']]
                                               ); ?>">
                                                <i class="fas fa-print"></i> <?php _e('Print'); ?></a>
                                            <?php if ($invoice['status'] == \Module\Order\Model\Invoice::STATUS_INVOICE_DRAFT) { ?>
                                                <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                                                   href="<?php echo $this->url(
                                                       '', ['controller' => 'invoice', 'action' => 'edit', 'id' => $invoice['id']]
                                                   ); ?>">
                                                    <i class="fas fa-pencil-alt"></i> <?php _e('Edit'); ?></a>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                </table>

                                <?php foreach ($invoice['installments'] as $installment) { ?>
                                    <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3 table-installment">
                                        <tr>
                                            <th class="table-col-md-2 transparent"></th>
                                            <th class="table-col-md-1"><?php _e('Installment'); ?></th>
                                            <th class="table-col-md-1"><?php _e('Price'); ?></th>
                                            <th class="table-col-md-1"><?php _e('Credit price'); ?></th>
                                            <th class="table-col-md-1"><?php _e('Due date'); ?></th>
                                            <th class="table-col-md-2"><?php _e('Time pay'); ?></th>
                                            <th class="table-col-md-2"><?php _e('Gateway'); ?></th>
                                            <th class="table-col-md-1"><?php _e('Status'); ?></th>
                                            <th class="table-col-md-2 text-right"><?php _e('Action'); ?></th>
                                        </tr>
                                        <?php
                                        $rowClass = '';
                                        if ($installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_UNPAID) {
                                            $badgeIdClass = 'badge-warning';
                                        } elseif ($installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID) {
                                            $badgeIdClass = 'badge-success';
                                        }
                                        ?>
                                        <tr>
                                            <td class="transparent"></td>
                                            <td><?php echo $installment['count'] . ' / ' . count($invoice['installments']) ?></td>
                                            <td><?php echo $this->escape($installment['due_price_view']); ?></td>
                                            <td><?php echo $this->escape($installment['credit_price_view']); ?></td>
                                            <td><?php echo $this->escape($installment['time_duedate_view']); ?></td>
                                            <td><?php echo $this->escape($installment['time_payment_view']); ?></td>
                                            <td><?php echo isset($gateways[$installment['gateway']]) ? $gateways[$installment['gateway']] : ''; ?></td>
                                            <td><span class="badge <?php echo $badgeIdClass; ?>"><?php echo $installment['status_payment']
                                                    == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID ? __('Paid') : __('Unpaid') ?></span>
                                            </td>
                                            <td class="text-right">
                                                <?php
                                                $type = '';
                                                if (isset($gatewaysInfo[$installment['gateway']])) {
                                                    $type = $gatewaysInfo[$installment['gateway']]['type'];
                                                }
                                                $readonly = $installment['status_payment'] == \Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID
                                                    && $type == 'online';
                                                if ($invoice['status'] != \Module\Order\Model\Invoice::STATUS_INVOICE_CANCELLED) { ?>
                                                    <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                                                       href="<?php echo $this->url(
                                                           '', ['controller' => 'installment', 'action' => 'edit', 'id' => $installment['id']]
                                                       ); ?>">
                                                        <i class="fas fa-pencil-alt"></i> <?php _e('Edit'); ?></a>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                    </table>
                                <?php } ?>
                            <?php } ?>
                            <hr/>
                            <?php if ($order['status_order'] == \Module\Order\Model\Order::STATUS_ORDER_VALIDATED && !$hasValidInvoice
                                && !$hasDraftInvoice
                            ) { ?>
                                <ul class="list-inline clearfix">
                                    <li class="list-inline-item float-right">
                                        <a class="btn btn-success float-right"
                                           href="<?php echo $this->url('', ['controller' => 'invoice', 'action' => 'add', 'order' => $order['id']]); ?>"
                                           title="<?php _e('New invoice'); ?>"><i
                                                    class="fas fa-plus"></i> <?php _e('New invoice'); ?></a>
                                    </li>
                                </ul>
                            <?php } ?>
                        <?php } else { ?>
                            <?php if ($order['status_order'] == \Module\Order\Model\Order::STATUS_ORDER_VALIDATED && !$hasValidInvoice
                                && !$hasDraftInvoice
                            ) { ?>
                                <div class="">
                                    <p><a class="btn btn-success float-right"
                                          href="<?php echo $this->url('', ['controller' => 'invoice', 'action' => 'add', 'order' => $order['id']]); ?>"
                                          title="<?php _e('New invoice'); ?>"><i
                                                    class="fas fa-plus"></i> <?php _e('New invoice'); ?></a></p>
                                </div>
                            <?php } else { ?>
                                <p><?php _e('Order is not validated, you cannot add an invoice.') ?></p>
                            <?php } ?>
                        <?php } ?>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            <!-- accordion -->
            <div class="card mt-3 <?php if (!empty($order['user_note'])) { ?>panel-info<?php } else { ?>card-primary<?php } ?>">
                <h4 class="card-title alert alert-info">
                    <?php _e('Note'); ?>
                </h4>
                <div>
                    <div class="card-body">
                        <?php if (!empty($order['user_note'])) { ?>
                            <div class="clearfix">
                                <h4><?php _e('User note'); ?></h4>
                                <div class="clearfix">
                                    <?php echo $order['user_note']; ?>
                                </div>
                                <hr/>
                            </div>
                        <?php } ?>
                        <div class="clearfix">
                            <h4><?php _e('Admin note'); ?></h4>
                            <div id="update-note-<?php echo $this->escape($order['id']); ?>" class="clearfix">
                                <?php echo $order['admin_note']; ?>
                            </div>
                            <hr/>
                            <ul class="list-inline clearfix">
                                <li class="list-inline-item float-left"><?php _e('You can set any note for user'); ?></li>
                                <li class="list-inline-item float-right">
                                    <a class="float-right update-note btn btn-success">
                                        <i class="fas fa-plus"></i> <?php _e('Add / edit admin note'); ?>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-order'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.update-order').click(this.orderAction);
                this.$('.update-delivery').click(this.deliveryAction);
                this.$('.update-canPay').click(this.canPayAction);
                this.$('.update-note').click(this.noteAction);
                this.$('.update-invoice').click(this.invoiceAction);
            },
            orderAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-order')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-order-' + p.attr('data-id')).attr('class', 'update-order btn ' + d.orderClass).html(d.orderTitle);
                        window.location.reload();
                    };
                });
            },
            invoiceAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-invoice'), {'id': $(e.target).data('invoice')}).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-invoice-' + $(e.target).data('invoice')).attr('class', 'update-invoice btn ' + d.invoiceClass);
                        window.location.reload();
                    };
                });
            },
            deliveryAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-delivery')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-delivery-' + p.attr('data-id')).attr('class', 'update-delivery btn ' + d.deliveryClass).html(d.deliveryTitle);
                        $('#update-delivery-' + p.attr('data-id') + '-time').html(d.time_delivery_view);
                    };
                });
            },
            canPayAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-canPay')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-canPay-' + p.attr('data-id')).attr('class', 'update-canPay btn ' + d.canPayClass).html(d.canPayTitle);
                    };
                });
            },
            noteAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-note')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-note-' + p.attr('data-id')).attr('class', 'clearfix').html(d.admin_note);
                    };
                });
            },
        }
        page.init();
    })(jQuery)
</script>
