<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->backbone();
?>

<div id="js-order" class="order-view clearfix">
    <div class="order-form" data-id="<?php echo $this->escape($order['id']); ?>"
         data-order="<?php echo $this->escape($order['url_update_order']); ?>"
         data-invoice="<?php echo $this->escape($order['url_update_invoice']); ?>"
         data-delivery="<?php echo $this->escape($order['url_update_delivery']); ?>"
         data-canPay="<?php echo $this->escape($order['url_update_canPay']); ?>"
         data-note="<?php echo $this->escape($order['url_update_note']); ?>">

        <div class="page-header">
            <ul class="list-inline clearfix">
                <li class="pull-left">
                    <h1><?php echo sprintf(__('Order %s details'), $order['code']); ?></h1>
                </li>
                <?php if (!$hasValidInvoice) { ?>
                    <?php if ($order['create_by'] == 'ADMIN' && count($order['invoices']) == 0) { ?>
                        <li class="pull-right">
                            <a class="btn btn-danger" title="<?php _e('Delete'); ?>"
                               href="<?php echo $this->url('', array(
                                   'controller' => 'order',
                                   'action' => 'delete',
                                   'id' => $order['id']
                               )); ?>"><i class="fa fa-close"></i> <?php _e('Delete'); ?>
                            </a>
                        </li>
                    <?php } ?> 
                    
                    <li class="pull-right">
                        <a class="btn btn-success" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', array(
                               'controller' => 'order',
                               'action' => 'edit',
                               'id' => $order['id']
                           )); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    
        <?php if ($offline) { ?>
            <div class="alert alert-danger">
                <ul class="list-inline">
                    <li class="order-main-icon"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></li>
                    <li><?php _e('This order have offline payment'); ?></li>
                </ul>
            </div>
        <?php } ?>

        <div class="alert alert-info">
            <ul class="list-inline">
                <li class="order-main-icon">
                    <a class="" title="<?php _e('User information'); ?>" href="<?php echo $this->url('admin', array(
                        'module' => 'user',
                        'controller' => 'edit',
                        'action' => 'index',
                        'uid' => $order['uid'],
                    )); ?>" target="_blank"><i class="fa fa-user" aria-hidden="true"></i></a></li>

                <li class=""><strong><?php _e('ID'); ?></strong>
                    : <?php echo $this->escape($order['user']['id']); ?></li>
                           
                <?php if (!empty($addressInvoicing['first_name']) && !empty($addressInvoicing['last_name'])) { ?>
                    <li><strong><?php _e('Name'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['first_name']); ?> <?php echo $this->escape($addressInvoicing['last_name']); ?></span>
                    </li>
                <?php } else {?>
                    <li class=""><strong><?php _e('Name'); ?></strong>
                                : <?php echo $this->escape($order['user']['name']); ?></li>
                <?php } ?>
                <?php if (!empty($addressInvoicing['email'])) { ?>
                    <li><strong><?php _e('Email'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['email']); ?></span></li>
                <?php } ?>
                <?php if (!empty($addressInvoicing['phone'])) { ?>
                    <li><strong><?php _e('Phone'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['phone']); ?></span></li>
                <?php } ?>
                <?php if (!empty($addressInvoicing['mobile'])) { ?>
                    <li><strong><?php _e('Mobile'); ?></strong> :
                        <span><?php echo $this->escape($addressInvoicing['mobile']); ?></span></li>
                <?php } ?>
                <?php if ($order['total_price'] > 0) { ?>
                    <li><strong><?php _e('Total price'); ?></strong> :
                        <span><?php echo $this->escape($order['total_price_view']); ?></span></li>
                <?php } ?>
            </ul>
        </div>
        <?php if (!empty($order['invoices'])) { ?>
            <?php if ($order['paidInstallments'] == $order['totalInstallments']) {
                $classAlert = 'alert-success';
            } elseif ($order['unPaidInstallments'] == $order['totalInstallments']) {
                $classAlert = 'alert-danger';
            } else {
                $classAlert = 'alert-warning';
            } ?>
            <div class="alert <?php echo $classAlert; ?>">
                <ul class="list-inline clearfix">
                    <li class="order-main-icon"><i class="fa fa-calculator" aria-hidden="true"></i></li>
                    <li><strong><?php _e('Pay installments status'); ?></strong> :</li>
                    <li><?php echo $this->escape($order['statusInstallments']); ?></li>
                </ul>
            </div>
        <?php } ?>

        <?php if ($config['score_active']) { ?>
            <?php $score = Pi::api('invoice', 'order')->getInvoiceScore($order['uid']); ?>
            <div class="alert alert-info">
                <ul class="list-inline clearfix">
                    <li class="order-main-icon"><i class="fa fa-star-o" aria-hidden="true"></i></li>
                    <li><strong><?php _e('User score'); ?></strong> :</li>
                    <li><?php echo sprintf(__('Type : %s - Amount : %s'), $score['type_view'], $score['amount_view']); ?></li>
                </ul>
            </div>
        <?php } ?>

        <?php if ($config['credit_active']) { ?>
            <div class="alert alert-info">
                <ul class="list-inline clearfix">
                    <li class="order-main-icon"><i class="fa fa-money" aria-hidden="true"></i></li>
                    <li><strong><?php _e('Credit'); ?></strong> :</li>
                    <li><?php echo $this->escape($order['credit']['amount_view']); ?></li>
                    <li>( <?php echo $this->escape($order['credit']['time_update_view']); ?> )</li>
                    <li class="pull-right">
                        <a class="btn btn-info btn-xs"
                           href="<?php echo $this->url('', array('controller' => 'credit', 'action' => 'update', 'uid' => $order['uid'])); ?>"
                           title="<?php _e('Update credit'); ?>" target="_blank"><i
                                    class="fa fa-plus"></i> <?php _e('Update credit'); ?></a>
                        <a class="btn btn-info btn-xs"
                           href="<?php echo $this->url('', array('controller' => 'credit', 'action' => 'history', 'uid' => $order['uid'])); ?>"
                           title="<?php _e('History'); ?>" target="_blank"><i
                                    class="fa fa-plus"></i> <?php _e('History'); ?></a>
                    </li>
                </ul>
            </div>
        <?php } ?>

        <div class="panel-group" id="accordion">

            <!-- accordion -->
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingInformation">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" href="#collapseInformation" aria-expanded="false" aria-controls="collapseInformation">
                            <i class="fa fa-plus"></i> <?php _e('Main information of order'); ?>
                        </a>
                    </h4>
                </div>
                <div id="collapseInformation" class="panel-collapse collapse in" role="tabpanel">
                    <div class="panel-body">
                        <div class="clearfix">
                            <div class="col-md-4">
                                <p><strong><?php _e('Invoicing address') ?></strong></p>
                                <hr/>
                                <p>
                                    <?php if (!empty($addressInvoicing['first_name']) && !empty($addressInvoicing['last_name'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['first_name']); ?> <?php echo $this->escape($addressInvoicing['last_name']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['id_number'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['id_number']); ?><br/>
                                    <?php } ?>
                                </p>
                                <p>
                                    <?php if (!empty($addressInvoicing['address1'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['address1']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['address2'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['address2']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['city'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['city']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['state'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['state']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['country'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['country']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['zip_code'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['zip_code']); ?><br/>
                                    <?php } ?>
                                </p>
                                <p>
                                    <?php if (!empty($addressInvoicing['email'])) { ?>
                                        <?php _e('Email'); ?> : <?php echo $this->escape($addressInvoicing['email']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['phone'])) { ?>
                                        <?php _e('Phone'); ?> : <?php echo $this->escape($addressInvoicing['phone']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['mobile'])) { ?>
                                        <?php _e('Mobile'); ?> : <?php echo $this->escape($addressInvoicing['mobile']); ?><br/>
                                    <?php } ?>
                                </p>
                                <p>
                                    <?php if (!empty($addressInvoicing['company'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['company']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['company_id'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['company_id']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressInvoicing['company_vat'])) { ?>
                                        <?php echo $this->escape($addressInvoicing['company_vat']); ?><br/>
                                    <?php } ?>
                                </p>
                            </div>
                            <div class="col-md-4">
                                <p><strong><?php _e('Delivery address') ?></strong></p>
                                <hr/>
                                <p>
                                    <?php if (!empty($addressDelivery['first_name']) && !empty($addressDelivery['last_name'])) { ?>
                                        <?php echo $this->escape($addressDelivery['first_name']); ?> <?php echo $this->escape($addressDelivery['last_name']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['id_number'])) { ?>
                                        <?php echo $this->escape($addressDelivery['id_number']); ?><br/>
                                    <?php } ?>
                                </p>
                                <p>
                                    <?php if (!empty($addressDelivery['address1'])) { ?>
                                        <?php echo $this->escape($addressDelivery['address1']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['address2'])) { ?>
                                        <?php echo $this->escape($addressDelivery['address2']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['city'])) { ?>
                                        <?php echo $this->escape($addressDelivery['city']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['state'])) { ?>
                                        <?php echo $this->escape($addressDelivery['state']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['country'])) { ?>
                                        <?php echo $this->escape($addressDelivery['country']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['zip_code'])) { ?>
                                        <?php echo $this->escape($addressDelivery['zip_code']); ?><br/>
                                    <?php } ?>
                                </p>
                                <p>
                                    <?php if (!empty($addressDelivery['email'])) { ?>
                                        <?php _e('Email'); ?> : <?php echo $this->escape($addressDelivery['email']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['phone'])) { ?>
                                        <?php _e('Phone'); ?> : <?php echo $this->escape($addressDelivery['phone']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['mobile'])) { ?>
                                        <?php _e('Mobile'); ?> : <?php echo $this->escape($addressDelivery['mobile']); ?><br/>
                                    <?php } ?>
                                </p>
                                <p>
                                    <?php if (!empty($addressDelivery['company'])) { ?>
                                        <?php echo $this->escape($addressDelivery['company']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['company_id'])) { ?>
                                        <?php echo $this->escape($addressDelivery['company_id']); ?><br/>
                                    <?php } ?>
                                    <?php if (!empty($addressDelivery['company_vat'])) { ?>
                                        <?php echo $this->escape($addressDelivery['company_vat']); ?><br/>
                                    <?php } ?>
                                </p>
                            </div>
                            <div class="col-md-4">
                                <p><strong><?php _e('Informations') ?></strong></p>
                                <hr/>
                                <p><strong><?php _e('Time create'); ?></strong> :
                                    <span><?php echo $this->escape($order['time_create_view']); ?> </span></p>

                               <?php 
                                $orderClass = '';
                                switch ($order['status_order']) {
                                    case Module\Order\Model\Order::STATUS_ORDER_DRAFT:
                                        $orderClass = 'btn-warning';
                                        break;
                                    case Module\Order\Model\Order::STATUS_ORDER_VALIDATED:
                                        $orderClass = 'btn-success';
                                        break;
                                    case Module\Order\Model\Order::STATUS_ORDER_CANCELLED:
                                        $orderClass = 'btn-danger';
                                        break;
                                }
                                ?>
                                 <p><strong><?php _e('Order status'); ?></strong> : <span
                                            id="update-order-<?php echo $this->escape($order['id']); ?>"
                                            class=" <?php echo ($order['status_order'] != \Module\Order\Model\Order::STATUS_ORDER_VALIDATED || !$hasValidInvoice) ? 'btn update-order' : ''?> <?php echo $orderClass; ?> btn-xs">
                                            <?php echo Module\Order\Model\Order::getStatusList()[$order['status_order']]; ?>
                                            </span>
                                </p>
                                 <p><strong><?php _e('Can pay?'); ?></strong> : <span
                                            id="update-canPay-<?php echo $this->escape($order['id']); ?>"
                                            class="update-canPay btn <?php echo $this->escape($order['canPayClass']); ?> btn-xs"><?php echo $this->escape($order['canPayTitle']); ?></span>
                                </p>
                                <p><strong><?php _e('Delivery status'); ?></strong> : <span
                                        id="update-delivery-<?php echo $this->escape($order['id']); ?>"
                                        class="update-delivery btn <?php echo $this->escape($order['deliveryClass']); ?> btn-xs"><?php echo $this->escape($order['deliveryTitle']); ?></span>
                                </p>
                                <p"><strong><?php _e('Time delivery'); ?></strong> : <span
                                            id="update-delivery-<?php echo $this->escape($order['id']); ?>-time"><?php echo $this->escape($order['time_delivery_view']); ?></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- accordion -->
            <div class="panel panel-success">
                <div class="panel-heading" role="tab" id="headingProducts">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" href="#collapseProducts" aria-expanded="false" aria-controls="collapseProducts">
                            <i class="fa fa-plus"></i> <?php _e('List of ordered services/products'); ?>
                        </a>
                    </h4>
                </div>
                <div id="collapseProducts" class="panel-collapse collapse in" role="tabpanel">
                    <div class="panel-body">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr>
                                <th><?php _e('Product'); ?></th>
                                <th><?php _e('Time start'); ?></th>
                                <th><?php _e('Time end'); ?></th>
                                <th><?php _e('Number'); ?></th>
                                <th><?php _e('Price'); ?></th>
                                <th><?php _e('Shipping'); ?></th>
                                <th><?php _e('Packing'); ?></th>
                                <th><?php _e('Setup'); ?></th>
                                <th><?php _e('Discount'); ?></th>
                                <th><?php _e('Vat'); ?></th>
                                <th><?php _e('Total'); ?></th>
                            </tr>
                            <?php 
                                $totalProductPrice = 0;
                                $totalShippingPrice = 0;
                                $totalPackingPrice = 0;
                                $totalSetupPrice = 0;
                                $totalDiscountPrice = 0;
                                $totalVatPrice = 0;
                                $totalPrice = 0;
                            
                            foreach ($order['products'] as $product) {
                                
                                $totalProductPrice += $product['product_price'];
                                $totalShippingPrice += $product['shipping_price'];
                                $totalPackingPrice += $product['packing_price'];
                                $totalSetupPrice += $product['setup_price'];
                                $totalDiscountPrice += $product['discount_price'];
                                $totalVatPrice += $product['vat_price'];
                                $totalPrice += $product['total_price'];
                            ?>
                                <tr>
                                    <td>
                                        <div class="productItem">
                                            <?php if (isset($product['details']['productUrl']) && !empty($product['details']['productUrl'])) { ?>
                                                <a title="<?php echo $this->escape($product['details']['title']); ?>"
                                                   href="<?php echo $this->escape($product['details']['productUrl']); ?>">
                                                    <?php if (isset($product['details']['thumbUrl']) && !empty($product['details']['thumbUrl'])) { ?>
                                                        <img width="32" height="32"
                                                             src="<?php echo $this->escape($product['details']['thumbUrl']); ?>"
                                                             alt="<?php echo $this->escape($product['details']['title']); ?>">
                                                    <?php } ?>
                                                    <?php echo $this->escape($product['details']['title']); ?>
                                                </a>
                                            <?php } else { ?>
                                                <?php echo $this->escape($product['details']['title']); ?>
                                            <?php } ?>
                                        </div>
                                        
                                    </td>
                                    <td><?php echo $product['time_start'] ? _date($product['time_start']) : ''; ?></td>
                                    <td><?php echo $product['time_end'] ? _date($product['time_end']) : ''; ?></td>
                                    <td><?php echo $product['number'] ?></td>
                                    <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['product_price'])); ?></td>
                                    <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['shipping_price'])); ?></td>
                                    <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['packing_price'])); ?></td>
                                    <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['setup_price'])); ?></td>
                                    <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['discount_price'])); ?></td>
                                    <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['vat_price'])); ?></td>
                                    <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['total_price'])); ?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td colspan=4><strong><?php _e ('Total') ?></strong></td>
                                <td><strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalProductPrice)); ?></strong></td>
                                <td><strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalShippingPrice)); ?></strong></td>
                                <td><strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalPackingPrice)); ?></strong></td>
                                <td><strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalSetupPrice)); ?></strong></td>
                                <td><strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalDiscountPrice)); ?></strong></td>
                                <td><strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalVatPrice)); ?></strong></td>
                                <td><strong><?php echo Pi::api('api', 'order')->viewPrice($this->escape($totalPrice)); ?></strong></td>
                            </tr>
                        </table>
                        <hr />
                        <?php if (!$hasValidInvoice) { ?> 
                            <ul class="list-inline clearfix">
                                <li class="pull-left"><?php _e('You can add new product / service to this order'); ?></li>
                                <li class="pull-right">
                                    <a class="btn btn-success" title="<?php _e('Add product / service'); ?>" href="<?php echo $this->url('', array(
                                        'controller' => 'order',
                                        'action' => 'product',
                                        'order' => $order['id']
                                    )); ?>">
                                        <i class="fa fa-plus"></i> <?php _e('Add product / service'); ?>
                                    </a>
                                </li>
                            </ul>
                        <?php } ?>
                    </div>
                </div>
            </div>

            <!-- accordion -->
            <div class="panel panel-success">
                <div class="panel-heading" role="tab" id="headingInvoice">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" href="#collapseInvoice" aria-expanded="false" aria-controls="collapseInvoice">
                            <i class="fa fa-plus"></i> <?php _e('This order invoices list'); ?>
                        </a>
                    </h4>
                </div>
                <div id="collapseInvoice" class="panel-collapse collapse in" role="tabpanel">
                    <div class="panel-body">
                        <?php if (!empty($order['invoices'])) { ?>
                            
                                <?php foreach ($order['invoices'] as $invoice) { ?>
                                    <table class="table table-striped table-bordered table-condensed">
                                        <tr>
                                            <th class="col-md-1"><?php _e('Invoice ID'); ?></th>
                                            <th class="col-md-1"><?php _e('Bank ID'); ?></th>
                                            <th class="col-md-1"><?php _e('Type'); ?></th>
                                            <th class="col-md-2"><?php _e('Time Create'); ?></th>
                                            <th class="col-md-7 text-right"><?php _e('Action'); ?></th>
                                        </tr>
                                        
                                    <?php
                                    $labelIdClass = '';
                                    if ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_VALIDATED) {
                                        $labelIdClass = 'label-success';
                                    } elseif ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_DRAFT) {
                                        $labelIdClass = 'label-warning';
                                    } elseif ($invoice['status'] == Module\Order\Model\Invoice::STATUS_INVOICE_CANCELLED) {
                                        $labelIdClass = 'label-danger';
                                    }
                                    ?>
                                    
                                    
                                    <tr>
                                        <td><span id="update-invoice-<?php echo $invoice['id'] ?>" data-invoice="<?php echo $invoice['id'] ?>" class="label <?php echo $invoice['type'] != 'CREDIT' && $invoice['status'] != \Module\Order\Model\Invoice::STATUS_INVOICE_CANCELLED ? 'update-invoice btn' : '' ?>  <?php echo $labelIdClass; ?>"><?php echo $this->escape($invoice['code']); ?></span></td>
                                        <td><?php echo $this->escape($invoice['random_id']); ?></td>
                                        <td><?php echo $this->escape($invoice['type']); ?></td>
                                        <td><?php echo $this->escape($invoice['time_create_view']) . ' ' . date('H:m', $invoice['time_create']); ?></td>
                                        <td class="text-right">
                                            <a class="btn btn-primary btn-xs" title="<?php _e('View'); ?>"
                                               href="<?php echo $this->url('', array('controller' => 'invoice', 'action' => 'view', 'id' => $invoice['id'])); ?>">
                                                <i class="fa fa-eye"></i> <?php _e('View'); ?></a>
                                            <a class="btn btn-primary btn-xs" title="<?php _e('Print'); ?>"
                                               href="<?php echo $this->url('', array('controller' => 'invoice', 'action' => 'print-pdf', 'id' => $invoice['id'])); ?>">
                                                <i class="fa fa-print"></i> <?php _e('Print'); ?></a>
                                                <?php if ($invoice['status'] == \Module\Order\Model\Invoice::STATUS_INVOICE_DRAFT) { ?> 
                                            <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                                               href="<?php echo $this->url('', array('controller' => 'invoice', 'action' => 'edit', 'id' => $invoice['id'])); ?>">
                                                <i class="fa fa-pencil"></i> <?php _e('Edit'); ?></a>
                                                <?php } ?> 
                                        </td>
                                    </tr>
                                </table>
                            
                                <?php foreach ($invoice['installments'] as $installment) { ?>
                                    <table class="table table-striped table-installment table-bordered table-condensed">
                                        <tr>
                                            <th class="col-md-1 transparent"></th>
                                            <th class="col-md-1"><?php _e('Installment'); ?></th>
                                            <th class="col-md-1"><?php _e('Price'); ?></th>
                                            <th class="col-md-1"><?php _e('Credit price'); ?></th>
                                            <th class="col-md-2"><?php _e('Due date'); ?></th>
                                            <th class="col-md-2"><?php _e('Time pay'); ?></th>
                                            <th class="col-md-2"><?php _e('Gateway'); ?></th>
                                            <th class="col-md-3 text-right"><?php _e('Action'); ?></th>
                                        </tr>
                                        <?php
                                        $rowClass = '';
                                        if ($installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_UNPAID) {
                                            $labelIdClass = 'label-warning';
                                            $rowClass = ' class="warning"';
                                            if ($installment['time_duedate'] < strtotime("-1 day")) {
                                                $rowClass = ' class="danger"';
                                            }
                                        } elseif ($installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID) {
                                            $labelIdClass = 'label-success';
                                            $rowClass = ' class="success"';                                        
                                        } 
                                        ?>
                                        <tr<?php echo $rowClass; ?>>
                                            <td class="transparent"></td>
                                            <td><?php echo $installment['count'] . ' / ' . count($invoice['installments']) ?></td>
                                            <td><?php echo $this->escape($installment['due_price_view']); ?></td>
                                            <td><?php echo $this->escape($installment['credit_price_view']); ?></td>
                                            <td><?php echo $this->escape($installment['time_duedate_view']); ?></td>
                                            <td><?php echo $this->escape($installment['time_payment_view']); ?></td>
                                            <td><?php echo isset($gateways[$installment['gateway']]) ? $gateways[$installment['gateway']] : ''; ?></td >
                                            <td class="text-right">
                                                <?php 
                                                $type = '';
                                                if (isset($gatewaysInfo[$installment['gateway']])) {
                                                    $type = $gatewaysInfo[$installment['gateway']]['type'];
                                                }
                                                $readonly = $installment['status_payment'] == \Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID && $type == 'online';
                                                if ($invoice['status'] != \Module\Order\Model\Invoice::STATUS_INVOICE_CANCELLED && !$readonly) { ?> 
                                                    <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                                                       href="<?php echo $this->url('', array('controller' => 'installment', 'action' => 'edit', 'id' => $installment['id'])); ?>">
                                                        <i class="fa fa-pencil"></i> <?php _e('Edit'); ?></a>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                    </table>
                                <?php } ?>
                             <?php } ?>
                            <ul class="list-inline clearfix">
                                <li class="label label-success"><?php _e('Paid'); ?></li>
                                <li class="label label-warning"><?php _e('Unpaid'); ?></li>
                                <li class="label label-danger"><?php _e('Canceled'); ?></li>
                            </ul>
                            <hr />
                            <?php if ($order['status_order'] == \Module\Order\Model\Order::STATUS_ORDER_VALIDATED && !$hasValidInvoice && !$hasDraftInvoice) { ?>
                                <ul class="list-inline clearfix">
                                    <li class="pull-left"><?php _e('Add extra invoice to this order'); ?></li>
                                    <li class="pull-right">
                                        <a class="btn btn-success"
                                           href="<?php echo $this->url('', array('controller' => 'invoice', 'action' => 'add', 'order' => $order['id'])); ?>"
                                           title="<?php _e('New invoice'); ?>"><i
                                                    class="fa fa-plus"></i> <?php _e('New invoice'); ?></a>
                                    </li>
                                </ul>
                            <?php } ?>
                        <?php } else { ?>
                            <?php if ($order['status_order'] == \Module\Order\Model\Order::STATUS_ORDER_VALIDATED && !$hasValidInvoice && !$hasDraftInvoice) { ?>
                                <div class="well">
                                    <h4><?php _e('Add extra invoice to this order'); ?></h4>
                                    <p><?php _e('If you want your user pay new price for this order, you can add new invoice for him by new price, use below button to add new invoice'); ?></p>
                                    <p><a class="btn btn-success"
                                          href="<?php echo $this->url('', array('controller' => 'invoice', 'action' => 'add', 'order' => $order['id'])); ?>"
                                          title="<?php _e('New invoice'); ?>"><i class="fa fa-plus"></i> <?php _e('New invoice'); ?></a></p>
                                </div>
                            <?php } ?>
                        <?php } ?>

                    </div>
                </div>
            </div>

            <!-- accordion -->
            <div class="panel <?php if (!empty($order['user_note'])) { ?>panel-info<?php } else { ?>panel-default<?php } ?>">
                <div class="panel-heading" role="tab" id="headingNote">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" href="#collapseNote" aria-expanded="false" aria-controls="collapseNote">
                            <i class="fa fa-plus"></i> <?php _e('Note'); ?>
                        </a>
                    </h4>
                </div>
                <div id="collapseNote" class="panel-collapse collapse <?php if (!empty($order['user_note'])) { ?>in<?php } ?>" role="tabpanel">
                    <div class="panel-body">
                        <?php if (!empty($order['user_note'])) { ?>
                            <div class="clearfix">
                                <h4><?php _e('User note'); ?></h4>
                                <div class="clearfix">
                                    <?php echo $order['user_note']; ?>
                                </div>
                                <hr />
                            </div>
                        <?php } ?>
                        <div class="clearfix">
                            <h4><?php _e('Admin note'); ?></h4>
                            <div id="update-note-<?php echo $this->escape($order['id']); ?>" class="clearfix">
                                <?php echo $order['admin_note']; ?>
                            </div>
                            <hr />
                            <ul class="list-inline clearfix">
                                <li class="pull-left"><?php _e('You can set any note for user'); ?></li>
                                <li class="pull-right">
                                    <a class="pull-right update-note btn btn-success">
                                        <i class="fa fa-plus"></i> <?php _e('Add / edit admin note'); ?>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-order'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.update-order').click(this.orderAction);
                this.$('.update-delivery').click(this.deliveryAction);
                this.$('.update-canPay').click(this.canPayAction);
                this.$('.update-note').click(this.noteAction);
                this.$('.update-invoice').click(this.invoiceAction);
            },
            orderAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-order')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-order-' + p.attr('data-id')).attr('class', 'update-order btn ' + d.orderClass).html(d.orderTitle);
                        window.location.reload();
                    };
                });
            },
            invoiceAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-invoice'), {'id' : $(e.target).data('invoice')}).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-invoice-' + $(e.target).data('invoice')).attr('class', 'update-invoice btn ' + d.invoiceClass);
                        window.location.reload();
                    };
                });
            },
            deliveryAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-delivery')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-delivery-' + p.attr('data-id')).attr('class', 'update-delivery btn ' + d.deliveryClass).html(d.deliveryTitle);
                        $('#update-delivery-' + p.attr('data-id') + '-time').html(d.time_delivery_view);
                    };
                });
            },
            canPayAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-canPay')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-canPay-' + p.attr('data-id')).attr('class', 'update-canPay btn ' + d.canPayClass).html(d.canPayTitle);
                    };
                });
            },
            noteAction: function (e) {
                var p = $(e.target).parents('div.order-form'),
                    self = this;
                $.get(p.attr('data-note')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-note-' + p.attr('data-id')).attr('class', 'clearfix').html(d.admin_note);
                    };
                });
            },
        }
        page.init();
    })(jQuery)
</script>