<?php
// Load bootstrap
$this->css(
    Pi::url('public/vendor/bootstrap/css/bootstrap.min.css'),
    array('media' => "all")
);
// Load localization css
$this->css(
    $this->assetLocale('locale.css'),
    array('media' => "all")
);
// locad print css
$this->css(
    $this->assetModule('css/print.css'),
    array('media' => "all")
);
// Get language
$locale = 'fa';
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="utf-8">
</head>
<!--  onload="window.print()" -->
<body onload="window.print()" id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
<div id="print">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 print-title">
                <?php _e('Order invoice'); ?>
            </div>
            <div class="col-12 print-user">
                <div class="clearfix text-normal">
                    <div class="col-6">
                        <?php if (!empty($address['first_name']) && !empty($address['last_name'])) { ?>
                            <p><strong><?php _e('Name'); ?></strong> :
                                <span><?php echo $this->escape($address['first_name']); ?> <?php echo $this->escape($address['last_name']); ?></span>
                            </p>
                        <?php } ?>
                        <?php if (!empty($address['id_number'])) { ?>
                            <p><strong><?php _e('ID number'); ?></strong> :
                                <span><?php echo $this->escape($address['id_number']); ?></span></p>
                        <?php } ?>
                        <?php if (!empty($address['company'])) { ?>
                            <p><strong><?php _e('Company'); ?></strong> :
                                <span><?php echo $this->escape($address['company']); ?></span></p>
                        <?php } ?>
                    </div>
                    <div class="col-6">
                        <?php if (!empty($address['email'])) { ?>
                            <p><strong><?php _e('Email'); ?></strong> :
                                <span><?php echo $this->escape($address['email']); ?></span></p>
                        <?php } ?>
                        <?php if (!empty($address['phone'])) { ?>
                            <p><strong><?php _e('Phone'); ?></strong> :
                                <span><?php echo $this->escape($address['phone']); ?></span></p>
                        <?php } ?>
                        <?php if (!empty($address['mobile'])) { ?>
                            <p><strong><?php _e('Mobile'); ?></strong> :
                                <span><?php echo $this->escape($address['mobile']); ?></span></p>
                        <?php } ?>

                    </div>
                    <div class="col-12">
                        <?php if (!empty($address['city'])) { ?>
                            <strong><?php _e('City'); ?></strong> :
                            <span><?php echo $this->escape($address['city']); ?></span>
                        <?php } ?>
                        <?php if (!empty($address['state'])) { ?>
                            <strong><?php _e('State'); ?></strong> :
                            <span><?php echo $this->escape($address['state']); ?></span>
                        <?php } ?>
                        <?php if (!empty($address['country'])) { ?>
                            <strong><?php _e('Country'); ?></strong> :
                            <span><?php echo $this->escape($address['country']); ?></span>
                        <?php } ?>
                        <?php if (!empty($address['zip_code'])) { ?>
                            <strong><?php _e('Zip code'); ?></strong> :
                            <span><?php echo $this->escape($address['zip_code']); ?></span>
                        <?php } ?>
                        <?php if (!empty($address['address1'])) { ?>
                            <strong><?php _e('Delivery address'); ?></strong> :
                            <span><?php echo $this->escape($address['address1']); ?></span>
                        <?php } ?>
                        <?php if (!empty($address['address2'])) { ?>
                            <strong><?php _e('Invoicing Address'); ?></strong> :
                            <span><?php echo $this->escape($address['address2']); ?></span>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="clearfix print-product">
                
            </div>
            
        </div>
    </div>
</div>
</body>
</html>