<?php
// Load bootstrap
$this->css(
    Pi::url('public/vendor/bootstrap/css/bootstrap.min.css'),
    array('media' => "all")
);
// Load localization css
$this->css(
    $this->assetLocale('locale.css'),
    array('media' => "all")
);
// locad print css
$this->css(
    $this->assetModule('css/print.css'),
    array('media' => "all")
);
// Get language
$locale = 'fa';
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="utf-8">
</head>
<!--  onload="window.print()" -->
<body onload="window.print()" id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
<div id="print">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 print-title">
                <?php _e('Order invoice'); ?>
            </div>
            <div class="col-xs-12 print-user">
                <div class="clearfix text-normal">
                    <div class="col-xs-6">
                        <?php if (!empty($order['first_name']) && !empty($order['last_name'])) { ?>
                            <p><strong><?php _e('Name'); ?></strong> :
                                <span><?php echo $this->escape($order['first_name']); ?> <?php echo $this->escape($order['last_name']); ?></span>
                            </p>
                        <?php } ?>
                        <?php if (!empty($order['id_number'])) { ?>
                            <p><strong><?php _e('ID number'); ?></strong> :
                                <span><?php echo $this->escape($order['id_number']); ?></span></p>
                        <?php } ?>
                        <?php if (!empty($order['company'])) { ?>
                            <p><strong><?php _e('Company'); ?></strong> :
                                <span><?php echo $this->escape($order['company']); ?></span></p>
                        <?php } ?>
                    </div>
                    <div class="col-xs-6">
                        <?php if (!empty($order['email'])) { ?>
                            <p><strong><?php _e('Email'); ?></strong> :
                                <span><?php echo $this->escape($order['email']); ?></span></p>
                        <?php } ?>
                        <?php if (!empty($order['phone'])) { ?>
                            <p><strong><?php _e('Phone'); ?></strong> :
                                <span><?php echo $this->escape($order['phone']); ?></span></p>
                        <?php } ?>
                        <?php if (!empty($order['mobile'])) { ?>
                            <p><strong><?php _e('Mobile'); ?></strong> :
                                <span><?php echo $this->escape($order['mobile']); ?></span></p>
                        <?php } ?>

                    </div>
                    <div class="col-xs-12">
                        <?php if (!empty($order['city'])) { ?>
                            <strong><?php _e('City'); ?></strong> :
                            <span><?php echo $this->escape($order['city']); ?></span>
                        <?php } ?>
                        <?php if (!empty($order['state'])) { ?>
                            <strong><?php _e('State'); ?></strong> :
                            <span><?php echo $this->escape($order['state']); ?></span>
                        <?php } ?>
                        <?php if (!empty($order['country'])) { ?>
                            <strong><?php _e('Country'); ?></strong> :
                            <span><?php echo $this->escape($order['country']); ?></span>
                        <?php } ?>
                        <?php if (!empty($order['zip'])) { ?>
                            <strong><?php _e('Zip code'); ?></strong> :
                            <span><?php echo $this->escape($order['zip']); ?></span>
                        <?php } ?>
                        <?php if (!empty($order['address1'])) { ?>
                            <strong><?php _e('Delivery address'); ?></strong> :
                            <span><?php echo $this->escape($order['address1']); ?></span>
                        <?php } ?>
                        <?php if (!empty($order['address2'])) { ?>
                            <strong><?php _e('Invoicing Address'); ?></strong> :
                            <span><?php echo $this->escape($order['address2']); ?></span>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="clearfix print-product">
                <?php if ($order['type_payment'] == 'installment') { ?>
                    <table class="table table-striped table-bordered table-condensed small">
                        <tr>
                            <th class="text-center text-small"><?php _e('Row'); ?></th>
                            <th class="text-center text-small"><?php _e('Product name'); ?></th>
                            <th class="text-center text-small"><?php _e('Number'); ?></th>
                            <th class="text-center text-small"><?php _e('Per Payment'); ?></th>
                            <th class="text-center text-small"><?php _e('1 months'); ?></th>
                            <th class="text-center text-small"><?php _e('2 months'); ?></th>
                            <th class="text-center text-small"><?php _e('3 months'); ?></th>
                            <th class="text-center text-small"><?php _e('4 months'); ?></th>
                            <th class="text-center text-small"><?php _e('5 months'); ?></th>
                            <th class="text-center text-small"><?php _e('6 months'); ?></th>
                            <th class="text-center text-small"><?php _e('7 months'); ?></th>
                            <th class="text-center text-small"><?php _e('8 months'); ?></th>
                            <th class="text-center text-small"><?php _e('9 months'); ?></th>
                            <th class="text-center text-small"><?php _e('10 months'); ?></th>
                            <th class="text-center text-small"><?php _e('11 months'); ?></th>
                            <th class="text-center text-small"><?php _e('12 months'); ?></th>
                            <th class="text-center text-small"><?php _e('Total'); ?></th>
                        </tr>
                        <?php $i = 1; ?>
                        <?php $total = 0; ?>
                        <?php foreach ($order['products'] as $product) { ?>
                            <tr>
                                <td class="text-center text-small"><?php echo $i; ?></td>
                                <td>
                                    <?php echo $this->escape($product['details']['title']); ?>
                                    <?php if (isset($product['extra']['product']) && !empty($product['extra']['product'])) { ?>
                                        <?php foreach ($product['extra']['product'] as $extraProduct) { ?>
                                            <div class="productItem">
                                                <span><?php echo $this->escape($extraProduct['title']); ?></span> :
                                                <strong><?php echo $this->escape($extraProduct['value']); ?></strong>
                                            </div>
                                        <?php } ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small"><?php echo _number($this->escape($product['number'])); ?></td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][0]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][0]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][1]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][1]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][2]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][2]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][3]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][3]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][4]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][4]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][5]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][5]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][6]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][6]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][7]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][7]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][8]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][8]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][9]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][9]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][10]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][10]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][11]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][11]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment'][12]['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][12]['price'], true)); ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center text-small">
                                    <?php if ($product['extra']['installment']['total']['price']) { ?>
                                        <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment']['total']['price'], true)); ?>
                                        <?php $total = $total + $product['extra']['installment']['total']['price'] ?>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php $i++; ?>
                        <?php } ?>
                        <tr>
                            <td class="text-center text-small" colspan="3"><?php _e('Total'); ?></td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][1]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][1]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][2]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][2]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][3]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][3]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][4]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][4]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][5]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][5]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][6]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][6]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][7]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][7]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][8]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][8]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][9]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][9]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][10]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][10]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][11]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][11]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][12]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][12]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php if ($order['invoices'][13]['total_price']) { ?>
                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($order['invoices'][13]['total_price'], true)); ?>
                                <?php } ?>
                            </td>
                            <td class="text-center text-small">
                                <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($total, true)); ?>
                            </td>
                        </tr>
                    </table>
                <?php } else { ?>

                <?php } ?>
            </div>
            <?php if ($order['type_payment'] == 'installment') { ?>
                <div class="col-xs-12 print-text">
                    <?php _e('Order invoice desc'); ?>
                    <small>(<?php _e('Order invoice desc price'); ?>)</small>
                </div>
                <?php if (!empty($order['installment']['all']['10-order'])) { ?>
                    <div class="clearfix print-table">
                        <table class="table table-striped table-bordered table-condensed small">
                            <tr>
                                <th class="text-center" colspan="18"><?php _e('10 th'); ?></th>
                            </tr>
                            <tr>
                                <th class="text-center text-small"><?php _e('Row'); ?></th>
                                <th class="text-center text-small"><?php _e('Product name'); ?></th>
                                <th class="text-center text-small"><?php _e('Number'); ?></th>
                                <!-- <th class="text-center text-small"><?php _e('Delayed'); ?></th>
                        <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][0]['10-view']); ?></th> -->
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][1]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][2]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][3]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][4]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][5]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][6]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][7]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][8]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][9]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][10]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][11]['10-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][12]['10-view']); ?></th>
                                <th class="text-center text-small">
                                <?php _e('Total'); ?></td>
                            </tr>
                            <?php $i = 1; ?>
                            <?php $total = 0; ?>
                            <?php foreach ($order['installment']['all']['10-order'] as $orderId) { ?>
                                <?php foreach ($order['allproducts'] as $product) { ?>
                                    <?php if ($product['order'] == $orderId) { ?>
                                        <tr>
                                            <td class="text-center text-small"><?php echo $i; ?></td>
                                            <td><?php echo $this->escape($product['details']['title']); ?></td>
                                            <td class="text-center text-small"><?php echo _number($this->escape($product['number'])); ?></td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][1]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][1]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][2]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][2]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][3]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][3]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][4]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][4]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][5]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][5]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][6]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][6]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][7]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][7]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][8]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][8]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][9]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][9]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][10]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][10]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][11]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][11]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][12]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][12]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment']['total']['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment']['total']['price'], true)); ?>
                                                    <?php $total = $total + $product['extra']['installment']['total']['price'] ?>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                        <?php $i++; ?>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                            <tr>
                                <td class="text-center text-small" colspan="3"><?php _e('Total'); ?></td>
                                <!-- <td class="text-center text-small"><?php echo $order['installment']['m']['10-sun']; ?></td>
                        <td class="text-center text-small"><?php echo $order['installment'][0]['10-sun']; ?></td> -->
                                <td class="text-center text-small"><?php echo $order['installment'][1]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][2]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][3]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][4]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][5]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][6]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][7]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][8]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][9]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][10]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][11]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][12]['10-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $this->escape(Pi::api('api', 'order')->viewPrice($total, true)); ?></td>
                            </tr>
                        </table>
                    </div>
                <?php } ?>
                <?php if (!empty($order['installment']['all']['20-order'])) { ?>
                    <div class="clearfix print-table">
                        <table class="table table-striped table-bordered table-condensed small">
                            <tr>
                                <th class="text-center" colspan="18"><?php _e('20 th'); ?></th>
                            </tr>
                            <tr>
                                <th class="text-center text-small"><?php _e('Row'); ?></th>
                                <th class="text-center text-small"><?php _e('Product name'); ?></th>
                                <th class="text-center text-small"><?php _e('Number'); ?></th>
                                <!-- <th class="text-center text-small"><?php _e('Delayed'); ?></th>
                        <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][0]['20-view']); ?></th> -->
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][1]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][2]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][3]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][4]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][5]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][6]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][7]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][8]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][9]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][10]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][11]['20-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][12]['20-view']); ?></th>
                                <th class="text-center text-small">
                                <?php _e('Total'); ?></td>
                            </tr>
                            <?php $i = 1; ?>
                            <?php $total = 0; ?>
                            <?php foreach ($order['installment']['all']['20-order'] as $orderId) { ?>
                                <?php foreach ($order['allproducts'] as $product) { ?>
                                    <?php if ($product['order'] == $orderId) { ?>
                                        <tr>
                                            <td class="text-center text-small"><?php echo $i; ?></td>
                                            <td><?php echo $this->escape($product['details']['title']); ?></td>
                                            <td class="text-center text-small"><?php echo _number($this->escape($product['number'])); ?></td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][1]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][1]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][2]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][2]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][3]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][3]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][4]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][4]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][5]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][5]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][6]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][6]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][7]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][7]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][8]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][8]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][9]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][9]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][10]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][10]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][11]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][11]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][12]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][12]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment']['total']['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment']['total']['price'], true)); ?>
                                                    <?php $total = $total + $product['extra']['installment']['total']['price'] ?>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                        <?php $i++; ?>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                            <tr>
                                <td class="text-center text-small" colspan="3"><?php _e('Total'); ?></td>
                                <!-- <td class="text-center text-small"><?php echo $order['installment']['m']['20-sun']; ?></td>
                        <td class="text-center text-small"><?php echo $order['installment'][0]['20-sun']; ?></td> -->
                                <td class="text-center text-small"><?php echo $order['installment'][1]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][2]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][3]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][4]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][5]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][6]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][7]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][8]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][9]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][10]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][11]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][12]['20-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $this->escape(Pi::api('api', 'order')->viewPrice($total, true)); ?></td>
                            </tr>
                        </table>
                    </div>
                <?php } ?>
                <?php if (!empty($order['installment']['all']['30-order'])) { ?>
                    <div class="clearfix print-table">
                        <table class="table table-striped table-bordered table-condensed small">
                            <tr>
                                <th class="text-center" colspan="18"><?php _e('30 th'); ?></th>
                            </tr>
                            <tr>
                                <th class="text-center text-small"><?php _e('Row'); ?></th>
                                <th class="text-center text-small"><?php _e('Product name'); ?></th>
                                <th class="text-center text-small"><?php _e('Number'); ?></th>
                                <!-- <th class="text-center text-small"><?php _e('Delayed'); ?></th>
                        <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][0]['30-view']); ?></th> -->
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][1]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][2]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][3]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][4]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][5]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][6]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][7]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][8]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][9]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][10]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][11]['30-view']); ?></th>
                                <th class="text-center text-small"><?php echo str_replace("۱۳۹", "۹", $order['installment'][12]['30-view']); ?></th>
                                <th class="text-center text-small">
                                <?php _e('Total'); ?></td>
                            </tr>
                            <?php $i = 1; ?>
                            <?php $total = 0; ?>
                            <?php foreach ($order['installment']['all']['30-order'] as $orderId) { ?>
                                <?php foreach ($order['allproducts'] as $product) { ?>
                                    <?php if ($product['order'] == $orderId) { ?>
                                        <tr>
                                            <td class="text-center text-small"><?php echo $i; ?></td>
                                            <td><?php echo $this->escape($product['details']['title']); ?></td>
                                            <td class="text-center text-small"><?php echo _number($this->escape($product['number'])); ?></td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][1]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][1]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][2]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][2]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][3]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][3]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][4]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][4]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][5]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][5]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][6]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][6]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][7]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][7]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][8]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][8]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][9]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][9]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][10]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][10]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][11]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][11]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment'][12]['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment'][12]['price'], true)); ?>
                                                <?php } ?>
                                            </td>
                                            <td class="text-center text-small">
                                                <?php if ($product['extra']['installment']['total']['price']) { ?>
                                                    <?php echo $this->escape(Pi::api('api', 'order')->viewPrice($product['extra']['installment']['total']['price'], true)); ?>
                                                    <?php $total = $total + $product['extra']['installment']['total']['price'] ?>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                        <?php $i++; ?>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                            <tr>
                                <td class="text-center text-small" colspan="3"><?php _e('Total'); ?></td>
                                <!-- <td class="text-center text-small"><?php echo $order['installment']['m']['30-sun']; ?></td>
                        <td class="text-center text-small"><?php echo $order['installment'][0]['30-sun']; ?></td> -->
                                <td class="text-center text-small"><?php echo $order['installment'][1]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][2]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][3]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][4]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][5]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][6]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][7]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][8]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][9]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][10]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][11]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $order['installment'][12]['30-sun']; ?></td>
                                <td class="text-center text-small"><?php echo $this->escape(Pi::api('api', 'order')->viewPrice($total, true)); ?></td>
                            </tr>
                        </table>
                    </div>
                <?php } ?>
                <div class="clearfix">
                    <div class="col-xs-6 text-center">
                        <?php _e('Seller signature'); ?>
                        <br/>
                        <?php _e('Stamp'); ?>
                    </div>
                    <div class="col-xs-6 text-center">
                        <?php _e('Buyer signature'); ?>
                        <br/>
                        <?php _e('Stamp / fingerprint'); ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
</body>
</html>