<?php
$this->css($this->assetModule('css/admin.css'));
$this->backbone();
?>
<div id="js-order" class="clearfix">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingForm">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseForm" aria-expanded="false" aria-controls="collapseForm">
                        <i class="fas fa-plus"></i> <?php _e('Filter orders'); ?>
                    </a>
                </h4>
            </div>
            <div id="collapseForm" class="panel-collapse collapse" role="tabpanel">
                <div class="panel-body">
                    <?php echo $this->form($form); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix row order-header">
        <div class="col-xs-3">
            <h3><?php _e('List of orders'); ?></h3>
        </div>
        <div class="col-xs-6 text-center totalOrder">
            <strong><?php echo __('Ordered') . ' ' . date('Y') . ' : '?></strong> <?php echo $totalOrdered . ' €' ?>
            -
            <strong><?php echo __('Invoiced') . ' ' . date('Y') . ' : '?></strong> <?php echo $totalBilled . ' €' ?>
            == 
            <strong><?php echo __('Non invoiced') . ' ' . date('Y') . ' : '?></strong> <?php echo $totalNonOrdered . ' €' ?>
        </div>
        <div class="col-xs-3 text-right">
            <a class="btn btn-success" title="<?php _e('New order'); ?>" href="<?php echo $this->url('', array('controller' => 'order', 'action' => 'add')); ?>">
                <i class="fas fa-plus"></i> <?php _e('New order'); ?>
            </a>
        </div>
    </div>

    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th class="text-center small"><?php _e('Code'); ?></th>
                <th class="text-center small"><?php _e('Date'); ?></th>
                <th class="text-center small"><?php _e('Total price'); ?></th>
                <th class="text-center small"><?php _e('Information'); ?></th>
                <th class="text-center small col-xs-3"><?php _e('Products'); ?></th>
                <th class="clearfix col-xs-6">
                    <ul class="list-inline">
                        <li class="text-center small col-xs-2"><?php _e('Order status'); ?></li>
                        <li class="text-center small col-xs-2"><?php _e('Can pay'); ?></li>
                        <li class="text-center small col-xs-1"><?php _e('Payment'); ?></li>
                        <li class="text-center small col-xs-2"><?php _e('Delivery'); ?></li>
                        <li class="text-center small col-xs-1"><?php _e('Note'); ?></li>
                        <li class="text-center small col-xs-4"><?php _e('Action'); ?></li>
                        
                        
                    </ul>
                </th>
            </tr>
            <?php foreach ($list as $order) { ?>
                <?php 
                $class = '';
                if ($order['status_payment'] == \Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID) {
                    $class = 'success';
                } else if ($order['status_payment'] != null && $order['status_payment'] != ''  && $order['status_payment'] == \Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_UNPAID) {
                    $class = 'danger';
                } ?>
                <tr
                    class="<?php echo $class; ?>"
                    data-id="<?php echo $this->escape($order['id']); ?>"
                    data-order="<?php echo $this->escape($order['url_update_order']); ?>"
                    data-canPay="<?php echo $this->escape($order['url_update_canPay']); ?>"
                    data-delivery="<?php echo $this->escape($order['url_update_delivery']); ?>"
                    data-listUser="<?php echo $this->escape($order['url_list_user']); ?>"
                >
                    <td class="text-center small"><?php echo $this->escape($order['code']); ?></td>
                    <td class="text-center small"><?php echo _date($order['time_create']) . '<br>' . date('H:m', $order['time_create']); ?></td>
                    <td class="text-center small"><?php echo $this->escape($order['total_price_view']); ?></td>
                    <td class="text-center small">
                        <ul class="list-inline">
                            <li>
                                <?php echo $this->escape($order['first_name']); ?>
                                <?php echo $this->escape($order['last_name']); ?>
                            </li>
                        </ul>
                    </td>
                    <td class="text-center small">
                        <?php $productsList = array();
                        foreach ($order['products'] as $product) {
                            $productsList[] = $product['details']['title'];
                        }
                        echo implode(' , ',$productsList); ?>
                    </td>
                    <td class="clearfix">
                        <ul class="list-inline">
                            <li class="col-xs-2 text-center">
                                <?php if ($order['status_order'] == \Module\Order\Model\Order::STATUS_ORDER_VALIDATED) { ?>
                                    <span id="update-order-<?php echo $this->escape($order['id']); ?>" class="update-order btn btn-xs <?php echo $this->escape($order['orderClass']); ?>"><?php echo $this->escape($order['orderTitle']); ?></span>
                                <?php } else if ($order['status_order'] == \Module\Order\Model\Order::STATUS_ORDER_DRAFT) { ?>
                                    <span class="label label-warning"><?php echo $this->escape($order['orderTitle']); ?></span>
                                <?php } else { ?>
                                    <span class="label label-danger"><?php echo $this->escape($order['orderTitle']); ?></span>
                                <?php } ?>
                            </li>
                            <li class="col-xs-2 text-center">
                                <span id="update-canPay-<?php echo $this->escape($order['id']); ?>" class="update-canPay btn btn-xs <?php echo $this->escape($order['canPayClass']); ?>"><?php echo $this->escape($order['canPayTitle']); ?></span>
                            </li>
                            <?php /* if ($order['type_payment'] == 'installment') { ?>
                                    <li class="col-xs-2 text-center"><span class="btn btn-xs <?php echo $this->escape($order['paymentClass']); ?>"><?php echo $this->escape($order['paymentTitle']); ?></span></li>
                                <?php } else { ?>
                                    <li class="col-xs-2 text-center"><span id="update-payment-<?php echo $this->escape($order['id']); ?>" class="update-payment btn btn-xs <?php echo $this->escape($order['paymentClass']); ?>"><?php echo $this->escape($order['paymentTitle']); ?></span></li>
                                <?php } */ ?>
                            <li class="col-xs-1 text-center">
                                <?php if ($class == '') { ?>
                                    <span class="label label-warning" data-toggle="tooltip" data-placement="top" title="<?php _e('Pending'); ?>"><?php _e('Pending'); ?></span>
                                <?php } elseif ($class == 'success') { ?>
                                    <span class="label label-success" data-toggle="tooltip" data-placement="top" title="<?php _e('Paid'); ?>"><?php _e('Paid'); ?></span>
                                <?php } else { ?>
                                    <span class="label label-danger" data-toggle="tooltip" data-placement="top" title="<?php _e('Unpaid'); ?>"><?php _e('Unpaid'); ?></span>
                                <?php } ?>
                            </li>
                            <li class="col-xs-2 text-center">
                                <?php if ($order['type_commodity'] == 'product') { ?>
                                    <span id="update-delivery-<?php echo $this->escape($order['id']); ?>" class="update-delivery btn btn-xs <?php echo $this->escape($order['deliveryClass']); ?>"><?php echo $this->escape($order['deliveryTitle']); ?></span>
                                <?php } else { ?>
                                    <span class="label label-default"><?php _e('Its service'); ?></span>
                                <?php } ?>
                            </li>
                            <li class="col-xs-1 text-center">
                                <?php if($order['user_note']) { ?>
                                        <span class="far fa-comments"></span>
                                    <?php } ?> 
                            </li> 
                            <li class="col-xs-4 text-center">
                                <a class="btn btn-primary btn-xs" title="<?php _e('View'); ?>" href="<?php echo $this->escape($order['url_view']); ?>" target="_blank"><i class="far fa-eye"></i>
                                    <?php _e('View'); ?>
                                </a>
                            </li> 
                        </ul>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert"><?php _e('No order is not created yet'); ?></div>
        <div class="alert alert-info" role="alert">
            <h4><?php _e('Todo list for fist time'); ?></h4>
            <ol>
                <li><?php _e('Setup payment gateway from gateway tap'); ?></li>
                <li><?php _e('Setup delivery method from delivery tap'); ?></li>
                <li><?php _e('Setup location from location tap'); ?></li>
            </ol>
        </div>
    <?php } ?>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-order'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.label').hover(this.tooltipAction);
                this.$('.update-order').click(this.orderAction);
                this.$('.update-payment').click(this.paymentAction);
                this.$('.update-delivery').click(this.deliveryAction);
                this.$('.update-canPay').click(this.canPayAction);
                this.$('.show-list-user').click(this.listUserAction);
            },
            tooltipAction: function (e) {
                $('[data-toggle="tooltip"]').tooltip();
            },
            orderAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-order')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-order-' + p.attr('data-id')).attr('class', 'update-order btn btn-xs ' + d.orderClass).html(d.orderTitle);
                    };
                });
            },
            paymentAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-payment')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-payment-' + p.attr('data-id')).attr('class', 'update-payment btn btn-xs ' + d.paymentClass).html(d.paymentTitle);
                    };
                });
            },
            deliveryAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-delivery')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-delivery-' + p.attr('data-id')).attr('class', 'update-delivery btn btn-xs ' + d.deliveryClass).html(d.deliveryTitle);
                    };
                });
            },
            canPayAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-canPay')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-canPay-' + p.attr('data-id')).attr('class', 'update-canPay btn btn-xs ' + d.canPayClass).html(d.canPayTitle);
                    };
                });
            },
            listUserAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-listUser')).done(function (res) {
                    self.modal.html(res).modal('show');
                });
            },
        }
        page.init();
    })(jQuery)
</script>