<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h1 class="mb-3"><?php _e('New order'); ?></h1>
    <div class="alert alert-info">
        <?php _e(
            'You can add manual order for your customer, and link it to a third part module (service or product), and set the gateway (manual payment or online payment)'
        ); ?>
    </div>
    <?php echo $this->form($form); ?>
</div>
