<?php
$this->css($this->assetModule('css/admin.css'));
$this->backbone();
?>
<div id="js-order" class="clearfix">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingForm">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseForm" aria-expanded="false" aria-controls="collapseForm">
                        <i class="fa fa-plus"></i> <?php _e('Filter orders'); ?>
                    </a>
                </h4>
            </div>
            <div id="collapseForm" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingForm">
                <div class="panel-body">
                    <?php echo $this->form($form); ?>
                </div>
            </div>
        </div>
    </div>
    <h3><?php _e('List of orders'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Code'); ?></th>
                <th><?php _e('Total price'); ?></th>
                <th><?php _e('Information'); ?></th>
            </tr>
            <?php foreach ($list as $order) { ?>
                <tr
                    data-id="<?php echo $this->escape($order['id']); ?>"
                    data-order="<?php echo $this->escape($order['url_update_order']); ?>"
                    data-canPay="<?php echo $this->escape($order['url_update_canPay']); ?>"
                    data-payment="<?php echo $this->escape($order['url_update_payment']); ?>"
                    data-delivery="<?php echo $this->escape($order['url_update_delivery']); ?>"
                >
                    <td><?php echo $this->escape($order['id']); ?></td>
                    <td><?php echo $this->escape($order['code']); ?></td>
                    <td><?php echo $this->escape($order['total_price_view']); ?></td>
                    <td class="clearfix">
				        <div class="col-xs-4">
                            <ul class="list-inline small">
                                <li>
                                    <?php echo $this->escape($order['first_name']); ?>
                                    <?php echo $this->escape($order['last_name']); ?>
                                </li>
                                <li class="label label-info">
                                    <?php echo $this->escape($order['user']['identity']); ?>
                                    ( <?php echo $this->escape($order['user']['name']); ?> )
                                </li>
                            </ul>
                        </div>
                        <div class="col-xs-8">
                            <ul class="list-inline">
                                <?php if (in_array($order['status_order'], array(1, 2, 3, 7))) { ?>
                                    <li class="col-xs-3"><span id="update-order-<?php echo $this->escape($order['id']); ?>" class="update-order btn btn-xs <?php echo $this->escape($order['orderClass']); ?>"><?php echo $this->escape($order['orderTitle']); ?></span></li>
                                <?php } else { ?>
                                    <li class="col-xs-3"><span class="label label-danger"><?php echo $this->escape($order['orderTitle']); ?></span></li>
                                <?php } ?>
                                <li class="col-xs-2"><span id="update-canPay-<?php echo $this->escape($order['id']); ?>" class="update-canPay btn btn-xs <?php echo $this->escape($order['canPayClass']); ?>"><?php echo $this->escape($order['canPayTitle']); ?></span></li>
                                <li class="col-xs-2"><span id="update-payment-<?php echo $this->escape($order['id']); ?>" class="update-payment btn btn-xs <?php echo $this->escape($order['paymentClass']); ?>"><?php echo $this->escape($order['paymentTitle']); ?></span></li>
                                <?php if ($order['type_commodity'] == 'product') { ?>
                                    <li class="col-xs-3"><span id="update-delivery-<?php echo $this->escape($order['id']); ?>" class="update-delivery btn btn-xs <?php echo $this->escape($order['deliveryClass']); ?>"><?php echo $this->escape($order['deliveryTitle']); ?></span></li>
                                <?php } else { ?>
                                    <li class="col-xs-3"><span class="label label-default"><?php _e('Its service'); ?></span></li>
                                <?php } ?>
                                <li class="col-xs-2"><a class="btn btn-primary btn-xs" title="<?php _e('View'); ?>" href="<?php echo $this->escape($order['url_view']); ?>" target="_blank"><i class="fa fa-eye"></i> <?php _e('View'); ?></a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert"><?php _e('No order is not created yet'); ?></div>
        <div class="alert alert-info" role="alert">
            <h4><?php _e('Todo list for fist time'); ?></h4>
            <ol>
                <li><?php _e('Setup payment gateway from gateway tap'); ?></li>
                <li><?php _e('Setup delivery method from delivery tap'); ?></li>
                <li><?php _e('Setup location from location tap'); ?></li>
            </ol>
        </div>
    <?php } ?>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-order'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.update-order').click(this.orderAction);
                this.$('.update-payment').click(this.paymentAction);
                this.$('.update-delivery').click(this.deliveryAction);
                this.$('.update-canPay').click(this.canPayAction);
            },
            orderAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-order')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-order-' + p.attr('data-id')).attr('class', 'update-order btn btn-xs ' + d.orderClass).html(d.orderTitle);
                    };
                });
            },
            paymentAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-payment')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-payment-' + p.attr('data-id')).attr('class', 'update-payment btn btn-xs ' + d.paymentClass).html(d.paymentTitle);
                    };
                });
            },
            deliveryAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-delivery')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-delivery-' + p.attr('data-id')).attr('class', 'update-delivery btn btn-xs ' + d.deliveryClass).html(d.deliveryTitle);
                    };
                });
            },
            canPayAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-canPay')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-canPay-' + p.attr('data-id')).attr('class', 'update-canPay btn btn-xs ' + d.canPayClass).html(d.canPayTitle);
                    };
                });
            },
        }
        page.init();
    })(jQuery)
</script>