<?php
$this->css(
    [
        $this->assetModule('css/tempusdominus-bootstrap-4.min.css'),
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery(
    [
        'ui/jquery-ui.custom.min.js',
    ]
);
$this->js(
    [
        $this->assetModule('js/moment.js'),
        $this->assetModule('js/bootstrap-datetimepicker.min.js'),
        $this->assetModule('script/system-msg.js', 'system'),
        $this->assetModule('js/tempusdominus-bootstrap-4.min.js'),

    ]
);
$this->Backbone();
?>
<div class="clearfix">
    <?php echo $this->form($form); ?>
</div>
<script>
    $(
        function () {
            $.fn.datetimepicker.Constructor.Default = $.extend({}, $.fn.datetimepicker.Constructor.Default, {
                icons: {
                    time: 'far fa-clock',
                    date: 'far fa-calendar',
                    up: 'fas fa-angle-up',
                    down: 'fas fa-angle-down',
                    previous: 'fas fa-angle-left',
                    next: 'fas fa-angle-right',
                    today: 'far fa-calendar-check-o',
                    clear: 'far fa-trash',
                    close: 'far fa-times'
                }
            });
            var datetime_start = $('input[name=time_start]').val();
            $('input[name=datetimepicker_start]').datetimepicker(
                {
                    defaultDate: datetime_start == 0 ? false : moment(new Date(1000 * datetime_start)),
                    locale: 'fr',
                }
            );

            $('input[name=datetimepicker_start]').on('change.datetimepicker', function () {
                $('input[name=time_start]').val($('input[name=datetimepicker_start]').datetimepicker('date').unix());
            });

            var datetime_end = $('input[name=time_end]').val();
            $('input[name=datetimepicker_end]').datetimepicker(
                {
                    defaultDate: datetime_end == 0 ? false : moment(new Date(1000 * datetime_end)),
                    locale: 'fr',
                }
            );

            $('input[name=datetimepicker_end]').on('change.datetimepicker', function () {
                $('input[name=time_end]').val($('input[name=datetimepicker_end]').datetimepicker('date').unix());
            });

            $('[data-toggle="tooltip"]').tooltip({html: true});
        }
    );
</script>
