<?php
/**
 * Pi Engine (http://piengine.org)
 *
 * @link            http://code.piengine.org for the Pi Engine source repository
 * @copyright       Copyright (c) Pi Engine http://piengine.org
 * @license         http://piengine.org/license.txt New BSD License
 */

/**
 * @author Hossein Azizabadi <azizabadi@faragostaresh.com>
 */

return [
    'category' => [
        [
            'title' => _a('Admin'),
            'name'  => 'admin',
        ],
        [
            'title' => _a('Front'),
            'name'  => 'front',
        ],
        [
            'title' => _a('Order'),
            'name'  => 'order',
        ],
        [
            'title' => _a('Checkout'),
            'name'  => 'checkout',
        ],
        [
            'title' => _a('Invoice'),
            'name'  => 'invoice',
        ],
        [
            'title' => _a('Print'),
            'name'  => 'print',
        ],
        [
            'title' => _a('Customize'),
            'name'  => 'customize',
        ],
        [
            'title' => _a('Payment'),
            'name'  => 'payment',
        ],
        [
            'title' => _a('Credit'),
            'name'  => 'credit',
        ],
        [
            'title' => _a('Score'),
            'name'  => 'score',
        ],
        [
            'title' => _a('Notification'),
            'name'  => 'notification',
        ],
        [
            'title' => _a('Cron'),
            'name'  => 'cron',
        ],
        [
            'title' => _a('Installment'),
            'name'  => 'installment',
        ],

    ],
    'item'     => [
        // Admin
        'admin_perpage'                  => [
            'category'    => 'admin',
            'title'       => _a('Perpage'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'number_int',
            'value'       => 50,
        ],
        
        // Front
        'view_perpage'                   => [
            'category'    => 'front',
            'title'       => _a('Perpage'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'number_int',
            'value'       => 10,
        ],
        
        // Order
        'order_active'                   => [
            'category'    => 'order',
            'title'       => _a('Order method'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_testmode'                 => [
            'category'    => 'order',
            'title'       => _a('Test mode'),
            'description' => _a('By test mode , you can disable payment on bank and test order level. dont use it on active websites'),
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 0,
        ],
        'order_anonymous'                => [
            'category'    => 'order',
            'title'       => _a('Anonymous users can pay'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 0,
        ],
        'order_filename_prefix'          => [
            'category'    => 'order',
            'title'       => _a('Order filename Prefix'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 'Pi',
        ],
        'order_code_prefix'              => [
            'category'    => 'order',
            'title'       => _a('Order code Prefix'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 'Pi',
        ],
        'invoice_code_prefix'            => [
            'category'    => 'order',
            'title'       => _a('Invoice code Prefix'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 'Pi',
        ],
        'order_update_user'              => [
            'category'    => 'order',
            'title'       => _a('Update user profile'),
            'description' => _a('Update user profile by order informations by user confirmation'),
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 0,
        ],
        'order_additional_price_product' => [
            'category'    => 'order',
            'title'       => _a('Product additional price'),
            'description' => _a('Additional price as ready and delivery, just for products'),
            'edit'        => 'text',
            'filter'      => 'number_int',
            'value'       => 0,
        ],
        'order_additional_price_service' => [
            'category'    => 'order',
            'title'       => _a('Service additional price'),
            'description' => _a('Additional price as setup, just for servicies'),
            'edit'        => 'text',
            'filter'      => 'number_int',
            'value'       => 0,
        ],
        'order_payment'                  => [
            'title'       => _a('After save order'),
            'description' => '',
            'edit'        => [
                'type'    => 'select',
                'options' => [
                    'options' => [
                        'invoice' => _a('Go to invoice page'),
                        'payment' => _a('Go to payment page'),
                    ],
                ],
            ],
            'filter'      => 'text',
            'value'       => 'invoice',
            'category'    => 'order',
        ],
        'order_sellerlogo'               => [
            'category'    => 'order',
            'title'       => _a('Seller logo'),
            'description' => _a('Put logo full URL'),
            'edit'        => 'text',
            'filter'      => 'string',
        ],
        'order_sellerinfo'               => [
            'category'    => 'order',
            'title'       => _a('Seller information'),
            'description' => _a('HTML tags supported, use on invoice page'),
            'edit'        => 'textarea',
            'filter'      => 'string',
        ],
        'order_notification_email'       => [
            'category'    => 'order',
            'title'       => _a('Notification email for each module'),
            'description' => _a('Setup format : shop,shop@mysite.com|guide,guide@mysite.com'),
            'edit'        => 'textarea',
            'filter'      => 'string',
        ],
        
        // Checkout
        'address_type'                  => [
            'title'       => _a('Address type'),
            'description' => '',
            'edit'        => [
                'type'    => 'select',
                'options' => [
                    'options' => [
                        'both' => __('Both'),
                        'individual' => __('Individual'),
                        'company'    => __('Company'),
                    ],
                ],
            ],
            'filter'      => 'text',
            'value'       => 'both',
            'category'    => 'checkout',
        ],
        'address_type_default'                  => [
            'title'       => _a('Default address type'),
            'description' => '',
            'edit'        => [
                'type'    => 'select',
                'options' => [
                    'options' => [
                        'individual' => __('Individual'),
                        'company'    => __('Company'),
                    ],
                ],
            ],
            'filter'      => 'text',
            'value'       => 'individual',
            'category'    => 'checkout',
        ],
        'order_idnumber'                 => [
            'category'    => 'checkout',
            'title'       => _a('Show ID number'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_name'                     => [
            'category'    => 'checkout',
            'title'       => _a('Show name'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_email'                    => [
            'category'    => 'checkout',
            'title'       => _a('Show email'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_phone'                    => [
            'category'    => 'checkout',
            'title'       => _a('Show phone'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_mobile'                   => [
            'category'    => 'checkout',
            'title'       => _a('Show mobile'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_birthday'                 => [
            'category'    => 'checkout',
            'title'       => _a('Show birthday'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_company'                  => [
            'category'    => 'checkout',
            'title'       => _a('Show company'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_company_extra'            => [
            'category'    => 'checkout',
            'title'       => _a('Show company extra (ID , VAT)'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_address1'                 => [
            'category'    => 'checkout',
            'title'       => _a('Show address'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_address2'                 => [
            'category'    => 'checkout',
            'title'       => _a('Show address addition'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_country'                  => [
            'category'    => 'checkout',
            'title'       => _a('Show country'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_countrylist'              => [
            'category'    => 'checkout',
            'title'       => _a('Country list'),
            'description' => _a('Use `|` as delimiter to separate countries'),
            'edit'        => 'textarea',
        ],
        'order_state'                    => [
            'category'    => 'checkout',
            'title'       => _a('Show state'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_city'                     => [
            'category'    => 'checkout',
            'title'       => _a('Show city'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_zip'                      => [
            'category'    => 'checkout',
            'title'       => _a('Show Zip code'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_packing'                  => [
            'category'    => 'checkout',
            'title'       => _a('Show packing'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_location_delivery'        => [
            'category'    => 'checkout',
            'title'       => _a('Show location and delivery'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_usernote'                 => [
            'category'    => 'checkout',
            'title'       => _a('Show user note'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'order_term'                     => [
            'category'    => 'checkout',
            'title'       => _a('Show order term'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 0,
        ],
        'order_termurl'                  => [
            'category'    => 'checkout',
            'title'       => _a('Order term url'),
            'description' => '',
            'edit'        => 'text',
        ],
        
        // Print
        'print_anonymous'                => [
            'category'    => 'print',
            'title'       => _a('Signature zone on print'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        
        // Customize
        'price_custom'                   => [
            'category'    => 'customize',
            'title'       => _a('Use custom price'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 0,
        ],
        'date_format'                    => [
            'category'    => 'customize',
            'title'       => _a('Date format'),
            'description' => _a('For example : yyyy/MM/dd'),
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 'yyyy/MM/dd',
        ],
        
        // Payment
        'payment_gateway_error_url'      => [
            'category'    => 'payment',
            'title'       => _a('Payment gateway error url'),
            'description' => _a('Set back url when gateway have error, set empty for default url'),
            'edit'        => 'text',
            'filter'      => 'string',
        ],
        /* 'payment_shownotpay' => array(
            'category' => 'payment',
            'title' => _a('Show not pay payments'),
            'description' => '',
            'edit' => 'checkbox',
            'filter' => 'number_int',
            'value' => 1
        ), */
        'payment_image'                  => [
            'category'    => 'payment',
            'title'       => _a('Website image URL'),
            'description' => _a('Use on some payment gateway like paypal.'),
            'edit'        => 'text',
            'filter'      => 'string',
        ],
        /* 'payment_methods' => array(
            'category' => 'payment',
            'title' => _a('Payment methods'),
            'edit' => 'textarea',
            'filter' => 'string',
        ), */
        'payment_offline'                => [
            'category'    => 'payment',
            'title'       => _a('Offline payment'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 0,
        ],
        'payment_offline_title'          => [
            'category'    => 'payment',
            'title'       => _a('Title for offline payment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('Offline payment'),
        ],
        'payment_offline_description'    => [
            'category'    => 'payment',
            'title'       => _a('Description for offline payment'),
            'description' => '',
            'edit'        => 'textarea',
            'filter'      => 'string',
            'value'       => _a('Admin make contact about payment whit you after review your order'),
        ],
        'payment_minimum_for_installment'    => [
            'category'    => 'payment',
            'title'       => _a('Minimum value for split payments'),
            'description' => _a('Below of this amount, the invoice is paid throught in a single transaction (1 installment only)'),,
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('100'),
        ],
        
        // Credit
        'credit_active'                  => [
            'category'    => 'credit',
            'title'       => _a('Active credit system'),
            'description' => _a('User can use credit to pay invoice and see history'),
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'credit_type'                    => [
            'title'       => _a('Credit system type'),
            'description' => '',
            'edit'        => [
                'type'    => 'select',
                'options' => [
                    'options' => [
                        'general' => _a('One credit amount for use on all modules'),
                        'module'  => _a('Each module have special credit amount'),
                    ],
                ],
            ],
            'filter'      => 'text',
            'value'       => 'general',
            'category'    => 'credit',
        ],
        
        // Score
        'score_active'                   => [
            'category' => 'score',
            'title'    => _a('Active score system'),
            'edit'     => 'checkbox',
            'filter'   => 'number_int',
            'value'    => 0,
        ],
        'score_division'                 => [
            'category' => 'score',
            'title'    => _a('Division score'),
            'edit'     => 'text',
            'filter'   => 'string',
            'value'    => '0.001',
        ],
        
        // Notification
        'sms_order_user'                 => [
            'category'    => 'notification',
            'title'       => _a('New order notification to user (SMS)'),
            'description' => _a('Dear %s %s, you order %s product by %s price, added on %s website'),
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('Dear %s %s, you order %s product by %s price, added on %s website'),
        ],
        'sms_order_admin'                => [
            'category'    => 'notification',
            'title'       => _a('New order notification to admin (SMS)'),
            'description' => _a('Dear %s admin, %s %s User ordered %s product by %s price'),
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('Dear %s admin, %s %s User ordered %s product by %s price'),
        ],
        'sms_invoice_user'               => [
            'category'    => 'notification',
            'title'       => _a('Pay invoice notification to user (SMS)'),
            'description' => _a('Dear %s %s, You paid invoice %s by %s price for %s order included % product on %s website successfully'),
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('Dear %s %s, You paid invoice %s by %s price for %s order included % product on %s website successfully'),
        ],
        'sms_invoice_admin'              => [
            'category'    => 'notification',
            'title'       => _a('Pay invoice notification to admin (SMS)'),
            'description' => _a('Dear %s admin, %s %s User paid invoice %s by %s price for %s order included % product successfully'),
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('Dear %s admin, %s %s User paid invoice %s by %s price for %s order included % product successfully'),
        ],
        'notification_cron_invoice'      => [
            'category'    => 'notification',
            'title'       => _a('Set X day before due date (CRON)'),
            'description' => _a('Notification invoice due date, X day before invoice time by cron'),
            'edit'        => 'text',
            'filter'      => 'number_int',
            'value'       => 2,
        ],
        'sms_invoice_duedate'            => [
            'category'    => 'notification',
            'title'       => _a('Duedate invoice notification to user (CRON)'),
            'description' => _a('Dear %s %s, You have duedate invoice on next %s days'),
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('Dear %s %s, You have duedate invoice on next %s days'),
        ],
        'notification_cron_expired'      => [
            'category'    => 'notification',
            'title'       => _a('Set X day after expired (CRON)'),
            'description' => _a('Notification invoice expired, X day after invoice time by cron'),
            'edit'        => 'text',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'user_expired_invoice'           => [
            'category'    => 'notification',
            'title'       => _a('Expired invoice notification to user (CRON)'),
            'description' => _a('Dear %s %s, You have expired invoice on %s days ago'),
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('Dear %s %s, You have expired invoice on %s days ago'),
        ],
        
        // Cron
        'module_cron'                    => [
            'category'    => 'cron',
            'title'       => _a('Active this module cron system'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        
        // Installment
        'installment_credit'             => [
            'category'    => 'installment',
            'title'       => _a('Reduce from user credit'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_1_show'                    => [
            'category'    => 'installment',
            'title'       => _a('Show plan 1'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_1_title'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 1 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('1 month'),
        ],
        'plan_1_prepayment'              => [
            'category'    => 'installment',
            'title'       => _a('Plan 1 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 50,
        ],
        'plan_1_profit'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 1 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 0,
        ],
        'plan_1_total'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 1 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 1,
        ],
        'plan_2_show'                    => [
            'category'    => 'installment',
            'title'       => _a('Show plan 2'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_2_title'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 2 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('2 months'),
        ],
        'plan_2_prepayment'              => [
            'category'    => 'installment',
            'title'       => _a('Plan 2 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 20,
        ],
        'plan_2_profit'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 2 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 1.5,
        ],
        'plan_2_total'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 2 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 2,
        ],
        'plan_3_show'                    => [
            'category'    => 'installment',
            'title'       => _a('Show plan 3'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_3_title'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 3 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('3 months'),
        ],
        'plan_3_prepayment'              => [
            'category'    => 'installment',
            'title'       => _a('Plan 3 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 20,
        ],
        'plan_3_profit'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 3 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 2,
        ],
        'plan_3_total'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 3 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 3,
        ],
        'plan_4_show'                    => [
            'category'    => 'installment',
            'title'       => _a('Show plan 4'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_4_title'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 4 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('4 months'),
        ],
        'plan_4_prepayment'              => [
            'category'    => 'installment',
            'title'       => _a('Plan 4 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 20,
        ],
        'plan_4_profit'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 4 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 2.5,
        ],
        'plan_4_total'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 4 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 4,
        ],
        'plan_5_show'                    => [
            'category'    => 'installment',
            'title'       => _a('Show plan 5'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_5_title'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 5 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('5 months'),
        ],
        'plan_5_prepayment'              => [
            'category'    => 'installment',
            'title'       => _a('Plan 5 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 20,
        ],
        'plan_5_profit'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 5 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 3,
        ],
        'plan_5_total'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 5 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 5,
        ],
        'plan_6_show'                    => [
            'category'    => 'installment',
            'title'       => _a('Show plan 6'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_6_title'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 6 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('6 months'),
        ],
        'plan_6_prepayment'              => [
            'category'    => 'installment',
            'title'       => _a('Plan 6 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 20,
        ],
        'plan_6_profit'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 6 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 3,
        ],
        'plan_6_total'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 6 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 6,
        ],
        'plan_7_show'                    => [
            'category'    => 'installment',
            'title'       => _a('Show plan 7'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_7_title'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 7 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('7 months'),
        ],
        'plan_7_prepayment'              => [
            'category'    => 'installment',
            'title'       => _a('Plan 7 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 20,
        ],
        'plan_7_profit'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 7 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 3,
        ],
        'plan_7_total'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 7 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 7,
        ],
        'plan_8_show'                    => [
            'category'    => 'installment',
            'title'       => _a('Show plan 8'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_8_title'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 8 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('8 months'),
        ],
        'plan_8_prepayment'              => [
            'category'    => 'installment',
            'title'       => _a('Plan 8 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 20,
        ],
        'plan_8_profit'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 8 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 3,
        ],
        'plan_8_total'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 8 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 8,
        ],
        'plan_9_show'                    => [
            'category'    => 'installment',
            'title'       => _a('Show plan 9'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_9_title'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 9 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('9 months'),
        ],
        'plan_9_prepayment'              => [
            'category'    => 'installment',
            'title'       => _a('Plan 9 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 20,
        ],
        'plan_9_profit'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 9 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 3,
        ],
        'plan_9_total'                   => [
            'category'    => 'installment',
            'title'       => _a('Plan 9 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 9,
        ],
        'plan_10_show'                   => [
            'category'    => 'installment',
            'title'       => _a('Show plan 10'),
            'description' => '',
            'edit'        => 'checkbox',
            'filter'      => 'number_int',
            'value'       => 1,
        ],
        'plan_10_title'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 10 : Title'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => _a('10 months'),
        ],
        'plan_10_prepayment'             => [
            'category'    => 'installment',
            'title'       => _a('Plan 10 : Prepayment'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 20,
        ],
        'plan_10_profit'                 => [
            'category'    => 'installment',
            'title'       => _a('Plan 10 : Profit'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 3,
        ],
        'plan_10_total'                  => [
            'category'    => 'installment',
            'title'       => _a('Plan 10 : Total'),
            'description' => '',
            'edit'        => 'text',
            'filter'      => 'string',
            'value'       => 10,
        ],
        
        // head_meta
        'text_description_checkup'       => [
            'category'    => 'head_meta',
            'title'       => _a('Description for checkup page'),
            'description' => '',
            'edit'        => 'textarea',
            'filter'      => 'string',
            'value'       => '',
        ],
        
        // Invoice
        'invoice_text_description'       => [
            'category'    => 'invoice',
            'title'       => _a('Description for invoice'),
            'description' => '',
            'edit'        => 'textarea',
            'filter'      => 'string',
            'value'       => '',
        ],
        'invoice_text_footer'            => [
            'category'    => 'invoice',
            'title'       => _a('Text for footer'),
            'description' => '',
            'edit'        => 'textarea',
            'filter'      => 'string',
            'value'       => '',
        ],
        'invoice_header_image'           => [
            'category'    => 'invoice',
            'title'       => _a('Invoice header image path'),
            'description' => '',
            'edit'        => 'text',
        ],
        'invoice_header_logo'            => [
            'category'    => 'invoice',
            'title'       => _a('Invoice header logo path'),
            'description' => 'Square',
            'edit'        => 'text',
        ],
    ],
];
