<?php $this->css($this->assetModule('css/block.css', 'order')); ?>
<div class="order-block-detail">
    <div class="order-block-detail-tab" role="tabpanel">
        <ul class="nav nav-tabs">
            <li role="presentation" class="nav-item"><a class="nav-link active" href="#invoice" aria-controls="invoice" role="tab"
                                                        data-toggle="tab"><?php echo _b('Invoices'); ?></a></li>
            <li role="presentation" class="nav-item"><a class="nav-link" href="#order" aria-controls="order" role="tab"
                                                        data-toggle="tab"><?php echo _b('Orders'); ?></a></li>
            <li role="presentation" class="nav-item"><a class="nav-link" href="#user" aria-controls="user" role="tab"
                                                        data-toggle="tab"><?php echo _b('User informations'); ?></a></li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="invoice">
                <?php if ($block['resources']['invoices']) { ?>
                    <?php foreach ($block['resources']['invoices'] as $invoice) { ?>
                        <table class="table table-striped table-bordered table-sm">
                            <tr>
                                <th class="col-md-1"><?php echo _b('ID'); ?></th>
                                <th class="col-md-1"><?php echo _b('Type'); ?></th>
                                <th class="col-md-1"><?php echo _b('Time Create'); ?></th>
                                <th class="col-md-9 text-right"><?php echo _b('Action'); ?></th>
                            </tr>
                            <?php
                            if ($invoice['status'] == 1) {
                                $badgeIdClass = 'badge-success';
                            } elseif ($invoice['status'] == 2) {
                                $badgeIdClass = 'badge-warning';
                            } elseif ($invoice['status'] == 3) {
                                $badgeIdClass = 'badge-danger';
                            }
                            ?>
                            <tr>
                                <td><span
                                            class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($invoice['code']); ?></span>
                                </td>
                                <td><?php echo $this->escape($invoice['type']); ?></td>
                                <td><?php echo $this->escape($invoice['time_create_view']); ?></td>
                                <td class="text-right">
                                    <a class="btn btn-primary btn-sm" title="<?php echo _b('View / Pay'); ?>"
                                       href="<?php echo $this->url('order', ['module' => 'order', 'controller' => 'detail', 'id' => $invoice['order']]); ?>"><i
                                                class="fas fa-edit"></i> <?php echo _b('View / Pay'); ?></a>
                                </td>
                            </tr>
                        </table>

                        <?php foreach ($invoice['installments'] as $installment) { ?>
                            <table class="table table-striped table-installment table-bordered table-sm">
                                <tr>
                                    <th class="col-md-1 transparent"></th>
                                    <th class="col-md-1"><?php _e('Installment'); ?></th>
                                    <th class="col-md-1"><?php _e('Price'); ?></th>
                                    <th class="col-md-1"><?php _e('Credit price'); ?></th>
                                    <th class="col-md-2"><?php _e('Due date'); ?></th>
                                    <th class="col-md-2"><?php _e('Time pay'); ?></th>
                                    <th class="col-md-4"><?php _e('Gateway'); ?></th>
                                </tr>
                                <?php
                                $rowClass = '';
                                if ($installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_UNPAID) {
                                    $badgeIdClass = 'badge-warning';
                                    $rowClass     = ' class="warning"';
                                    if ($installment['time_duedate'] < strtotime("-1 day")) {
                                        $rowClass = ' class="danger"';
                                    }
                                } elseif ($installment['status_payment'] == Module\Order\Model\Invoice\Installment::STATUS_PAYMENT_PAID) {
                                    $badgeIdClass = 'badge-success';
                                    $rowClass     = ' class="success"';
                                }
                                ?>
                                <tr<?php echo $rowClass; ?>>
                                    <td class="transparent"></td>
                                    <td><?php echo $installment['count'] . ' / ' . count($invoice['installments']) ?></td>
                                    <td><?php echo $this->escape($installment['due_price_view']); ?></td>
                                    <td><?php echo $this->escape($installment['credit_price_view']); ?></td>
                                    <td><?php echo $this->escape($installment['time_duedate_view']); ?></td>
                                    <td><?php echo $this->escape($installment['time_payment_view']); ?></td>
                                    <td><?php echo isset($block['gateways'][$installment['gateway']]) ? $block['gateways'][$installment['gateway']]
                                            : ''; ?></td>

                                </tr>
                            </table>
                        <?php } ?>
                    <?php } ?>
                    <p>
                        <span class="badge badge-success"><?php echo _b('Paid'); ?></span>
                        <span class="badge badge-warning"><?php echo _b('Unpaid'); ?></span>
                        <span class="badge badge-danger"><?php echo _b('Canceled'); ?></span>
                    </p>
                <?php } else { ?>
                    <div class="alert alert-warning"
                         role="alert"><?php echo _b('You dont have any invoice yet'); ?></div>
                <?php } ?>
            </div>
            <div role="tabpanel" class="tab-pane" id="order">
                <?php if ($block['resources']['orders']) { ?>
                    <table class="table table-striped table-bordered table-sm">
                        <tr>
                            <th><?php echo _b('ID'); ?></th>
                            <th><?php echo _b('Time create'); ?></th>
                            <th><?php echo _b('Price'); ?></th>
                            <th><?php echo _b('Action'); ?></th>
                        </tr>
                        <?php foreach ($block['resources']['orders'] as $order) { ?>
                            <tr>
                                <td><?php echo $this->escape($order['code']); ?></td>
                                <td><?php echo $this->escape($order['time_create_view']); ?></td>
                                <td><?php echo $this->escape($order['total_price_view']); ?></td>
                                <td>
                                    <a class="btn btn-primary btn-sm" title="<?php echo _b('View'); ?>"
                                       href="<?php echo $this->url('order', ['module' => 'order', 'controller' => 'detail', 'id' => $order['id']]); ?>"><i
                                                class="fas fa-edit"></i> <?php echo _b('View'); ?></a>
                                </td>
                            </tr>
                        <?php } ?>
                    </table>
                <?php } else { ?>
                    <div class="alert alert-warning" role="alert"><?php echo _b('You dont have any order yet'); ?></div>
                <?php } ?>
            </div>
            <div role="tabpanel" class="tab-pane" id="user">
                <div class="well">
                    <div class="clearfix">
                        <div class="col-md-6">
                            <?php if (!empty($block['resources']['credit'])) { ?>
                                <p><strong><?php echo _b('Credit'); ?></strong> : <span
                                            class="badge badge-success"><?php echo Pi::api('api', 'order')->viewPrice(
                                            $this->escape($block['resources']['credit'])
                                        ); ?></span>
                                </p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['first_name']) && !empty($block['resources']['last_name'])) { ?>
                                <p><strong><?php echo _b('Name'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['first_name']); ?><?php echo $this->escape(
                                            $block['resources']['last_name']
                                        ); ?></span>
                                </p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['city'])) { ?>
                                <p><strong><?php echo _b('City'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['city']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['state'])) { ?>
                                <p><strong><?php echo _b('State'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['state']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['country'])) { ?>
                                <p><strong><?php echo _b('Country'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['country']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['zip_code'])) { ?>
                                <p><strong><?php echo _b('Zip code'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['zip_code']); ?></span></p>
                            <?php } ?>
                        </div>
                        <div class="col-md-6">
                            <?php if (!empty($block['resources']['email'])) { ?>
                                <p><strong><?php echo _b('Email'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['email']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['phone'])) { ?>
                                <p><strong><?php echo _b('Phone'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['phone']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['mobile'])) { ?>
                                <p><strong><?php echo _b('Mobile'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['mobile']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['company'])) { ?>
                                <p><strong><?php echo _b('Company'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['company']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['company_id'])) { ?>
                                <p><strong><?php echo _b('Company ID'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['company_id']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['company_vat'])) { ?>
                                <p><strong><?php echo _b('Company VAT'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['company_vat']); ?></span></p>
                            <?php } ?>
                        </div>
                        <div class="col-md-12">
                            <?php if (!empty($block['resources']['address1'])) { ?>
                                <p><strong><?php echo _b('Delivery address'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['address1']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($block['resources']['address2'])) { ?>
                                <p><strong><?php echo _b('Invoicing Address'); ?></strong> :
                                    <span><?php echo $this->escape($block['resources']['address2']); ?></span></p>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="order-block-detail-more text-right">
        <a class="btn btn-success btn-sm" title="<?php echo _b('More informations'); ?>"
           href="<?php echo $this->escape($block['more']); ?>"><?php echo _b('More informations'); ?></a>
    </div>
</div>