<div class="order-block-installment">
	<div class="order-block-detail-tab" role="tabpanel">
		<ul class="nav nav-tabs">
			<li role="presentation" class="active">
				<a href="#summery" aria-controls="summery" role="tab" data-toggle="tab"><?php echo _b('Summery'); ?></a>
			</li>
			<li role="presentation">
				<a href="#invoice" aria-controls="invoice" role="tab" data-toggle="tab">
					<?php echo _b('Payable invoices'); ?>
                    <?php if (count($block['resources']['invoices']) > 0) { ?>
                    <span class="label label-danger"><?php echo _number(count($block['resources']['invoices'])); ?></span>
                    <?php } else { ?>
                    <span class="label label-success"><?php echo _number(count($block['resources']['invoices'])); ?></span>
                    <?php } ?>
				</a>
			</li>
    		<li role="presentation">
    			<a href="#order" aria-controls="order" role="tab" data-toggle="tab"><?php echo _b('Orders'); ?></a>
    		</li>
		</ul>
		<div class="tab-content">
    		<div role="tabpanel" class="tab-pane active" id="summery">
    			<h3 class="text-center"><?php echo _b('Desc'); ?> <small>قیمت ها به تومان می باشد</small></h3>
				<table class="table table-striped table-bordered table-condensed small">
					<tr>
						<th class="text-center col-md-table-16"><?php echo _b('10 th'); ?></th>
			            <th class="text-center col-md-table-16"><?php echo _b('Debt'); ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][0]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][1]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][2]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][3]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][4]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][5]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][6]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][7]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][8]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][9]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][10]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][11]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][12]['10-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo _b('Total'); ?></td>
					</tr>
					<?php foreach ($block['d']['all']['10-order'] as $orderItem) { ?>
					<tr class="text-muted">
						<td class="text-center"><a title="<?php echo $block['resources']['orders'][$orderItem]['code']; ?>" href="<?php echo $this->url('order', array('module' => 'order', 'controller' => 'detail', 'id' => $block['resources']['orders'][$orderItem]['id'])); ?>"><?php echo $block['resources']['orders'][$orderItem]['code']; ?></a></td>
						<td class="text-center"><?php if ($block['d']['m']['10-invoice'][$orderItem]['total_price_view']) {echo $block['d']['m']['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][0]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][0]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][1]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][1]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][2]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][2]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][3]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][3]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][4]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][4]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][5]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][5]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][6]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][6]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][7]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][7]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][8]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][8]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][9]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][9]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][10]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][10]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][11]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][11]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if ($block['d'][12]['10-invoice'][$orderItem]['total_price_view']) {echo $block['d'][12]['10-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"></td>
					</tr>
					<?php } ?>
					<tr>
						<td class="text-center"><?php echo _b('Amount'); ?></td>
			            <td class="text-center"><?php echo $block['d']['m']['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][0]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][1]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][2]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][3]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][4]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][5]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][6]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][7]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][8]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][9]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][10]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][11]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][12]['10-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d']['all']['10-sun-view']; ?></td>
					</tr>
					<!-- <tr>
						<td colspan="16" class="text-right">
							<button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#10-Modal">
								<?php echo _b('Details'); ?>
							</button>
						</td>
					</tr> -->
				</table>
				<!-- <div class="modal fade" id="10-Modal" tabindex="-1" role="dialog" aria-labelledby="10-ModalLabel" aria-hidden="true">
					<div class="modal-dialog modal-lg">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-label="<?php echo _b('Close'); ?>"><span aria-hidden="true">&times;</span></button>
								<h4 class="modal-title" id="10-ModalLabel"><?php echo _b('10 th invoices'); ?></h4>
							</div>
							<div class="modal-body">
        						<?php if (!empty($block['d']['all']['10-invoice'])) { ?>
								<table class="table table-striped table-bordered table-condensed small">
									<tr>
										<th class="text-center"><?php echo _b('Amount'); ?></th>
										<th class="text-center"><?php echo _b('Time Create'); ?></th>
										<th class="text-center"><?php echo _b('Due date'); ?></th>
										<th class="text-center"><?php echo _b('Action'); ?></th>
									</tr>
									<?php foreach($block['d']['all']['10-invoice'] as $invoice) { ?>
									<tr>
										<td class="text-center"><?php echo $this->escape($invoice['total_price_view']); ?></td>
										<td class="text-center"><?php echo $this->escape($invoice['time_create_view']); ?></td>
										<td class="text-center"><?php echo $this->escape($invoice['time_duedate_view']); ?></td>
										<td class="text-center">
											<a class="btn btn-primary" title="<?php echo _b('View / Pay'); ?>" href="<?php echo $this->url('order', array('module' => 'order', 'controller' => 'invoice', 'id' => $invoice['id'])); ?>"><i class="fa fa-edit"></i> <?php echo _b('View / Pay'); ?></a>
										</td>
									</tr>
									<?php } ?>
								</table>
        						<?php } else { ?>
        						<div class="alert alert-info" role="alert"><?php echo _b('You dont have any invoice on this time'); ?></div>
        						<?php } ?>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-success" data-dismiss="modal"><?php echo _b('Close'); ?></button>
							</div>
    					</div>
					</div>
				</div> -->
				<table class="table table-striped table-bordered table-condensed small">
					<tr>
						<th class="text-center col-md-table-16"><?php echo _b('20 th'); ?></th>
			            <th class="text-center col-md-table-16"><?php echo _b('Debt'); ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][0]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][1]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][2]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][3]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][4]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][5]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][6]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][7]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][8]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][9]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][10]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][11]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][12]['20-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo _b('Total'); ?></td>
					</tr>
					<?php foreach ($block['d']['all']['20-order'] as $orderItem) { ?>
					<tr class="text-muted">
						<td class="text-center"><a title="<?php echo $block['resources']['orders'][$orderItem]['code']; ?>" href="<?php echo $this->url('order', array('module' => 'order', 'controller' => 'detail', 'id' => $block['resources']['orders'][$orderItem]['id'])); ?>"><?php echo $block['resources']['orders'][$orderItem]['code']; ?></a></td>
						<td class="text-center"><?php if (isset($block['d']['m']['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d']['m']['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][0]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][0]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][1]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][1]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][2]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][2]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][3]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][3]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][4]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][4]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][5]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][5]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][6]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][6]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][7]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][7]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][8]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][8]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][9]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][9]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][10]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][10]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][11]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][11]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][12]['20-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][12]['20-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"></td>
					</tr>
					<?php } ?>
					<tr>
						<td class="text-center"><?php echo _b('Amount'); ?></td>
			            <td class="text-center"><?php echo $block['d']['m']['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][0]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][1]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][2]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][3]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][4]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][5]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][6]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][7]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][8]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][9]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][10]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][11]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][12]['20-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d']['all']['20-sun-view']; ?></td>
					</tr>
					<!-- <tr>
						<td colspan="16" class="text-right">
							<button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#20-Modal">
								<?php echo _b('Details'); ?>
							</button>
						</td>
					</tr> -->
				</table>
				<!-- <div class="modal fade" id="20-Modal" tabindex="-1" role="dialog" aria-labelledby="20-ModalLabel" aria-hidden="true">
					<div class="modal-dialog modal-lg">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-label="<?php echo _b('Close'); ?>"><span aria-hidden="true">&times;</span></button>
								<h4 class="modal-title" id="20-ModalLabel"><?php echo _b('20 th invoices'); ?></h4>
							</div>
							<div class="modal-body">
        						<?php if (!empty($block['d']['all']['20-invoice'])) { ?>
								<table class="table table-striped table-bordered table-condensed small">
									<tr>
										<th class="text-center"><?php echo _b('Amount'); ?></th>
										<th class="text-center"><?php echo _b('Time Create'); ?></th>
										<th class="text-center"><?php echo _b('Due date'); ?></th>
										<th class="text-center"><?php echo _b('Action'); ?></th>
									</tr>
									<?php foreach($block['d']['all']['20-invoice'] as $invoice) { ?>
									<tr>
										<td class="text-center"><?php echo $this->escape($invoice['total_price_view']); ?></td>
										<td class="text-center"><?php echo $this->escape($invoice['time_create_view']); ?></td>
										<td class="text-center"><?php echo $this->escape($invoice['time_duedate_view']); ?></td>
										<td class="text-center">
											<a class="btn btn-primary" title="<?php echo _b('View / Pay'); ?>" href="<?php echo $this->url('order', array('module' => 'order', 'controller' => 'invoice', 'id' => $invoice['id'])); ?>"><i class="fa fa-edit"></i> <?php echo _b('View / Pay'); ?></a>
										</td>
									</tr>
									<?php } ?>
								</table>
        						<?php } else { ?>
        						<div class="alert alert-info" role="alert"><?php echo _b('You dont have any invoice on this time'); ?></div>
        						<?php } ?>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-success" data-dismiss="modal"><?php echo _b('Close'); ?></button>
							</div>
    					</div>
					</div>
				</div> -->
				<table class="table table-striped table-bordered table-condensed small">
					<tr>
						<th class="text-center col-md-table-16"><?php echo _b('30 th'); ?></th>
			            <th class="text-center col-md-table-16"><?php echo _b('Debt'); ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][0]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][1]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][2]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][3]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][4]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][5]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][6]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][7]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][8]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][9]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][10]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][11]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo $block['d'][12]['30-view']; ?></th>
			            <th class="text-center col-md-table-16"><?php echo _b('Total'); ?></td>
					</tr>
					<?php foreach ($block['d']['all']['30-order'] as $orderItem) { ?>
					<tr class="text-muted">
						<td class="text-center"><a title="<?php echo $block['resources']['orders'][$orderItem]['code']; ?>" href="<?php echo $this->url('order', array('module' => 'order', 'controller' => 'detail', 'id' => $block['resources']['orders'][$orderItem]['id'])); ?>"><?php echo $block['resources']['orders'][$orderItem]['code']; ?></a></td>
						<td class="text-center"><?php if (isset($block['d']['m']['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d']['m']['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][0]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][0]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][1]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][1]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][2]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][2]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][3]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][3]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][4]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][4]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][5]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][5]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][6]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][6]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][7]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][7]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][8]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][8]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][9]['30-invoice'][$orderItem]['total_price_view'])) { echo $block['d'][9]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][10]['30-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][10]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][11]['30-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][11]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"><?php if (isset($block['d'][12]['30-invoice'][$orderItem]['total_price_view'])) {echo $block['d'][12]['30-invoice'][$orderItem]['total_price_view'];} ?></td>
			            <td class="text-center"></td>
					</tr>
					<?php } ?>
					<tr>
						<td class="text-center"><?php echo _b('Amount'); ?></td>
			            <td class="text-center"><?php echo $block['d']['m']['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][0]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][1]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][2]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][3]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][4]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][5]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][6]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][7]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][8]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][9]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][10]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][11]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d'][12]['30-sun']; ?></td>
			            <td class="text-center"><?php echo $block['d']['all']['30-sun-view']; ?></td>
					</tr>
					<!-- <tr>
						<td colspan="16" class="text-right">
							<button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#30-Modal">
								<?php echo _b('Details'); ?>
							</button>
						</td>
					</tr> -->
				</table>
				<!-- <div class="modal fade" id="30-Modal" tabindex="-1" role="dialog" aria-labelledby="30-ModalLabel" aria-hidden="true">
					<div class="modal-dialog modal-lg">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-label="<?php echo _b('Close'); ?>"><span aria-hidden="true">&times;</span></button>
								<h4 class="modal-title" id="30-ModalLabel"><?php echo _b('30 th invoices'); ?></h4>
							</div>
							<div class="modal-body">
        						<?php if (!empty($block['d']['all']['30-invoice'])) { ?>
								<table class="table table-striped table-bordered table-condensed small">
									<tr>
										<th class="text-center"><?php echo _b('Amount'); ?></th>
										<th class="text-center"><?php echo _b('Time Create'); ?></th>
										<th class="text-center"><?php echo _b('Due date'); ?></th>
										<th class="text-center"><?php echo _b('Action'); ?></th>
									</tr>
									<?php foreach($block['d']['all']['30-invoice'] as $invoice) { ?>
									<tr>
										<td class="text-center"><?php echo $this->escape($invoice['total_price_view']); ?></td>
										<td class="text-center"><?php echo $this->escape($invoice['time_create_view']); ?></td>
										<td class="text-center"><?php echo $this->escape($invoice['time_duedate_view']); ?></td>
										<td class="text-center">
											<a class="btn btn-primary" title="<?php echo _b('View / Pay'); ?>" href="<?php echo $this->url('order', array('module' => 'order', 'controller' => 'invoice', 'id' => $invoice['id'])); ?>"><i class="fa fa-edit"></i> <?php echo _b('View / Pay'); ?></a>
										</td>
									</tr>
									<?php } ?>
								</table>
        						<?php } else { ?>
        						<div class="alert alert-info" role="alert"><?php echo _b('You dont have any invoice on this time'); ?></div>
        						<?php } ?>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-success" data-dismiss="modal"><?php echo _b('Close'); ?></button>
							</div>
    					</div>
					</div>
				</div> -->
				<table class="table table-striped table-bordered table-condensed small">
					<tr>
						<th class="text-center col-md-11">جمع کل</th>
			            <th class="text-center col-md-1"><?php echo $block['d']['total-view']; ?></th>
					</tr>
				</table>
    		</div>
    		<div role="tabpanel" class="tab-pane" id="invoice">
    			<h3 class="text-center"><?php echo _b('Invoices list'); ?></h3>
    			<?php if ($block['resources']['invoices']) { ?>
				<table class="table table-striped table-bordered table-condensed small">
					<tr>
						<th class="text-center"><?php echo _b('Amount'); ?></th>
						<th class="text-center"><?php echo _b('Time Create'); ?></th>
						<th class="text-center"><?php echo _b('Due date'); ?></th>
						<th class="text-center"><?php echo _b('Action'); ?></th>
					</tr>
					<?php foreach($block['resources']['invoices'] as $invoice) { ?>
					<tr>
						<td class="text-center"><?php echo $this->escape($invoice['total_price_view']); ?></td>
						<td class="text-center"><?php echo $this->escape($invoice['time_create_view']); ?></td>
						<td class="text-center"><?php echo $this->escape($invoice['time_duedate_view']); ?></td>
						<td class="text-center">
							<a class="btn btn-primary" title="<?php echo _b('View / Pay'); ?>" href="<?php echo $this->url('order', array('module' => 'order', 'controller' => 'invoice', 'id' => $invoice['id'])); ?>"><i class="fa fa-edit"></i> <?php echo _b('View / Pay'); ?></a>
						</td>
					</tr>
					<?php } ?>
				</table>
				<?php } else { ?>
				<div class="alert alert-warning" role="alert"><?php echo _b('You dont have any invoice yet'); ?></div>
				<?php } ?>
    		</div>
    		<div role="tabpanel" class="tab-pane" id="order">
    			<h3 class="text-center"><?php echo _b('Orders list'); ?></h3>
    			<?php if ($block['resources']['orders']) { ?>
				<table class="table table-striped table-bordered table-condensed small">
					<tr>
						<th class="text-center"><?php echo _b('ID'); ?></th>
						<th class="text-center"><?php echo _b('Time create'); ?></th>
						<th class="text-center"><?php echo _b('Amount'); ?></th>
						<th class="text-center"><?php echo _b('Gateway'); ?></th>
						<th class="text-center"><?php echo _b('Action'); ?></th>
					</tr>
					<?php foreach($block['resources']['orders'] as $order) { ?>
					<tr>
						<td class="text-center"><?php echo $this->escape($order['code']); ?></td>
						<td class="text-center"><?php echo $this->escape($order['time_create_view']); ?></td>
						<td class="text-center"><?php echo $this->escape($order['total_price_view']); ?></td>
						<td class="text-center"><?php echo $this->escape($order['gateway']); ?></td>
						<td class="text-center">
							<a class="btn btn-primary" title="<?php echo _b('View'); ?>" href="<?php echo $this->url('order', array('module' => 'order', 'controller' => 'detail', 'id' => $order['id'])); ?>"><i class="fa fa-edit"></i> <?php echo _b('View'); ?></a>
						</td>
					</tr>
					<?php } ?>
				</table>
				<?php } else { ?>
				<div class="alert alert-warning" role="alert"><?php echo _b('You dont have any order yet'); ?></div>
				<?php } ?>
    		</div>
		</div>
	</div>
	<div class="order-block-detail-more text-right">
		<a class="btn btn-success btn-sm" title="<?php echo _b('More informations'); ?>" href="<?php echo $this->escape($block['more']); ?>"><?php echo _b('More informations'); ?></a>
	</div>
</div>