<?php
$this->css(
    [
        $this->assetModule('css/front.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
$this->headMeta('noindex', 'robots');
?>
<div id="address-form" class="clearfix">
    <div class="col-md-12">
        <h3><?php echo $this->escape($title); ?></h3>
        <?php echo $this->form($form, 'modal'); ?>
    </div>
</div>
<script>
    $(document).ready(function () {

        var accountTypeChange = function() {

            var show = $('[name=account_type]:checked').val() == 'company';
            if (show) {
                $('[name=company]').closest('.row').show();
                $('[name=company_address1]').closest('.row').show();
                $('[name=company_address2]').closest('.row').show();
                $('[name=company_zip_code]').closest('.row').show();
                $('[name=company_city]').closest('.row').show();
                $('[name=company_state]').closest('.row').show();
                $('[name=company_country]').closest('.row').show();
                $('[name=company_id]').closest('.row').show();
                $('[name=company_vat]').closest('.row').show();
                $('.html-raw').show();
                $('.html-raw').show();

            } else {
                $('[name=company]').closest('.row').hide();
                $('[name=company_address1]').closest('.row').hide();
                $('[name=company_address2]').closest('.row').hide();
                $('[name=company_zip_code]').closest('.row').hide();
                $('[name=company_city]').closest('.row').hide();
                $('[name=company_state]').closest('.row').hide();
                $('[name=company_country]').closest('.row').hide();
                $('[name=company_id]').closest('.row').hide();
                $('[name=company_vat]').closest('.row').hide();
                $('.html-raw').hide();
                $('.html-raw').hide();
            }
        };

        $('[name=account_type]').change(accountTypeChange);
        accountTypeChange();

        $('form#address').submit(
            function () {
                $.post(
                    $('form#address').attr('action'),
                    $('form#address').serialize(),
                    function (data) {
                        if (data.status == 1) {
                            window.location.reload();
                        } else {
                            $("#addressModal").find(".modal-body").html(data);
                        }
                    }
                );
                return false;
            }
        )
    });
</script>
