<?php
$this->css(array(
    $this->assetModule('css/front.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->backbone();
$script = <<<'EOT'
(function($) {
    var page = {
        el: $('#js-order'),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            _.bindAll(this);
            this.$('#select-location').on("change",this.locationAction);
            this.$('#select-delivery').on("change",this.deliveryAction);
            this.$('#select-payment').on("change",this.paymentAction);
            this.$('.showCustomerFrom').on("click",this.makeOrderAction);
        },
        locationAction: function(e) {
            var url = "%s";
            $.getJSON(url + $('#select-location').val()).done(function(result) {
                if (result.status == 1) {
                    var htmlOptins = '';
                    $.each(result.data, function( index, value ) {
                        if (value.status==1) {
                            htmlOptins = htmlOptins
                                + "<option value='" + value.delivery + "'>"
                                + value.title + " - "
                                + " %s " + value.price + " - "
                                + " %s " + value.delivery_time  + " %s "
                                + "</option>";
                        } else {
                            htmlOptins = htmlOptins
                                + "<option value='" + value.delivery + "'>" + value.title + "</option>";
                        }
                    });
                    $('#select-delivery').html(htmlOptins);
                }
                $('#cart-location').html(result.location);
            });
        },
        deliveryAction: function(e) {
            var url = "%s";
            $.getJSON(url + $('#select-delivery').val()).done(function(result) {
                if (result.status == 1) {
                    $('#cart-total-shipping').html(result.data.shipping);
                    $('#cart-total-total').html(result.data.total);
                    var htmlOptins = '';
                    $.each(result.data.payment, function( index, value ) {
                        if (value.status==1) {
                            htmlOptins = htmlOptins
                                + "<option value='" + value.path + "'>"  + value.title + "</option>";
                        }
                    });
                    $('#select-payment').html(htmlOptins);
                }
                $('#cart-delivery').html(result.delivery);
                $('#cart-payment').html(result.payment);
            });
        },
        paymentAction: function(e) {
            var url = "%s";
            $.getJSON(url + $('#select-payment').val()).done(function(result) {
                if (result.status == 1) {
                    $('#cart-location').html(result.data.location);
                    $('#cart-delivery').html(result.data.delivery);
                    $('#cart-payment').html(result.data.payment);
                }
            });
        },
        makeOrderAction: function (e) {
            var p = $(e.target).parents('.customer-single'),
                self = this;
            if ($('#' + p.attr('data-id')).hasClass('hidden')) {
                $('#' + p.attr('data-id')).removeClass('hidden');
                $('#' + p.attr('data-button')).removeClass('btn-success').addClass('btn-danger').html("%s");
            } else {
                if (p.attr('data-id') == 'customerFromNew') {
                    $('#' + p.attr('data-id')).addClass('hidden');
                    $('#' + p.attr('data-button')).removeClass('btn-danger').addClass('btn-success').html("%s");
                } else {
                    $('#' + p.attr('data-id')).addClass('hidden');
                    $('#' + p.attr('data-button')).removeClass('btn-danger').addClass('btn-success').html("%s");
                }
            }
        },
    }
    page.init();
})(jQuery)
EOT;
$script = sprintf(
    $script,
    Pi::url($this->url('', array('controller' => 'checkout', 'action' => 'level', 'process' => 'location', 'id' => ''))),
    __('Price : '),
    __('Time : '),
    __('Days'),
    Pi::url($this->url('', array('controller' => 'checkout', 'action' => 'level', 'process' => 'delivery', 'id' => ''))),
    Pi::url($this->url('', array('controller' => 'checkout', 'action' => 'level', 'process' => 'payment', 'id' => ''))),
    __('Cancel'),
    __('Create new address'),
    __('Use it')
);
$this->footScript()->appendScript($script);
?>
<div id="js-order" class="clearfix order-checkout">
    <div class="page-header">
        <h1><?php _e('Checkout'); ?></h1>
    </div>
    <?php if ($cart['type_payment'] == 'installment') { ?>
        <div class="col-md-12">
            <div class="alert alert-info" role="alert">
                <h2><?php _e('Terms of payment'); ?></h2>
                <p><?php echo sprintf(__('You buy products on %s installment by %s payment on each installment and %s per payment'), _number(count($plan) - 2), Pi::api('api', 'order')->viewPrice($this->escape($plan[1]['price'])), Pi::api('api', 'order')->viewPrice($this->escape($plan[0]['price']))); ?></p>
            </div>
        </div>
    <?php } ?>
    <?php if ($cart['can_pay'] == 2) { ?>
        <div class="col-md-12">
            <div class="alert alert-danger"  role="alert">
                <p><?php echo __('One of your select products or services have variable stock, than your payment option is disable, we will review your order and if your selected products or services be in stock we active payment option and send notification for you'); ?></p>
            </div>
        </div>
    <?php } ?>
    <div class="clearfix">
        <div class="col-md-8">
            <?php if (isset($formLogin) && !empty($formLogin)) { ?>
                <div class="alert alert-info" role="alert">
                    <?php _e('If you registered on website before this time and have user account, please login to system and continue ordering, and if you dont have user account here, please fill register new user account and make order form'); ?>
                </div>
                <div class="page-header">
                    <h3><?php _e('Login'); ?></h3>
                </div>
                <?php echo $this->form($formLogin); ?>
                <div class="page-header">
                    <h3><?php _e('Register new user account and make order'); ?></h3>
                </div>
            <?php } ?>
            <?php if (!empty($customers)) { ?>
                <?php foreach ($customers as $customer) { ?>
                    <div class="customer-single table-responsive"
                         data-id="customerFrom<?php echo $customer['id']; ?>"
                         data-button="customerFromButton<?php echo $customer['id']; ?>">
                        <table class="table table-bordered table-condensed table-striped">
                            <tr>
                                <th colspan="2" class="col-md-9">
                                    <ul class="list-inline">
                                        <li><?php echo $this->escape($customer['first_name']); ?></li>
                                        <li><?php echo $this->escape($customer['last_name']); ?></li>
                                        <li>( <?php echo $this->escape($customer['email']); ?> )</li>
                                        <?php if (!empty($customer['company'])) { ?>
                                            <li> - </li>
                                            <li><?php echo $this->escape($customer['company']); ?></li>
                                        <?php } ?>
                                    </ul>
                                </th>
                                <td colspan="1" class="col-md-3 text-center">
                                    <button id="customerFromButton<?php echo $customer['id']; ?>" class="showCustomerFrom btn btn-success btn-sm">
                                        <?php _e('Use it'); ?>
                                    </button>
                                </td>
                            </tr>
                            <?php if (
                                !empty($customer['state']) ||
                                !empty($customer['city']) ||
                                !empty($customer['address1']) ||
                                !empty($customer['zip_code']) ||
                                !empty($customer['phone']) ||
                                !empty($customer['mobile'])) { ?>
                                <tr>
                                    <td class="col-md-6">
                                        <?php if (!empty($customer['address1'])) { ?><p><strong><?php _e('Delivery address'); ?></strong> : <?php echo $this->escape($customer['address1']); ?></p><?php } ?>
                                        <?php if (!empty($customer['address2'])) { ?><p><strong><?php _e('Invoicing address'); ?></strong> : <?php echo $this->escape($customer['address2']); ?></p><?php } ?>
                                        <?php if (!empty($customer['zip_code'])) { ?><p><strong><?php _e('Zip code'); ?></strong> : <?php echo $this->escape($customer['zip_code']); ?></p><?php } ?>
                                    </td>
                                    <td class="col-md-3">
                                        <?php if (!empty($customer['state'])) { ?><p><strong><?php _e('State'); ?></strong> : <?php echo $this->escape($customer['state']); ?></p><?php } ?>
                                        <?php if (!empty($customer['city'])) { ?><p><strong><?php _e('City'); ?></strong> : <?php echo $this->escape($customer['city']); ?></p><?php } ?>
                                    </td>
                                    <td class="col-md-3">
                                        <?php if (!empty($customer['phone'])) { ?><p><strong><?php _e('Phone'); ?></strong> : <?php echo $this->escape($customer['phone']); ?></p><?php } ?>
                                        <?php if (!empty($customer['mobile'])) { ?><p><strong><?php _e('Mobile'); ?></strong> : <?php echo $this->escape($customer['mobile']); ?></p><?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td colspan="3" id="customerFrom<?php echo $customer['id']; ?>" class="hidden">
                                    <div class="clearfix col-md-12">
                                        <?php $key = sprintf('customer-%s', $customer['id']); ?>
                                        <?php echo $this->form($forms[$key]); ?>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                <?php } ?>
                <div class="customer-single well well-sm clearfix" data-id="customerFromNew" data-button="customerFromButtonNew">
                    <div class="page-header row">
                        <div class="col-md-9">
                            <h3><?php _e("Create order with a new address"); ?></h3>
                        </div>
                        <dic class="col-md-3 text-center">
                            <button id="customerFromButtonNew" class="showCustomerFrom btn btn-success btn-sm">
                                <?php _e('Create new address'); ?>
                            </button>
                        </dic>
                    </div>
                    <div id="customerFromNew" class="clearfix col-md-12 <?php if (!$check) { echo 'hidden';} ?>">
                        <?php echo $this->form($forms['new']); ?>
                    </div>
                </div>
            <?php } else { ?>
                <?php echo $this->form($forms['new']); ?>
            <?php } ?>
        </div>
        <div class="col-md-4 cart-product">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php _e('Your products or services'); ?></h3>
                </div>
                <div class="panel-body">
                    <div class="cart-product-list">
                        <?php foreach ($cart['product'] as $product) { ?>
                            <div class="clearfix cart-product-single">
                                <div class="row">
                                    <h5 class="col-xs-12">
                                        <a href="<?php echo $this->escape($product['details']['productUrl']); ?>" target="_blank">
                                            <?php echo $this->escape($product['details']['title']); ?>
                                        </a>
                                    </h5>
                                    <?php if (!empty($product['details']['thumbUrl'])) { ?>
                                        <div class="col-xs-5">
                                            <a href="<?php echo $this->escape($product['details']['productUrl']); ?>" target="_blank">
                                                <img class="img-responsive" src="<?php echo $this->escape($product['details']['thumbUrl']); ?>">
                                            </a>
                                        </div>
                                    <?php } ?>
                                    <div class="col-xs-7">
                                        <strong><?php _e('Price') ?></strong> : <?php echo $this->escape($product['product_price_view']); ?>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                    <p>
                        <strong><?php _e('Total Price ext VAT'); ?></strong> :
                        <?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['product'])); ?>
                    </p>
                    <p>
                        <strong><?php _e('Total Discount'); ?></strong> :
                        <?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['discount'])); ?>
                    </p>
                    <p>
                        <strong><?php _e('Total Shipping'); ?></strong> :
                        <?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['shipping'])); ?>
                    </p>
                    <p>
                        <strong><?php _e('Total Vat'); ?></strong> :
                        <?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['vat'])); ?>
                    </p>
                    <p>
                        <strong><?php _e('Final Price incl. VAT'); ?></strong> :
                        <span class="label label-success">
                            <?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['total'])); ?>
                        </span>
                    </p>
                </div>
            </div>
            <?php if (!empty($config['text_description_checkup'])) { ?>
                <div class="checkout-description">
                    <?php echo $config['text_description_checkup']; ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>