<?php
$this->css(
    [
        $this->assetModule('css/front.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
$this->headMeta('noindex', 'robots');
?>
<div id="address-form" class="clearfix">
    <div class="col-md-12">
        <h3><?php echo $this->escape($title); ?></h3>
        <?php echo $this->form($form, 'modal-simple'); ?>
    </div>
</div>
<script>
    $(document).ready(function () {

        var accountTypeChange = function() {

            var show = $('[name=account_type]:checked').val() == 'company';
            var elements = [
                'company',
                'company_address1',
                'company_address2',
                'company_zip_code',
                'company_city',
                'company_state',
                'company_country',
                'company_id',
                'company_vat'
            ];
            if (show) {
                for (var i = 0; i < elements.length; ++i) {
                    var element = $('[name=' + elements[i] + ']');
                    if (element.closest('.row').find('label i').length) {
                        element.attr('required', true);
                    }
                }
                $('[name=company]').closest('fieldset').show();
            } else {
                for (var i = 0; i < elements.length; ++i) {
                    var element = $('[name=' + elements[i] + ']');
                    element.attr('required', false);
                }
                $('[name=company]').closest('fieldset').hide();
            }
        };

        $('[name=account_type]').change(accountTypeChange);
        accountTypeChange();

        $('.edit-address').click(
            function() { $('form#address').submit(); }
        );
        $('form#address').submit(
            function () {
                $.post(
                    $('form#address').attr('action'),
                    $('form#address').serialize(),
                    function (data) {
                        if (data.status == 1) {
                            window.location.reload();
                        } else {
                            $("#addressModal").find(".modal-body").html(data);
                        }
                    }
                );
                return false;
            }
        )
    });
</script>
