<?php
$this->css(array(
    $this->assetModule('css/front.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->backbone();
$script = <<<'EOT'
(function($) {
    var page = {
        el: $('#js-order'),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            _.bindAll(this);
            this.$('#select-location').on("change",this.locationAction);
            this.$('#select-delivery').on("change",this.deliveryAction);
            this.$('#select-payment').on("change",this.paymentAction);
        },
        locationAction: function(e) {
            var url = "%s";
            $.getJSON(url + $('#select-location').val()).done(function(result) {
                if (result.status == 1) {
                    var htmlOptins = '';
                    $.each(result.data, function( index, value ) {
                        if (value.status==1) {
                            htmlOptins = htmlOptins
                            + "<option value='" + value.delivery + "'>"
                                + value.title + " - "
                                + " %s " + value.price + " - "
                                + " %s " + value.delivery_time  + " %s "
                            + "</option>";
                        } else {
                            htmlOptins = htmlOptins
                            + "<option value='" + value.delivery + "'>" + value.title + "</option>";
                        }
                    });
                    $('#select-delivery').html(htmlOptins);
                }
                $('#cart-location').html(result.location);
            });
        },
        deliveryAction: function(e) {
            var url = "%s";
            $.getJSON(url + $('#select-delivery').val()).done(function(result) {
                if (result.status == 1) {
                    $('#cart-total-shipping').html(result.data.shipping);
                    $('#cart-total-total').html(result.data.total);
                    var htmlOptins = '';
                    $.each(result.data.payment, function( index, value ) {
                        if (value.status==1) {
                            htmlOptins = htmlOptins
                            + "<option value='" + value.path + "'>"  + value.title + "</option>";
                        }
                    });
                    $('#select-payment').html(htmlOptins);
                }
                $('#cart-delivery').html(result.delivery);
                $('#cart-payment').html(result.payment);
            });
        },
        paymentAction: function(e) {
            var url = "%s";
            $.getJSON(url + $('#select-payment').val()).done(function(result) {
                if (result.status == 1) {
                    $('#cart-location').html(result.data.location);
                    $('#cart-delivery').html(result.data.delivery);
                    $('#cart-payment').html(result.data.payment);
                }
            });
        },
    }
    page.init();
})(jQuery)
EOT;
$script = sprintf(
    $script,
    Pi::url($this->url('', array('controller' => 'checkout', 'action' => 'level', 'process' => 'location', 'id' => ''))),
    __('Price : '),
    __('Time : '),
    __('Days'),
    Pi::url($this->url('', array('controller' => 'checkout', 'action' => 'level', 'process' => 'delivery', 'id' => ''))),
    Pi::url($this->url('', array('controller' => 'checkout', 'action' => 'level', 'process' => 'payment', 'id' => '')))
);
$this->footScript()->appendScript($script);
?>
    <div id="js-order" class="clearfix row order-checkout">
        <?php if (!empty($customers)) { ?>
            <div class="page-header">
                <h1><?php _e('Checkout'); ?></h1>
            </div>
        <?php } ?>
        <?php if ($cart['type_payment'] == 'installment') { ?>
        <div class="col-md-12">
            <?php } else { ?>
            <div class="col-md-8">
                <?php } ?>
                <?php if (!empty($customers)) { ?>
                    <?php if ($cart['type_payment'] == 'installment') { ?>
                        <div class="alert alert-info" role="alert">
                            <h2><?php _e('Terms of payment'); ?></h2>

                            <p><?php echo sprintf(__('You buy products on %s installment by %s payment on each installment and %s per payment'), _number(count($plan) - 2), Pi::api('api', 'order')->viewPrice($this->escape($plan[1]['price'])), Pi::api('api', 'order')->viewPrice($this->escape($plan[0]['price']))); ?></p>
                        </div>
                    <?php } ?>
                    <div class="well"><?php _e('Select your invoicing address for your order'); ?></div>
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="false">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="new-address">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse-new-address"
                                       aria-expanded="false" aria-controls="collapse-new-address">
                                        <?php _e('Add a new invoicing address'); ?>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse-new-address" class="panel-collapse collapse" role="tabpanel"
                                 aria-labelledby="new-address">
                                <div class="panel-body">
                                    <?php echo $this->form($forms['new']); ?>
                                </div>
                            </div>
                        </div>
                        <?php $i = 1; ?>
                        <?php foreach ($customers as $customer) { ?>
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab"
                                     id="customer-<?php echo $this->escape($customer['id']); ?>">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#accordion"
                                           href="#collapse-customer-<?php echo $this->escape($customer['id']); ?>"
                                           aria-expanded="<?php if ($i == 1) {echo 'true';} else {echo 'false';} ?>"
                                           aria-controls="collapse-customer-<?php echo $this->escape($customer['id']); ?>">
                                            <?php echo $this->escape($customer['first_name']); ?>
                                            <?php echo $this->escape($customer['last_name']); ?> :
                                            <?php echo $this->escape($customer['address1']); ?>
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapse-customer-<?php echo $this->escape($customer['id']); ?>"
                                     class="panel-collapse collapse<?php if ($i == 1) {echo ' in';} ?>" role="tabpanel"
                                     aria-labelledby="customer-<?php echo $this->escape($customer['id']); ?>">
                                    <div class="panel-body">
                                        <?php $key = sprintf('customer-%s', $customer['id']); ?>
                                        <?php echo $this->form($forms[$key]); ?>
                                    </div>
                                </div>
                            </div>
                            <?php $i++; ?>
                        <?php } ?>
                    </div>
                <?php } else { ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1 class="panel-title"><?php _e('Checkout'); ?></h1>
                        </div>
                        <div class="panel-body">
                            <?php if ($cart['type_payment'] == 'installment') { ?>
                                <div class="alert alert-info" role="alert">
                                    <h2><?php _e('Terms of payment'); ?></h2>

                                    <p><?php echo sprintf(__('You buy products on %s installment by %s payment on each installment and %s per payment'), _number(count($plan) - 2), Pi::api('api', 'order')->viewPrice($this->escape($plan[1]['price'])), Pi::api('api', 'order')->viewPrice($this->escape($plan[0]['price']))); ?></p>
                                </div>
                            <?php } ?>
                            <?php echo $this->form($forms['new']); ?>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <?php if ($cart['type_payment'] != 'installment') { ?>
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h2 class="panel-title"><?php _e('Pre Invoice'); ?></h2>
                        </div>
                        <div class="panel-body">
                            <p><strong><?php _e('Total Price'); ?></strong> : <span
                                    id="cart-total-price"><?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['product'])); ?></span>
                            </p>
                            <p><strong><?php _e('Total Discount'); ?></strong> : <span
                                    id="cart-total-discount"><?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['discount'])); ?></span>
                            </p>
                            <p><strong><?php _e('Total Shipping'); ?></strong> : <span
                                    id="cart-total-shipping"><?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['shipping'])); ?></span>
                            </p>
                            <p><strong><?php _e('Total Vat'); ?></strong> : <span
                                    id="cart-total-vat"><?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['vat'])); ?></span>
                            </p>
                            <p><strong><?php _e('Final Price'); ?></strong> : <span id="cart-total-total"
                                                                                    class="label label-success"><?php echo Pi::api('api', 'order')->viewPrice($this->escape($price['total'])); ?></span>
                            </p>
                            <?php if ($config['order_location_delivery'] && $cart['type_commodity'] == 'product') { ?>
                            <p><strong> <?php _e('Location'); ?></strong> : <span id="cart-location"></span></p>
                            <p><strong><?php _e('Delivery'); ?></strong> : <span id="cart-delivery"></span></p>
                            <p><strong><?php _e('Payment'); ?></strong> : <span id="cart-payment"></span></p>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
<?php if (isset($error) && !empty($error)) { ?>
<pre><?php print_r($error); ?></pre>
<?php } ?>