<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix row user-section-wrapper">
    <div class="col-md-3">
        <?php $sideActive = 'credit'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?php _e('Credit information and history'); ?></h1>
        </div>
        <div class="well">
            <div class="clearfix">
                <div class="col-md-6">
                    <p><strong><?php _e('Last update time'); ?></strong> : <span><?php echo $this->escape($credit['time_update_view']); ?></span></p>
                    <p>
                        <strong><?php _e('Name'); ?></strong> :
                        <?php if (!empty($user['first_name']) && !empty($user['last_name'])) { ?>
                            <span><?php echo $this->escape($user['first_name']); ?> <?php echo $this->escape($user['last_name']); ?></span>
                        <?php } else { ?>
                            <span><?php echo $this->escape($user['name']); ?></span>
                        <?php } ?>
                    </p>
                    <p><strong><?php _e('Email'); ?></strong> : <span><?php echo $this->escape($user['email']); ?></span></p>
                </div>
                <div class="col-md-6">
                    <p><strong><?php _e('Total credit amount'); ?></strong> : <span class="badge badge-success"><?php echo $this->escape($credit['amount_view']); ?></span></p>
                    <?php if ($config['credit_type'] == 'module') { ?>
                        <?php foreach ($credit['amount_detail_view'] as $amountDetail) { ?>
                            <p><strong><?php echo $amountDetail['module_title']; ?></strong> : <?php echo $amountDetail['amount_view']; ?></p>
                        <?php } ?>
                    <?php } ?>
                </div>
            </div>
        </div>
        <h3><?php _e('List of historys'); ?></h3>
        <?php if (!empty($list)) { ?>
            <table class="table table-striped table-bordered table-sm">
                <tr class="small">
                    <th><?php _e('Time create'); ?></th>
                    <th><?php _e('Description'); ?></th>
                    <th><?php _e('Old amount'); ?></th>
                    <th><?php _e('Debtor / Creditor'); ?></th>
                    <th><?php _e('Remained'); ?></th>
                    <th><?php _e('Action'); ?></th>
                </tr>
                <?php foreach ($list as $history) { ?>
                    <?php if ($history['status'] == 1) {
                        if ($history['status_fluctuation'] == 'increase') {
                            $tableClass = 'success';
                        } elseif ($history['status_fluctuation'] == 'decrease') {
                            $tableClass = 'danger';
                        }
                    } elseif ($history['status'] == 2) {
                        $tableClass = 'info';
                    } elseif ($history['status'] == 0) {
                        $tableClass = 'warning';
                    } ?>
                    <tr class="<?php echo $tableClass; ?>">
                        <td><?php echo $this->escape($history['time_create_view']); ?></td>
                        <td><?php echo $this->escape($history['message_user']); ?></td>
                        <td><?php echo $this->escape($history['amount_old_view']); ?></td>
                        <td><?php echo $this->escape($history['amount_view']); ?></td>
                        <td><?php echo $this->escape($history['amount_new_view']); ?></td>
                        <td>
                            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal"
                                    data-target="#history-modal-<?php echo $this->escape($history['id']); ?>">
                                <?php _e('Show details'); ?>
                            </button>
                            <div class="modal fade" id="history-modal-<?php echo $this->escape($history['id']); ?>" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title"><?php _e('history details'); ?></h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span></button>
                                        </div>
                                        <div class="modal-body">
                                            <table class="table table-striped table-bordered table-sm">
                                                <tr>
                                                    <td><strong><?php _e('Name'); ?></strong></td>
                                                    <td>
                                                        <?php if (!empty($user['first_name']) && !empty($user['last_name'])) { ?>
                                                            <span><?php echo $this->escape($user['first_name']); ?> <?php echo $this->escape($user['last_name']); ?></span>
                                                        <?php } else { ?>
                                                            <span><?php echo $this->escape($user['name']); ?></span>
                                                        <?php } ?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('Identity'); ?></strong></td>
                                                    <td><?php echo $this->escape($user['identity']); ?></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('Email'); ?></strong></td>
                                                    <td><?php echo $this->escape($user['email']); ?></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('Amount old credit'); ?></strong></td>
                                                    <td><?php echo $this->escape($history['amount_old_view']); ?></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('Amount change credit'); ?></strong></td>
                                                    <td><?php echo $this->escape($history['amount_view']); ?></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('Fluctuation status'); ?></strong></td>
                                                    <td><span class="<?php echo $history['status_fluctuation_class']; ?>"><?php echo $this->escape($history['status_fluctuation_view']); ?></span></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('Amount new credit'); ?></strong></td>
                                                    <td><?php echo $this->escape($history['amount_new_view']); ?></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('Time create'); ?></strong></td>
                                                    <td><?php echo $this->escape($history['time_create_view']); ?></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('User message'); ?></strong></td>
                                                    <td><?php echo $history['message_user']; ?></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('Action status'); ?></strong></td>
                                                    <td><?php echo $this->escape($history['status_action_view']); ?></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><?php _e('Ip'); ?></strong></td>
                                                    <td><?php echo $this->escape($history['ip']); ?></td>
                                                </tr>
                                            </table>
                                        </div>
                                        <div class="modal-footer">
                                            <?php if ($history['orderLink']) { ?>
                                                <a class="btn btn-primary" title="<?php _e('View order'); ?>" href="<?php echo $history['orderLink']; ?>" target="_blank"><?php _e('View order'); ?></a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </table>
            <div class="paginator">
                <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
            </div>
        <?php } else { ?>
            <div class="alert alert-warning" role="alert"><?php _e('No history save yet'); ?></div>
        <?php } ?>
    </div>
</div>