<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
	<h1><?php echo sprintf(__('Order %s details'), $order['code']); ?></h1>
	<div class="well">
		<div class="clearfix">
			<div class="col-md-6">
				<?php if (!empty($order['first_name']) && !empty($order['last_name'])) { ?>
				<p><strong><?php _e('Name'); ?></strong> : <span><?php echo $this->escape($order['first_name']); ?> <?php echo $this->escape($order['last_name']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['id_number'])) { ?>
				<p><strong><?php _e('ID number'); ?></strong> : <span><?php echo $this->escape($order['id_number']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['address1'])) { ?>
				<p><strong><?php _e('Address 1'); ?></strong> : <span><?php echo $this->escape($order['address1']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['address2'])) { ?>
				<p><strong><?php _e('Address 2'); ?></strong> : <span><?php echo $this->escape($order['address2']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['city'])) { ?>
				<p><strong><?php _e('City'); ?></strong> : <span><?php echo $this->escape($order['city']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['state'])) { ?>
				<p><strong><?php _e('State'); ?></strong> : <span><?php echo $this->escape($order['state']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['country'])) { ?>
				<p><strong><?php _e('Country'); ?></strong> : <span><?php echo $this->escape($order['country']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['zip'])) { ?>
				<p><strong><?php _e('Zip code'); ?></strong> : <span><?php echo $this->escape($order['zip']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['email'])) { ?>
				<p><strong><?php _e('Email'); ?></strong> : <span><?php echo $this->escape($order['email']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['phone'])) { ?>
				<p><strong><?php _e('Phone'); ?></strong> : <span><?php echo $this->escape($order['phone']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['mobile'])) { ?>
				<p><strong><?php _e('Mobile'); ?></strong> : <span><?php echo $this->escape($order['mobile']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['company'])) { ?>
				<p><strong><?php _e('Company'); ?></strong> : <span><?php echo $this->escape($order['company']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['company_id'])) { ?>
				<p><strong><?php _e('Company ID'); ?></strong> : <span><?php echo $this->escape($order['company_id']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['company_vat'])) { ?>
				<p><strong><?php _e('Company VAT'); ?></strong> : <span><?php echo $this->escape($order['company_vat']); ?></span></p>
				<?php } ?>
			</div>
			<div class="col-md-6">
				<p><strong><?php _e('Order status'); ?></strong> : <span><?php echo $this->escape($order['orderTitle']); ?> </span></p>
				<p><strong><?php _e('Payment status'); ?></strong> : <span><?php echo $this->escape($order['paymentTitle']); ?> </span></p>
				<p><strong><?php _e('Delivery status'); ?></strong> : <span><?php echo $this->escape($order['deliveryTitle']); ?> </span></p>
				<p><strong><?php _e('Time create'); ?></strong> : <span><?php echo $this->escape($order['time_create_view']); ?> </span></p>
				<p><strong><?php _e('Time payment'); ?></strong> : <span><?php echo $this->escape($order['time_payment_view']); ?> </span></p>
				<p><strong><?php _e('Time delivery'); ?></strong> : <span><?php echo $this->escape($order['time_delivery_view']); ?> </span></p>
				<p><strong><?php _e('Time finish'); ?></strong> : <span><?php echo $this->escape($order['time_finish_view']); ?> </span></p>
				<p><strong><?php _e('Time start'); ?></strong> : <span><?php echo $this->escape($order['time_start_view']); ?> </span></p>
				<p><strong><?php _e('Time end'); ?></strong> : <span><?php echo $this->escape($order['time_end_view']); ?> </span></p>
				<p><strong><?php _e('Gateway'); ?></strong> : <span><?php echo $this->escape($order['gateway']); ?> </span></p>
				<?php if ($order['product_price'] > 0) { ?>
				<p><strong><?php _e('Product price'); ?></strong> : <span><?php echo $this->escape($order['product_price_view']); ?></span></p>
				<?php } ?>
				<?php if ($order['shipping_price'] > 0) { ?>
				<p><strong><?php _e('Shipping price'); ?></strong> : <span><?php echo $this->escape($order['shipping_price_view']); ?></span></p>
				<?php } ?>
				<?php if ($order['packing_price'] > 0) { ?>
				<p><strong><?php _e('Packing price'); ?></strong> : <span><?php echo $this->escape($order['packing_price_view']); ?></span></p>
				<?php } ?>
				<?php if ($order['vat_price'] > 0) { ?>
				<p><strong><?php _e('Vat price'); ?></strong> : <span><?php echo $this->escape($order['vat_price_view']); ?></span></p>
				<?php } ?>
				<?php if ($order['total_price'] > 0) { ?>
				<p><strong><?php _e('Total price'); ?></strong> : <span><?php echo $this->escape($order['total_price_view']); ?></span></p>
				<?php } ?>
				<?php if ($order['paid_price'] > 0) { ?>
				<p><strong><?php _e('Paid price'); ?></strong> : <span><?php echo $this->escape($order['paid_price_view']); ?></span></p>
				<?php } ?>
			</div>
		</div>
	</div>	
	<h3><?php _e('This order products or services list'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('Product'); ?></th>
			<th><?php _e('Number'); ?></th>
			<th><?php _e('Price'); ?></th>
			<th><?php _e('Shipping'); ?></th>
			<th><?php _e('Packing'); ?></th>
			<th><?php _e('Vat'); ?></th>
			<th><?php _e('Total'); ?></th>
		</tr>
		<?php foreach($order['products'] as $product) { ?>
		<tr>
			<td>
				<a title="<?php echo $this->escape($product['details']['title']); ?>" href="<?php echo $this->escape($product['details']['productUrl']); ?>">
					<img width="32" height="32" src="<?php echo $this->escape($product['details']['thumbUrl']); ?>" alt="<?php echo $this->escape($product['details']['title']); ?>">
					<?php echo $this->escape($product['details']['title']); ?>
				</a>
			</td>
			<td><?php echo _number($this->escape($product['number'])); ?></td>
			<td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['product_price'])); ?></td>
			<td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['shipping_price'])); ?></td>
			<td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['packing_price'])); ?></td>
			<td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['vat_price'])); ?></td>
			<td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['total_price'])); ?></td>
		</tr>
		<?php } ?>
	</table>
	<h3><?php _e('This order invoices list'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Price'); ?></th>
			<th><?php _e('Time Create'); ?></th>
			<th><?php _e('Due date'); ?></th>
			<th><?php _e('Time pay'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($order['invoices'] as $invoice) { ?>
		<?php
		if($invoice['status'] == 1) {
			$labelIdClass = 'label-success';	
		} elseif($invoice['status'] == 2) {
			$labelIdClass = 'label-warning';	
		} elseif($invoice['status'] == 3) {
			$labelIdClass = 'label-danger';	
		}
		// Set row class
		$rowClass = '';
		if ($invoice['time_duedate'] < strtotime("-1 day")) {
			$rowClass = ' class="danger"';
		} elseif ($invoice['time_duedate'] < strtotime("+1 day")) {
            $rowClass = ' class="warning"';
		}
		?>
		<tr<?php echo $rowClass; ?>>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo _number($this->escape($invoice['id'])); ?></span></td>
			<td><?php echo $this->escape($invoice['total_price_view']); ?></td>
			<td><?php echo $this->escape($invoice['time_create_view']); ?></td>
			<td><?php echo $this->escape($invoice['time_duedate_view']); ?></td>
			<td><?php echo $this->escape($invoice['time_payment_view']); ?></td>
			<td>
				<a class="btn btn-primary" title="<?php _e('View / Pay'); ?>" href="<?php echo $this->url('', array('controller' => 'invoice', 'id' => $invoice['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('View / Pay'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
	<p>
		<span class="label label-success"><?php _e('Paid'); ?></span>
		<span class="label label-warning"><?php _e('Unpaid'); ?></span>
		<span class="label label-danger"><?php _e('Canceled'); ?></span>
	</p>
</div>