<?php
$this->css($this->assetModule('css/front.css'));
$this->jquery();
$script1
    = <<<'EOT'
    var delay = 15000;
    setTimeout(function(){ window.location = '%s'; }, delay);
EOT;
$script1 = sprintf($script1, $url);
$this->footScript()->appendScript($script1);
$script2
    = <<<'EOT'
    var count=15;
    var counter=setInterval(timer, 1000);
    function timer()
    {
        count=count-1;
        if (count <= 0)
        {
            clearInterval(counter);
            return;
        }
        document.getElementById("timer").innerHTML=count + " secs";
    }
EOT;
$this->footScript()->appendScript($script2);
?>
<div class="clearfix finishBox">
    <div class="text-center finishLogo">
        <img class="img-fluid" src="<?php echo $this->logo(); ?>" alt="">
    </div>
    <div class="alert alert-success" role="alert">
        <h1><?php _e('Thanks you for your payment !'); ?></h1>

        <p><?php echo sprintf(
                __('Your payment ends successfully, we just need %s to obtain payment confirmation.'), '<strong><span id="timer"></span></strong>'
            ); ?></p>

        <p><?php _e('Once received, youll be redirected automatically to your dashboard, and will be able to create your item !'); ?></p>

        <?php if ($paypal) { ?>
            <p><?php _e(
                    'You will additionally receive a confirmation mail from Paypal, telling that your transaction has been completed, and giving you a receipt for your purchase. You may log into your account at www.paypal.com to view details of this transaction.'
                ); ?></p>
        <?php } ?>

        <p><?php _e('Please wait !'); ?></p>

    </div>
</div>