<?php
$this->css($this->assetModule('css/front.css'));
$this->jquery();
$script1 = <<<'EOT'
    var delay = 15000;
    setTimeout(function(){ window.location = '%s'; }, delay);
EOT;
$script1 = sprintf($script1, $url);
$this->footScript()->appendScript($script1);
$script2 = <<<'EOT'
    var count=15;
    var counter=setInterval(timer, 1000);
    function timer()
    {
        count=count-1;
        if (count <= 0)
        {
            clearInterval(counter);
            return;
        }
        document.getElementById("timer").innerHTML=count + " secs";
    }
EOT;
$this->footScript()->appendScript($script2);
?>
<div class="clearfix finishBox">
    <div class="text-center finishLogo">
        <img class="img-responsive" src="<?php echo $this->logo(); ?>" alt="">
    </div>
    <div class="alert alert-success" role="alert">
        <h1><?php _e('Thanks !'); ?></h1>

        <p><?php echo sprintf(__('Your payment ends successfully, we need %s to obtain payment confirmation.'), '<strong><span id="timer"></span></strong>'); ?></p>

        <p><?php _e('Once received, youll be redirected automatically to your dashboard, and will be able to create your item !'); ?></p>

        <p><?php _e('Please wait !'); ?></p>
        
        <?php if ($paypal) { ?> 
            <p><?php _e('Nous vous remercions de votre paiement. Votre transaction est terminée et vous allez recevoir par email un avis accusant réception de votre achat. Vous pouvez vous connecter à votre compte sur www.paypal.com pour consulter les détails de cette transaction.'); ?></p>    
        <?php } ?> 
    </div>
</div>