<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
	<div class="well">
		<div class="clearfix">
			<div class="col-md-6">
				<p><strong><?php _e('Status'); ?></strong> : 
				<?php if ($invoice['status'] == 1) { ?>
					<span class="label label-success"><?php _e('Paid'); ?><span>
				<?php } elseif ($invoice['status'] == 2) { ?>
					<span class="label label-warning"><?php _e('Unpaid'); ?><span>
				<?php } else { ?>
					<span class="label label-danger"><?php _e('Canceled'); ?><span>
				<?php } ?>
				<?php if (!empty($order['first_name']) && !empty($order['last_name'])) { ?>
				<p><strong><?php _e('Name'); ?></strong> : <span><?php echo $this->escape($order['first_name']); ?> <?php echo $this->escape($order['last_name']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['id_number'])) { ?>
				<p><strong><?php _e('ID number'); ?></strong> : <span><?php echo $this->escape($order['id_number']); ?></span></p>
				<?php } ?>
				<p><strong><?php _e('Order'); ?></strong> : <span><?php echo $this->escape($order['code']); ?></span></p>
			</div>
			<div class="col-md-6">
				<?php if (!empty($order['phone'])) { ?>
				<p><strong><?php _e('Phone'); ?></strong> : <span><?php echo $this->escape($order['phone']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['mobile'])) { ?>
				<p><strong><?php _e('Mobile'); ?></strong> : <span><?php echo $this->escape($order['mobile']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['email'])) { ?>
				<p><strong><?php _e('Email'); ?></strong> : <span><?php echo $this->escape($order['email']); ?></span></p>
				<?php } ?>
				<?php if (!empty($order['address1'])) { ?>
				<p>
					<strong><?php _e('Delivery address'); ?></strong> : <span><?php echo $this->escape($order['address1']); ?></span>
					<?php if (!empty($order['address2'])) { ?>
					<span><?php echo $this->escape($order['address2']); ?></span>
					<?php } ?>
				</p>
				<?php } ?>
			</div>
		</div>
		<h3><?php _e('This order products or services list'); ?></h3>
		<table class="table table-striped table-bordered table-condensed small">
			<tr>
				<th><?php _e('Product'); ?></th>
				<th><?php _e('Number'); ?></th>
				<th><?php _e('Price'); ?></th>
				<th><?php _e('Shipping'); ?></th>
				<!-- <th class="col-md-1"><?php _e('Packing'); ?></th> -->
				<th><?php _e('Vat'); ?></th>
				<th><?php _e('Total'); ?></th>
			</tr>
			<?php foreach($order['products'] as $product) { ?>
			<tr>
				<td>
					<a title="<?php echo $this->escape($product['details']['title']); ?>" href="<?php echo $this->escape($product['details']['productUrl']); ?>">
						<img width="32" height="32" src="<?php echo $this->escape($product['details']['thumbUrl']); ?>" alt="<?php echo $this->escape($product['details']['title']); ?>">
						<?php echo $this->escape($product['details']['title']); ?>
					</a>
				</td>
				<td><?php echo _number($this->escape($product['number'])); ?></td>
				<td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['product_price'])); ?></td>
				<td>
					<?php if ($product['shipping_price'] > 0) { ?>
					<?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['shipping_price'])); ?>
					<?php } ?>
				</td>
				<!-- <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['packing_price'])); ?></td> -->
				<td>
					<?php if ($product['vat_price'] > 0) { ?>
					<?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['vat_price'])); ?>
					<?php } ?>
				</td>
				<td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['total_price'])); ?></td>
			</tr>
			<?php } ?>
		</table>
		<?php if ($order['type_payment'] == 'installment') { ?>
		<!-- <h3><?php _e('Total order price'); ?></h3>
		<table class="table table-striped table-bordered table-condensed small">
			<tr>
				<th class="col-md-4"><?php _e('Title'); ?></th>
				<th class="col-md-8"><?php _e('Amount'); ?></th>
			</tr>
			<tr>
				<td class="col-md-4"><?php _e('Product price'); ?></td>
				<td class="col-md-8">
					<?php echo $this->escape($order['product_price_view']); ?>
				</td>
			</tr>
			<tr>
				<td class="col-md-4"><?php _e('Shipping'); ?></td>
				<td class="col-md-8">
					<?php echo $this->escape($order['shipping_price_view']); ?>
				</td>
			</tr>
			<tr>
				<td class="col-md-4"><?php _e('Vat'); ?></td>
				<td class="col-md-8">
					<?php echo $this->escape($order['vat_price_view']); ?>
				</td>
			</tr>
			<tr>
				<td class="col-md-4"><?php _e('Total'); ?></td>
				<td class="col-md-8">
					<strong><?php echo $this->escape($order['total_price_view']); ?></strong>
				</td>
			</tr>
		</table> -->
		<div class="alert alert-success" role="alert">
			<h2><?php _e('Payment price'); ?> : <strong><?php echo $this->escape($invoice['total_price_view']); ?></strong></h2>
		</div>
		<?php } else { ?>
		<h3><?php _e('Total invoice price'); ?></h3>
		<table class="table table-striped table-bordered table-condensed">
			<tr>
				<th class="col-md-4"><?php _e('Title'); ?></th>
				<th class="col-md-8"><?php _e('Amount'); ?></th>
			</tr>
			<tr>
				<td class="col-md-4"><?php _e('Product price'); ?></td>
				<td class="col-md-8">
				<?php if ($invoice['product_price'] > 0) { ?>
				<?php echo $this->escape($invoice['product_price_view']); ?>
				<?php } ?>
				</td>
			</tr>
			<tr>
				<td class="col-md-4"><?php _e('Shipping'); ?></td>
				<td class="col-md-8">
				<?php if ($invoice['shipping_price'] > 0) { ?>
				<?php echo $this->escape($invoice['shipping_price_view']); ?>
				<?php } ?>
				</td>
			</tr>
			<tr>
				<td class="col-md-4"><?php _e('Vat'); ?></td>
				<td class="col-md-8">
				<?php if ($invoice['vat_price'] > 0) { ?>
				<?php echo $this->escape($invoice['vat_price_view']); ?>
				<?php } ?>
				</td>
			</tr>
			<tr>
				<td class="col-md-4"><?php _e('Total'); ?></td>
				<td class="col-md-8">
				<?php if ($invoice['total_price'] > 0) { ?>
				<strong><?php echo $this->escape($invoice['total_price_view']); ?></strong>
				<?php } ?>
				</td>
			</tr>
		</table>
		<?php } ?>
	</div>	
	<?php if ($invoice['status'] == 2) {  ?>
	<div class="clearfix">
		<div class="col-md-6">
		<?php if ($invoice['status'] == 2) {  ?>
			<a class="btn btn-success btn-lg" title="<?php _e('Pay'); ?>" href="<?php echo $this->escape($invoice['pay_url']); ?>"><i class="fa fa-external-link"></i> <?php _e('Pay'); ?></a>
		<?php } ?>
		</div>
		<div class="col-md-6 text-right">
			<a class="btn btn-primary btn-sm" title="<?php _e('Back to order'); ?>" href="<?php echo $this->escape($invoice['order_url']); ?>"><?php _e('Back to order'); ?></a>
		</div>
	</div>
	<?php } ?>
</div>