<?php
// Load bootstrap
$this->css(
    Pi::url('public/vendor/bootstrap/css/bootstrap.min.css'),
    array('media' => "all")
);
// Load localization css
$this->css(
    $this->assetLocale('locale.css'),
    array('media' => "all")
);
// locad print css
$this->css(
    $this->assetModule('css/print.css'),
    array('media' => "all")
);
// Get language
$locale = 'en';
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="utf-8">
</head>
<!--  onload="window.print()" -->
<body onload="window.print()" id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
<div id="print">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 print-title">
                <?php _e('Print invoice'); ?>
            </div>
            <div class="col-xs-12">
                <h1><?php echo sprintf(__('Invoice %s'), $this->escape($invoice['code'])); ?></h1>
                <div class="well">
                    <div class="clearfix">
                        <div class="col-md-6">
                            <div class="text-left">
                                <?php if (!empty($config['order_sellerlogo'])) { ?>
                                    <img src="<?php echo $config['order_sellerlogo']; ?>" alt="">
                                <?php } else { ?>
                                    <img src="<?php echo $this->logo(); ?>" alt="">
                                <?php } ?>
                                <br />
                            </div>
                            <?php if (!empty($config['order_sellerinfo'])) { ?>
                                <div class="clearfix">
                                    <?php echo $config['order_sellerinfo']; ?>
                                    <br />
                                </div>
                            <?php } ?>
                            <p><strong><?php _e('Order date'); ?></strong> : <span><?php echo $this->escape($order['time_create_view']); ?></span></p>
                            <p><strong><?php _e('Invoice date'); ?></strong> : <span><?php echo $this->escape($invoice['time_create_view']); ?></span></p>
                        </div>
                        <div class="col-md-6">
                            <p><strong><?php _e('Order'); ?></strong> : <span><?php echo $this->escape($order['code']); ?></span></p>
                            <p><strong><?php _e('Status'); ?></strong> :
                                <?php if ($invoice['status'] == 1) { ?>
                                    <span class="label label-success"><?php _e('Paid'); ?></span>
                                    <span><?php _e('On'); ?> : <?php echo $this->escape($invoice['time_payment_view']) ?></span>
                                <?php } elseif ($invoice['status'] == 2) { ?>
                                    <span class="label label-warning"><?php _e('Unpaid'); ?></span>
                                    <span><?php _e('Due date'); ?> : <?php echo $this->escape($invoice['time_duedate_view']) ?></span>
                                <?php } else { ?>
                                    <span class="label label-danger"><?php _e('Canceled'); ?></span>
                                    <span><?php _e('On'); ?> : <?php echo $this->escape($invoice['time_cancel_view']) ?></span>
                                <?php } ?>
                            </p>
                            <?php if (!empty($order['first_name']) && !empty($order['last_name'])) { ?>
                                <p><strong><?php _e('Name'); ?></strong> : <span><?php echo $this->escape($order['first_name']); ?> <?php echo $this->escape($order['last_name']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($order['id_number'])) { ?>
                                <p><strong><?php _e('ID number'); ?></strong> : <span><?php echo $this->escape($order['id_number']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($order['phone'])) { ?>
                                <p><strong><?php _e('Phone'); ?></strong> : <span><?php echo $this->escape($order['phone']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($order['mobile'])) { ?>
                                <p><strong><?php _e('Mobile'); ?></strong> : <span><?php echo $this->escape($order['mobile']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($order['email'])) { ?>
                                <p><strong><?php _e('Email'); ?></strong> : <span><?php echo $this->escape($order['email']); ?></span></p>
                            <?php } ?>
                            <?php if (!empty($order['address1'])) { ?>
                                <p>
                                    <strong><?php _e('Address'); ?></strong> : <span><?php echo $this->escape($order['address1']); ?></span>
                                    <?php if (!empty($order['address2'])) { ?>
                                        <span><?php echo $this->escape($order['address2']); ?></span>
                                    <?php } ?>
                                </p>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <h3><?php _e('This order products or services list'); ?></h3>
                <table class="table table-striped table-bordered table-condensed small">
                    <tr>
                        <th><?php _e('Row'); ?></th>
                        <th><?php _e('Product'); ?></th>
                        <th><?php _e('Number'); ?></th>
                        <th><?php _e('Price'); ?></th>
                        <th><?php _e('Shipping'); ?></th>
                        <!-- <th class="col-md-1"><?php _e('Packing'); ?></th> -->
                        <th><?php _e('Vat'); ?></th>
                        <th><?php _e('Total'); ?></th>
                    </tr>
                    <?php $i = 1; ?>
                    <?php foreach($order['products'] as $product) { ?>
                        <tr>
                            <td><?php echo _number($i++); ?></td>
                            <td>
                                <div class="productItem">
                                    <?php if (isset($product['details']['thumbUrl']) && !empty($product['details']['thumbUrl'])) { ?>
                                        <img width="32" height="32" src="<?php echo $this->escape($product['details']['thumbUrl']); ?>" alt="<?php echo $this->escape($product['details']['title']); ?>">
                                    <?php } ?>
                                    <?php echo $this->escape($product['details']['title']); ?>
                                </div>
                                <?php if (isset($product['extra']['product']) && !empty($product['extra']['product'])) { ?>
                                    <?php foreach ($product['extra']['product'] as $extraProduct) { ?>
                                        <div class="productItem">
                                            <span><?php echo $this->escape($extraProduct['title']); ?></span> : <strong><?php echo $this->escape($extraProduct['value']); ?></strong>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                            </td>
                            <td><?php echo _number($this->escape($product['number'])); ?></td>
                            <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['product_price'])); ?></td>
                            <td>
                                <?php if ($product['shipping_price'] > 0) { ?>
                                    <?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['shipping_price'])); ?>
                                <?php } ?>
                            </td>
                            <!-- <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['packing_price'])); ?></td> -->
                            <td>
                                <?php if ($product['vat_price'] > 0) { ?>
                                    <?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['vat_price'])); ?>
                                <?php } ?>
                            </td>
                            <td><?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['total_price'])); ?></td>
                        </tr>
                    <?php } ?>
                </table>
                <?php if ($order['type_payment'] == 'installment') { ?>
                    <div class="alert alert-success" role="alert">
                        <h2><?php _e('Payment price'); ?> : <strong><?php echo $this->escape($invoice['total_price_view']); ?></strong></h2>
                    </div>
                <?php } else { ?>
                    <h3><?php _e('Total invoice price'); ?></h3>
                    <table class="table table-striped table-bordered table-condensed">
                        <tr>
                            <th class="col-md-4"><?php _e('Title'); ?></th>
                            <th class="col-md-8"><?php _e('Amount'); ?></th>
                        </tr>
                        <tr>
                            <td class="col-md-4"><?php _e('Product price'); ?></td>
                            <td class="col-md-8">
                                <?php if ($invoice['product_price'] > 0) { ?>
                                    <?php echo $this->escape($invoice['product_price_view']); ?>
                                <?php } ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="col-md-4"><?php _e('Shipping'); ?></td>
                            <td class="col-md-8">
                                <?php if ($invoice['shipping_price'] > 0) { ?>
                                    <?php echo $this->escape($invoice['shipping_price_view']); ?>
                                <?php } ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="col-md-4"><?php _e('Vat'); ?></td>
                            <td class="col-md-8">
                                <?php if ($invoice['vat_price'] > 0) { ?>
                                    <?php echo $this->escape($invoice['vat_price_view']); ?>
                                <?php } ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="col-md-4"><?php _e('Total'); ?></td>
                            <td class="col-md-8">
                                <?php if ($invoice['total_price'] > 0) { ?>
                                    <strong><?php echo $this->escape($invoice['total_price_view']); ?></strong>
                                <?php } ?>
                            </td>
                        </tr>
                    </table>
                <?php } ?>
            </div>
        </div>
    </div>
</body>
</html>