<?php if (!empty($form)) { ?>
    <style>
        .order-message {
            background: #f5f5f5;
            border: 1px solid #ddd;
            margin: 50px auto;
            padding: 15px;
            text-align: center;
        }
    </style>
    <div class="order-message">
        <?php _e("You'll be redirected in few seconds to gateway Checkout Page"); ?>
    </div>
    <?php echo $this->form($form); ?>
    <script>
        function formAutoSubmit() {
            var frm = document.getElementById("pay");
            frm.submit();
        }
        window.onload = window.setTimeout(formAutoSubmit, 100);
    </script>
<?php } ?>
