<?php $invoice = current($order['invoices']); ?>
<style>
    * {color:#525251}
    
    .align-right {text-align:right; right:5mm}
    .align-center {text-align:center}
    .align-justify {text-align:justify}
    .clearfix {clear:both}
    
    hr {margin:0; height:1px; color:#d6dce1;}
    table {width:100%}
    table.withborder td,
    table.withborder {border:1px solid #e3e3e3}
    th, td {padding:10px 5px}
    
    .header {position:relative; height:75mm; width:210.5mm;}
    .header div {position:absolute; bottom:15mm;right:15mm; }
    .header img.header {width:100%; height:100%}
    .header img.logo {width:30mm; height:30mm; position:absolute; top:5mm; left:10mm}
    
    .header .align-right {line-height:5mm}
    .small1, 
    .small2 {position:relative; right:0mm; top:10mm; width:75mm;border:2px solid #fff}
    .small1 {top:2mm} 
    .small2 {top:5mm}
    .small1 .col1,
    .small2 .col1 {width:66%}
    .small1 .col2,
    .small2 .col2{width:34%}
    
     div.big {position:relative; float:left; right:0mm;top:5mm;;width:200mm;}
     
    .big .col1{width:75%}
    .big .col2{width:12%}
    .big .col3{width:13%}
    
    .color1{background-color:#d6dce1; font-weight:bold; color:#76767a}
    .color2{background-color:#058cca; color:#fff; font-weight:bold}
    .borderbottom{border-bottom:1px solid #d6dce1}
    
    .paid-status {position:absolute; top:2mm;left:-125mm; padding:5px ;border:2px solid #525251}
    .text-footer {margin-left:5mm; width:200mm}
    
</style>
<page backleft="-20px" backtop="-20px">
    <div class="container">
        <div class="header">
            <div class="align-right">
                <?php if (!empty($order['company'])) { ?>
                    <b><?php echo $this->escape($order['company']); ?></b>
                    <br/>
                     <?php if (!empty($order['first_name']) && !empty($order['last_name'])) { ?>
                        <?php echo __('To the attention of') . ' ' . $this->escape($order['first_name']); ?> <?php echo $this->escape($order['last_name']); ?>
                        <br/>        
                    <?php } ?>
                <?php } else if (!empty($order['first_name']) && !empty($order['last_name'])) { ?>
                    <b><?php echo $this->escape($order['first_name']); ?> <?php echo $this->escape($order['last_name']); ?>
                    <br/>        
                <?php } ?>
                <?php if (!empty($order['address1'])) { ?>
                    <?php echo $this->escape($order['address1']); ?>
                    <br/>
                <?php } ?>
                <?php if (!empty($order['address2'])) { ?>
                    <?php echo $this->escape($order['address2']); ?>
                    <br/>
                <?php } ?>
                <?php 
                    $address = array();
                    if (!empty($order['zip_code'])) {
                        $address[] = $this->escape($order['zip_code']);
                    }
                    if (!empty($order['city'])) {
                        $address[] = $this->escape($order['city']);
                    }
                    echo $this->escape(join(', ', $address));
                ?>
                <br/>
                <?php if (!empty($order['state'])) { ?>
                    <?php echo $this->escape($order['state']); ?>
                    <br/>
                <?php } ?>
                
                <?php if (!empty($order['country'])) { ?>
                    <?php echo $this->escape($order['country']); ?>
                    <br/>
                <?php } ?>
                <?php if (!empty($order['id_number'])) { ?>
                    <?php echo $this->escape($order['id_number']); ?>
                    <br/>
                <?php } ?>
                <?php if (!empty($order['company_id'])) { ?>
                    <?php echo $this->escape($order['company_id']); ?>
                    <br/>
                <?php } ?>
                <?php if (!empty($order['company_vat'])) { ?>
                    N° TVA UE <?php echo $this->escape($order['company_vat']); ?>
                    <br/>
                <?php } ?>
            </div>    
            
        </div>    
        
        <div class="small1">
                <div style="position:absolute;left:-125mm;top:46.5mm">
                    <?php echo nl2br($config['invoice_text_description']); ?>
                </div>
                <table cellspacing="0">
                    <thead>
                        <tr class="borderbottom">
                            <th colspan=2 class="borderbottom">
                                <?php _e('Invoice'); ?>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="col1">
                                <?php _e('Order number'); ?>
                            </td>
                            <td class="align-right col2">
                                <?php echo $order['code'] ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?php _e('Invoice number'); ?>
                            </td>
                            <td class="align-right">
                                <?php echo $invoice['code'] ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?php _e('Time order'); ?>
                            </td>
                            <td class="align-right">
                                <?php echo $this->escape($order['time_create_view']); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?php _e('Time payment'); ?>
                            </td>
                            <td class="align-right">
                                <?php echo $this->escape($order['time_payment_view']); ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="color1">
                                <?php _e('Total all taxes included'); ?>
                            </td>
                            <td class="align-right color2">
                                <?php echo $this->escape($order['total_price_view']); ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <div class="clearfix"></div>
    
        </div>
        <div class="big">
                <table cellspacing="0" class="withborder">
                    <thead>
                        <tr class="">
                            <th class="col1 color1">
                                <?php _e('Product'); ?>
                            </th>
                            <th class="col2 color1">
                                <?php _e('Number'); ?>
                            </th>
                            <th class="align-right col3 color2">
                                <?php _e('Price'); ?>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($order['products'] as $product) { ?>
                            <tr>
                                <td>
                                    <?php echo $this->escape($product['details']['title']); ?>
                                </td>
                                <td class="align-center">
                                    <?php echo _number($this->escape($product['number'])); ?>
                                </td>
                                <td class="align-right">
                                    <?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['product_price'])); ?>
                                </td>
                            </tr>
                            <?php if ($product['discount_price']) { ?>
                                <tr>
                                    <td colspan=2>
                                        <?php _e('Discount'); ?>
                                    </td>
                                    <td class="align-right">
                                        <?php echo Pi::api('api', 'order')->viewPrice($this->escape($product['discount_price'])); ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            <?php $unconsumedPrice = $product['extra']['product']['unconsumedPrice'];?> 
                            <?php if ($unconsumedPrice) { ?>
                                <tr>
                                    <td colspan=2>
                                        <?php _e('Old package recovery'); ?>
                                    </td>
                                    <td class="align-right">
                                        <?php echo Pi::api('api', 'order')->viewPrice($this->escape($unconsumedPrice)); ?>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } ?>
                    </tbody>
                </table>
            <div class="clearfix"></div>
    
        </div>
        <div class="small2">
            <div class="paid-status">
                <strong><?php echo sprintf(__('Paid invoice (credit card / %s)'), $order['gateway']) ?></strong>
            </div>
            <table cellspacing="0">
                <tbody>
                    <tr>
                        <td class="col1 borderbottom">
                            <strong><?php _e('Product price ex VAT'); ?></strong>
                        </td>
                        <td class="align-right col2 borderbottom">
                            <?php echo $this->escape($order['total_product_price']); ?>
                        </td>
                    </tr>
                    <?php if ($order['shipping_price'] > 0) { ?>
                    <tr>
                        <td>
                            <?php _e('Shipping'); ?>
                        </td>
                        <td class="align-right">
                            <?php echo $this->escape($order['shipping_price_view']); ?>
                        </td>
                    </tr>
                    <?php } ?> 
                    <tr>
                        <td>
                            <?php _e('Vat'); ?>
                        </td>
                        <td class="align-right">
                            <?php echo $this->escape($order['vat_price_view']); ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="color1">
                            <?php _e('Total all taxes included'); ?>
                        </td>
                        <td class="align-right color2">
                            <?php echo $this->escape($order['total_price_view']); ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="clearfix"></div>
        </div>
        <br/>
        <p class="align-justify text-footer">
            <?php echo nl2br($config['invoice_text_footer']); ?>
        </p>
    </div>
 </page>
<page_footer>
    <div class="align-center">
        <hr/>
        <?php echo $config['order_sellerinfo']; ?>
    </div>
</page_footer>